### ISSUE TITLE
GCE Regional Instance Groups Supported by Cluster Autoscaler?

### ISSUE THREAD

**Issue by dd-caleb** [kubernetes/autoscaler#1003]
We've been successfully using the cluster autoscaler in AWS for a couple months and have recently tried to port our work to GCE as well. Unfortunately we haven't been able to get the cluster autoscaler to discover our **regional** managed instance groups.

Are regional managed instance groups currently supported?

It's possible I've simply misconfigured something. Here's our deployment (names slightly altered):

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
      - command:
        - ./cluster-autoscaler
        - --v=4
        - --stderrthreshold=info
        - --skip-nodes-with-local-storage=false
        - --expander=least-waste
        - --cloud-provider=gce
        - --node-group-auto-discovery=mig:namePrefix=staging-main-testcluster,min=0,max=10
        - --regional
        image: k8s.gcr.io/cluster-autoscaler:v1.2.2
        imagePullPolicy: Always
        name: cluster-autoscaler
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ssl-certs
          readOnly: true
      serviceAccount: cluster-autoscaler
      serviceAccountName: cluster-autoscaler
      volumes:
      - hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
          type: ""
        name: ssl-certs
```

The logs return:

```
I0621 10:50:49.338327       1 utils.go:404] Skipping staging-main-testcluster-nodepool-general-73p2 - no node group config
I0621 10:50:49.338331       1 utils.go:404] Skipping staging-main-testcluster-zookeeper-1-sxnx - no node group config
I0621 10:50:49.338335       1 utils.go:404] Skipping staging-main-testcluster-webapp-r84t - no node group config
...
```

And we have regional instance groups like:

```
staging-main-testcluster-nodepool-general
staging-main-testcluster-zookeeper-1-mig
staging-main-testcluster-webapp-mig
```

Looking at the code I see things like:

```go
// SetMigSize sets MIG size.
func (m *gceManagerImpl) SetMigSize(mig *Mig, size int64) error {
	glog.V(0).Infof("Setting mig size %s to %d", mig.Id(), size)
	op, err := m.gceService.InstanceGroupManagers.Resize(mig.Project, mig.Zone, mig.Name, size).Do()
	if err != nil {
		return err
	}
	return m.waitForOp(op, mig.Project, mig.Zone)
}
```

But I believe the Google API requires using the `RegionInstanceGroupManagers` field instead, which is why I'm wondering if this is supported yet. Apologies if this was documented somewhere and I simply missed it. 

Is support for this on the roadmap? If not we may take a stab at it if we can find the resources.
