### ISSUE TITLE
Version 1.1.3 | Auto Discovery not working

### ISSUE THREAD

**Issue by chrisduong** [kubernetes/autoscaler#1098]
Hi,

I'm using Version 1.1.3. I'm using Kubernetes version 1.9.x, I cannot use the version 1.3.x as the WARNing about compatibility.

I followed this guide https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws. But I've got the Error log

```
I0730 05:35:42.909028       1 auto_scaling.go:79] Failed to describe ASGs: Must specify at least one ASG name.
F0730 05:35:42.909055       1 cloud_provider_builder.go:112] Failed to create AWS cloud provider: Failed to get ASGs: List of ASG names was empty. Must specify at least one ASG name
```

My Deployment config is:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: aws-cluster-autoscaler
    chart: cluster-autoscaler-0.7.0
    heritage: Tiller
    release: cluster-ac
  name: cluster-ac-aws-cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cluster-autoscaler
      release: cluster-ac
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated", "value":"master"}]'
      creationTimestamp: null
      labels:
        app: aws-cluster-autoscaler
        release: cluster-ac
    spec:
      containers:
      - command:
        - ./cluster-autoscaler
        - --cloud-provider=aws
        - --namespace=kube-system
        - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/devops-kops.k8s.local
        - --logtostderr=true
        - --skip-nodes-with-local-storage
        - --stderrthreshold=info
        - --v=4
        env:
        - name: AWS_REGION
          value: ap-southeast-1
        image: k8s.gcr.io/cluster-autoscaler:v1.1.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check
            port: 8085
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: aws-cluster-autoscaler
        ports:
        - containerPort: 8085
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ssl-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/role: master
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cluster-ac-aws-cluster-autoscaler
      serviceAccountName: cluster-ac-aws-cluster-autoscaler
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
          type: ""
        name: ssl-certs
```
