### ISSUE TITLE
Cap recommendation upperBound to some sane value.

### ISSUE THREAD

**Issue by bskiba** [kubernetes/autoscaler#1182]
When we start providing recommendation for a VPA object, initially the upperBound is ridiculously high. This is confusing to the users and provides no information. We should cap this value to sth sane.

Some ideas are to cap upperBound to target recommendation +X cores or target recommendation + XX% of cores (analogous for memory).

**Comment by bskiba** [comment]
Need to choose a good capping value so that we will make sure this will not cause updater to start killing pods prematurely.

**Comment by Rajat-0** [comment]
I would like to work on this

**Comment by davidquarles** [comment]
I'm building/running current master and targeting a prometheus statefulset with no container memory limit and no `resourcePolicy` specified.  The pods were getting oom-killed for awhile before I deployed the vpa, if that's relevant.  Once stabilized, utilization was relatively low:
```
NAME           CPU(cores)   MEMORY(bytes)
prometheus-0   93m          1595Mi
prometheus-1   88m          1198Mi
```
but the recommender ended up with _very_ (unschedulably) high values for the memory request:
```
    - containerName: prometheus
      lowerBound:
        cpu: 92m
        memory: "2042845301"
      target:
        cpu: 109m
        memory: "1174275820239"
      uncappedTarget:
        cpu: 109m
        memory: "1174275820239"
      upperBound:
        cpu: 296m
        memory: "2762029041970"
```
I redeployed the vpa with a cap of 10Gi so that it would schedule and ingest some usage data, then tried removing the cap.  The recommendation target then returns to 1093Gi.  Does this sound correct, and is there any mitigation strategy outside of hard-capping, if so?  I'm not sure if i've done something wrong, or if it simply needs to be capped to function correctly today.
