### ISSUE TITLE
Feature Request: Cluster Autoscaler - scale up Deployment if PCB doesn't meet the scale down/drain requirements

### ISSUE THREAD

**Issue by AshMartian** [kubernetes/autoscaler#1298]
I'm looking over the cluster-autoscaler source to find where this could be added, not sure I have the go chops to submit a PR, but wanted to share this as a feature request.

I have a very RAM heavy microservice java app (20gb no load), in prod we'll run two of every service for HA. However our dev/test/stage environments it would be too expensive to run more than 1 of each service. 

I have each microservice in a deployment, with a Horizontal Pod Autoscaler to handle usage spikes / performance testing. 

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-autoscaler
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 700
```

In initial deployment in the dev environment, the cluster autoscaler caused significant occasional downtime as it balanced the cluster. These Java microservices sometimes take 4 minutes to become ready. So to avoid this, I applied a Pod Disruption Budget on each service.

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: service-budget
  namespace: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      run: service
```

So far so good. However since the Deployments have only 1 replica, this permanently blocks the cluster autoscaler from scaling down. 

There is an [issue on Kubernetes](https://github.com/kubernetes/kubernetes/issues/48307) relating to the kubectl drain in this scenario, but it's been closed due to inactivity. Seems like this use case for pdb wasn't recommended because it isn't HA with 1 replica. The argument being, Kubernetes *should* make 1 replica as available as possible were downtime even without a pdb should be avoided at all costs. 

The feature as follows.
- Check for pdb
- If a pdb is blocking a drain, scale the deployment/pod up until it meets the pdb criteria, ensuring the new pods are scheduled on ideal nodes.
- Wait for new Pods to become ready
- Drain the node

Maybe this could result in a new command argument that forces this behavior on all Deployments with 1 replica, without the need for a pdb.

As I search for a place to implement this, I found that [cluster-autoscaler/simulator/drain.go](https://github.com/kubernetes/autoscaler/blob/2908132f14d6edf362353690df6c6dd5a035ea1a/cluster-autoscaler/simulator/drain.go#L87) could be a starting place. From there I'm not sure how this could be implemented, but if there's any guidance where I could begin testing an implementation I'll gladly attempt to figure this out. 

One issue I see off the get go is determining if the pod is attached to a deployment, and if there is a horizontal autoscaler to read from to determine if scaling up is acceptable.
