### ISSUE TITLE
EKS IP-addresses limits

### ISSUE THREAD

**Issue by okgolove** [kubernetes/autoscaler#1366]
Hello. EKS uses AWS CNI to assign private IP to every pod https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI
So, if you haven't free IPs your pod won't be schedulded.

Can somehow autoscaler implements autoscaling based on IP limits?

**Comment by aleksandra-malinowska** [comment]
This is a non-trivial problem, and not just because it works differently for every cloud provider (e.g. on GCE, each nodes is assigned a range of IPs for pods). If I understand correctly, in this case IPs would be a cluster-level resource: it doesn't limit the number of nodes, and no matter how many we add, pods may not be able to run. Currently there's no support for such resources at all. It can probably be implemented by injecting a new pod list processor, which would remove pods that won't be able to run anyway from scale-up calculations.

**Comment by johanneswuerbach** [comment]
I'm not entirely sure cluster-autoscaler needs to do anything here, but your instances should be actually configured to only allow max IP address pods https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#options.

A change for that was recently implemented in kops https://github.com/kubernetes/kops/pull/6058, but I don't know whether this is done in EKS by default.

The max pods limit should also be recognised by the CA, but I'm not entirely sure whether it is, maybe @aleksandra-malinowska knows more?

**Comment by okgolove** [comment]
@johanneswuerbach hello, thank you for the feedback.
I have specified that option (--max-pods). It's exactly that thing I meant. As far I exhaust IP limit Kubernetes can't schedule any new pods. I meant it will be great if CA can handle these situations.

**Comment by aleksandra-malinowska** [comment]
I believe scheduler's predicates checks max pods per node limit. If it's not the case, it's probably a bug.

>  have specified that option (--max-pods). It's exactly that thing I meant. 

Can you verify if your nodes indeed have this set? `kubectl get node <node-name> -o yaml`

**Comment by okgolove** [comment]
@aleksandra-malinowska 

```
status:
  addresses:
  - address: 10.0.1.217
    type: InternalIP
  - address: ip-10-0-1-217.eu-west-1.compute.internal
    type: InternalDNS
  - address: ip-10-0-1-217.eu-west-1.compute.internal
    type: Hostname
  allocatable:
    cpu: "2"
    ephemeral-storage: "96625420948"
    hugepages-2Mi: "0"
    memory: 3937632Ki
    pods: "17"
  capacity:
    cpu: "2"
    ephemeral-storage: 104845292Ki
    hugepages-2Mi: "0"
    memory: 4040032Ki
    pods: "17"
```

Also I have a next option in kubelet-config.json:
```  "maxPods": 17```
