### ISSUE TITLE
[Proposal] Add cron pod autoscaler

### ISSUE THREAD

**Issue by hex108** [kubernetes/autoscaler#1439]
I have implemented a CronHPA which enables us to scale workloads(those support `scale` subresource) periodically using crontab scheme.  

## Use cases
A lot of game player will play games from Friday evening to Sunday evening. It will be better to provide a better experience for players if game servers(pods) could be scaled to a lager size at Friday evening and scaled to normal size at Sunday evening. And that's what game server admins do every week. 

Some other customers also do similar things because their products' usage also have peaks and valleys periodically. CronHPA is for their requirement.

## CronHPA example:

```
---
apiVersion: gs.io/v1alpha1
kind: CronHPA
metadata:
  name: example-cron-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: demo-deployment
  crons:
    - schedule: "0 23 * * 5"  // Set replicas to 60 every Friday 23:00
      targetReplicas: 60
    - schedule: "0 23 * * 7"  // Set replicas to 30 every Sunday 23:00
      targetReplicas: 30

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

BTW: Not sure it is the right place to send this proposal. If it is, I'll send a PR.
