### ISSUE TITLE
Confusing error message when applying a VerticalPodAutoscaler with boolean value for spec.updatePolicy.updateMode

### ISSUE THREAD

**Issue by davidxia** [kubernetes/autoscaler#1455]
I tried to apply the VerticalPodAutoscaler YAML below.

```yaml
apiVersion: "poc.autoscaling.k8s.io/v1alpha1"
kind: "VerticalPodAutoscaler"
metadata:
  name: "foo"
spec:
  selector:
    matchLabels:
      app: "foo"
  updatePolicy:
    updateMode: Off
```

## What happened

I didn't realize an unquoted `Off` is a YAML boolean false. This lead to the following error.

```
kubectl apply -f /path/to/file/above

error: error when creating "/path/to/file/above": Post https://<master-IP>/apis/poc.autoscaling.k8s.io/v1alpha1/namespaces/default/verticalpodautoscalers: unexpected EOF; some request body already written
```

Everything works as expected if I quote the `Off` to `"Off"`.

## What I expected

Perhaps the error message from the API could be more helpful. Maybe some early validation on the value of `updateMode` would help.

## kube versions

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.11", GitCommit:"42df8ec7aef509caba40b6178616dcffca9d7355", GitTreeState:"clean", BuildDate:"2018-11-08T20:06:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
