### ISSUE TITLE
addon resizer changes `optional: true` of volume mounts

### ISSUE THREAD

**Issue by williamhuangh** [kubernetes/autoscaler#1457]
original yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
  annotations:
    k8sdeploy.lyft.net/skip-rollout-monitoring: true
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
        version: ${sha}
    spec:
      serviceAccount: prometheus
      securityContext:
        runAsUser: 0 # This is required to use the EBS volume which is owned by root
      containers:
      - name: addon-resizer
        image: k8s.gcr.io/addon-resizer:1.7
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 30Mi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --container=prometheus
          - --cpu=3
          - --extra-cpu=10m
          - --memory=2Gi
          - --extra-memory=100Mi
          - --threshold=5
          - --deployment=prometheus        
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.3.2
        args:
            - '--config.file=/etc/prometheus/prometheus.yaml'
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle            
        ports:
        - name: web
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 8
            memory: 12000Mi
          requests:
            cpu: 3
            memory: 2000Mi
        env:
        - name: STORAGE_RETENTION
          valueFrom:
            configMapKeyRef:
              name: prometheus-env
              key: storage-retention
        - name: STORAGE_MEMORY_CHUNKS
          valueFrom:
            configMapKeyRef:
              name: prometheus-env
              key: storage-memory-chunks
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: rules
          mountPath: /etc/prometheus/rules
        - name: rules-ingress
          mountPath: /etc/prometheus/rules/ingress
        - name: rules-custom
          mountPath: /etc/prometheus/rules/services
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-configmap
      - name: rules
        configMap:
          name: prometheus-rules
      - name: rules-ingress
        configMap:
          name: prometheus-rules-ingress
          optional: true
      - name: rules-custom
        configMap:
          name: prometheus-rules-custom
          optional: true
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus
```
after addon-resizer
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        version: 7c4cf683790c010aba8698883f245fdacee706d1
      name: prometheus
    spec:
      containers:
      - command:
        - /pod_nanny
        - --container=prometheus
        - --cpu=3
        - --extra-cpu=10m
        - --memory=2Gi
        - --extra-memory=100Mi
        - --threshold=5
        - --deployment=prometheus-deployment
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: k8s.gcr.io/addon-resizer:1.7
        imagePullPolicy: IfNotPresent
        name: addon-resizer
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 30Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --config.file=/etc/prometheus/prometheus.yaml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --web.enable-lifecycle
        env:
        - name: STORAGE_RETENTION
          valueFrom:
            configMapKeyRef:
              key: storage-retention
              name: prometheus-env
        - name: STORAGE_MEMORY_CHUNKS
          valueFrom:
            configMapKeyRef:
              key: storage-memory-chunks
              name: prometheus-env
        image: quay.io/prometheus/prometheus:v2.3.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: prometheus
        ports:
        - containerPort: 9090
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 3110m
            memory: 3148Mi
          requests:
            cpu: 3110m
            memory: 3148Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config-volume
        - mountPath: /etc/prometheus/rules
          name: rules
        - mountPath: /etc/prometheus/rules/ingress
          name: rules-ingress
        - mountPath: /etc/prometheus/rules/services
          name: rules-custom
        - mountPath: /prometheus
          name: prometheus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: prometheus
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-configmap
        name: config-volume
      - configMap:
          defaultMode: 420
          name: prometheus-rules
        name: rules
      - configMap:
          defaultMode: 420
          name: prometheus-rules-ingress
        name: rules-ingress
      - configMap:
          defaultMode: 420
          name: prometheus-rules-custom
        name: rules-custom
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus
```
notice that it drops the `optional: true` from volumes
