### ISSUE TITLE
affinity for daemonset pod blocks scale-up

### ISSUE THREAD

**Issue by max-radin** [kubernetes/autoscaler#1520]
I'd like to add a pod affinity rule that requires my pod to run on a node that already is running a fluentd logging pod. (The fluentd pods are launched by a daemonset.) My affinity rule looks like:
```yaml
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - fluentd-logging
        topologyKey: kubernetes.io/hostname
```
Unfortunately this prevents the autoscalerfrom scaling up – see log below. 
```
I1220 23:52:25.618948       1 scale_up.go:152] Scale-up predicate failed: MatchInterPodAffinity predicate mismatch, cannot put default/h2-zwq56-1824281309 on template-node-for-m4_2xlarge-7056460638582648182, reason: node(s) didn't match pod affinity/anti-affinity,node(s) didn't match pod affinity rules
```
It would be great if the autoscaler would scale-up in this situation; i.e. recognize that if a new node was created, then a daemonset would launch a pod satisfying the interpod affinity rules for a pod that currently has no node to run on.

One workaround would be to tell the autoscaler to ignore interpod affinity rules – is there an easy way to do this?
