### ISSUE TITLE
Issue with Vertical Pod Autoscaler in Helm chart

### ISSUE THREAD

**Issue by thereverendtom** [kubernetes/autoscaler#1554]
I have added the Vertical Pod Autoscaler to my k8s cluster (version 1.10.3), and I added several VPAs to one of my Helm charts. An example looks like this:

```
apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: web-vpa
  namespace: zeus-dev
spec:
  selector:
    matchLabels:
      app: web
  updatePolicy:
    updateMode: "Off"
```

My first Helm deployment worked without issue and the VPA appears to be functioning as intended. However, upon my next Helm deployment (no change to the VPA - just an unrelated code change), I get the following error:

`Error: UPGRADE FAILED: no VerticalPodAutoscaler with the name "web-vpa" found`

But when I query the cluster, the VPA is there:

```
kubectl get verticalpodautoscaler -n zeus-dev
NAME                                     CREATED AT
web-vpa                                  7d
```

I am running the latest version of Helm (2.12.1) and the most recent version of the VPA as of Dec 28. When I remove the VPA definitions from my chart, the Helm deployment succeeds.

Has anyone else encountered this?
