### ISSUE TITLE
VPA: allow running outside kube-system namespace

### ISSUE THREAD

**Issue by mgoodness** [kubernetes/autoscaler#1572]
AFAICT there's no technical reason vertical-pod-autoscaler needs to run in `kube-system`. The only impediment today seems to be that the webhook self-registration has the namespace hardwired. May I submit a PR that allows the use of a `NAMESPACE` environment variable to override?

**Comment by bskiba** [comment]
Sounds absolutely reasonable, please go ahead. 

I assume admission controller will accept a --vpa-namespace flag and the deployment files will use a similar overriding mechanism as currently used for REGISTRY and TAG:
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/vpa-process-yaml.sh#L37

**Comment by mgoodness** [comment]
My thought in suggesting an environment variable is that the downward API could then be used to set the namespace.

We could add
```
      env:
       - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
to the admission-controller Deployment, eliminating any additional user-facing configuration.
