### ISSUE TITLE
Updater not set resources request on pods

### ISSUE THREAD

**Issue by qw1mb0** [kubernetes/autoscaler#1588]
I installed VPA 0.3.0 in a cluster 1.10.8 on two nodes and a master in GCE.

Have enabled MutatingAdmissionWebhook:
```
# kubectl -n kube-system get pod kube-apiserver-master-europe-west1-b-l6x1 -o yaml | grep MutatingAdmissionWebhook
      --cloud-provider=gce --enable-admission-plugins=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,NodeRestriction,ResourceQuota
```
and enabled api:
```
# kubectl api-versions | grep admissionregistration.k8s.io
admissionregistration.k8s.io/v1beta1
```

And I wanted to check his work by applying such yaml:
```
apiVersion: "autoscaling.k8s.io/v1beta1"
kind: VerticalPodAutoscaler
metadata:
  name: hamster-vpa
spec:
  selector:
    matchLabels:
      app: hamster
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hamster
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hamster
    spec:
      containers:
      - name: hamster
        image: k8s.gcr.io/ubuntu-slim:0.1
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 250Mi
        command: ["/bin/sh"]
        args: ["-c", "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"]
```

It's deployed to cluster:
```
# kubectl get vpa,pod
NAME                                                   AGE
verticalpodautoscaler.autoscaling.k8s.io/hamster-vpa   3h

NAME                           READY     STATUS    RESTARTS   AGE
pod/hamster-5c6f76c9bb-4lbwt   1/1       Running   0          2m
pod/hamster-5c6f76c9bb-h7tqm   1/1       Running   0          37s
```

Every 1m one of pod recreate and I see on **Updater** logs:

```
I0116 23:01:37.161863       5 update_priority_calculator.go:118] pod accepted for update hamster-5c6f76c9bb-h7tqm with priority 6
I0116 23:01:37.162488       5 update_priority_calculator.go:118] pod accepted for update hamster-5c6f76c9bb-4lbwt with priority 6
I0116 23:01:37.162567       5 updater.go:137] evicting pod hamster-5c6f76c9bb-h7tqm
I0116 23:01:37.270985       5 updater.go:195] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"hamster-5c6f76c9bb-h7tqm", UID:"898279de-19e2-11e9-8af9-42010a840006", APIVersion:"v1", ResourceVersion:"32694081", FieldPath:""}): type: 'Normal' reason: 'EvictedByVPA' Pod was evicted by VPA Updater to apply resource recommendation.
```

See that vpa can fetch metrics seen on VPA object:
```
# kubectl describe vpa/hamster-vpa
Name:         hamster-vpa
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"autoscaling.k8s.io/v1beta1","kind":"VerticalPodAutoscaler","metadata":{"annotations":{},"name":"hamster-vpa","namespace":"default"},"spe...
API Version:  autoscaling.k8s.io/v1beta1
Kind:         VerticalPodAutoscaler
Metadata:
  Cluster Name:        
  Creation Timestamp:  2019-01-16T19:57:50Z
  Generation:          1
  Resource Version:    32694279
  Self Link:           /apis/autoscaling.k8s.io/v1beta1/namespaces/default/verticalpodautoscalers/hamster-vpa
  UID:                 011af3da-19c9-11e9-8af9-42010a840006
Spec:
  Selector:
    Match Labels:
      App:  hamster
Status:
  Conditions:
    Last Transition Time:  2019-01-16T19:59:11Z
    Status:                True
    Type:                  RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  hamster
      Lower Bound:
        Cpu:     503m
        Memory:  262144k
      Target:
        Cpu:     671m
        Memory:  262144k
      Uncapped Target:
        Cpu:     671m
        Memory:  262144k
      Upper Bound:
        Cpu:     6200m
        Memory:  262144k
Events:          <none>

```

But every new pod have old resource request: 

```
# kubectl get pod
kNAME                       READY     STATUS    RESTARTS   AGE
hamster-5c6f76c9bb-4lbwt   1/1       Running   0          4m
hamster-5c6f76c9bb-7rmcz   1/1       Running   0          46s

# kubectl describe pod hamster-5c6f76c9bb-7rmcz
Name:           hamster-5c6f76c9bb-7rmcz
Namespace:      default
Node:           nodes-z27n/10.132.0.5
Start Time:     Wed, 16 Jan 2019 23:02:37 +0000
Labels:         app=hamster
                pod-template-hash=1729327566
Annotations:    <none>
Status:         Running
IP:             100.96.2.97
Controlled By:  ReplicaSet/hamster-5c6f76c9bb
Containers:
  hamster:
    Container ID:  docker://140bf6968b8cd041bea1587f0daf9a245e211d60b635d347fbcb038dade85429
    Image:         k8s.gcr.io/ubuntu-slim:0.1
    Image ID:      docker-pullable://k8s.gcr.io/ubuntu-slim@sha256:b6f8c3885f5880a4f1a7cf717c07242eb4858fdd5a84b5ffe35b1cf680ea17b1
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done
    State:          Running
      Started:      Wed, 16 Jan 2019 23:02:38 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     300m
      memory:  250Mi
    Requests:
      cpu:        100m
      memory:     50Mi
```

And i not see some annotations on these pods.

Why VPA not working for me? Helm please.
