### ISSUE TITLE
[AWS] Autoscaling not working with podAntiAffinity and topologyKey failure-domain.beta.kubernetes.io/zone

### ISSUE THREAD

**Issue by MoJo2600** [kubernetes/autoscaler#1681]
Hello,

I'm not sure if this is an issue or I am using the autoscaler wrong. So any advice is highly appreciated. I have a cluster set up with kops which is currently running in 1 AZ, but the Autoscaling Group is set up to use multiple AZs. On pod is already running on this node. The second node has the following podAntiAffinity configured:

```
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - theotherpod
        topologyKey: failure-domain.beta.kubernetes.io/zone
```
This pod is now all the time in Pending state. The message is:
`NotTriggerScaleUp  37s (x3 over 3m39s)   cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't match pod anti-affinity rules, 1 node(s) didn't match pod affinity/anti-affinity`

The autoscaling does work with when the topologyKey is set to `kubernetes.io/hostname`

I think the autoscaler has no idea, that a new node would be started in another region an it would then fit. Can this be somehow configured?

Best regards

Christian
