### ISSUE TITLE
It does NOT scale in

### ISSUE THREAD

**Issue by khteh** [kubernetes/autoscaler#1741]
Here is my HPA definition:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  namespace: default 
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: StatefulSet
    name: myapp
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
```
`kubectl top pods`:
```
myapp-0            3m           499Mi           
myapp-1            3m           454Mi           
myapp-2            3m           469Mi     
```
`kubectl get hpa`:
```
my-hpa    StatefulSet/myapp    46%/50%, 0%/50%   2         5         3          16d
```
I expect it to have only 2 replicas (minReplicas) since the metrics suggest that the CPU and RAM utilization are well below the water marks.

**Comment by aleksandra-malinowska** [comment]
Can you share pod spec (in particular, resource requests)?

**Comment by khteh** [comment]
Main container:
```
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
```
Sidecar:
```
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
```
