### ISSUE TITLE
[addon-resizer] deployment update drops existing nodeAffinity fields

### ISSUE THREAD

**Issue by jstangroome** [kubernetes/autoscaler#1799]
Seems to be a repeat of issue #188.

Using addon-resizer Docker image: `gcr.io/google-containers/addon-resizer-amd64:2.1`

Original deployment yaml contains:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # ... truncated ...
spec:
  template:
      # ... truncated ...
      tolerations:
      - key: the-taint
        effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: the-taint
                operator: Exists
```

And after addon-resizer logs "Resources are not within the expected limits, updating the deployment", the `apiVersion` has regressed to `extensions/v1beta1` and both the `tolerations` and `affinity` members have been removed.
