### ISSUE TITLE
Autoscaler was frequently killed for liveness proble failed

### ISSUE THREAD

**Issue by ccic** [kubernetes/autoscaler#1800]
Why the liveness probe fails so frequently?
Liveness probe failed: HTTP probe failed with statuscode: 500

![image](https://user-images.githubusercontent.com/19297121/54513402-4ef14b80-4992-11e9-8b11-95a592402c3c.png)

**Comment by aleksandra-malinowska** [comment]
1) Can you share your CA deployment (yaml with pod spec)? 
2) Can you check if CA logs anything before it's killed?

**Comment by Tzrlk** [comment]
I'm having the same issue, but I suspect it's because I haven't supplied it the required AWS permissions yet. Here's my deploy spec:
```yaml
---
# Source: operations/charts/cluster-autoscaler/templates/deployment.yml
apiVersion: apps/v1
kind:       Deployment

metadata:
  namespace: operations
  name:      cluster-autoscaler

  labels:
    app.kubernetes.io/name:       cluster-autoscaler
    app.kubernetes.io/instance:   operations
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/version:    v1.12.3
    helm.sh/chart:                cluster-autoscaler-0.1.0
    k8s-addon:                    cluster-autoscaler.addons.k8s.io

spec:
  replicas:             1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app.kubernetes.io/name:       cluster-autoscaler
      app.kubernetes.io/instance:   operations

  template:

    metadata:
      labels:
        app.kubernetes.io/name:       cluster-autoscaler
        app.kubernetes.io/instance:   operations
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/version:    v1.12.3
        helm.sh/chart:                cluster-autoscaler-0.1.0
        k8s-addon:                    cluster-autoscaler.addons.k8s.io

    spec:
      serviceAccountName: cluster-autoscaler
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
        - { effect: NoSchedule, key: node-role.kubernetes.io/master, value: 'true' }
      volumes:
        - { name: ssl-certs, hostPath: { path: '/etc/ssl/certs/ca-bundle.crt' } }
      containers:

        - name:  cluster-autoscaler
          image: k8s.gcr.io/cluster-autoscaler:v1.12.3
          volumeMounts:
            - { name: ssl-certs, mountPath: /etc/ssl/certs/ca-certificates.crt, readOnly: true }
          env:
            - { name: POD_NAMESPACE, valueFrom: { fieldRef: { fieldPath: metadata.namespace } } }
          # https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca
          command:
            - ./cluster-autoscaler
            - --address=:9101
            - --namespace=$(POD_NAMESPACE)
            - --stderrthreshold=info
            - --cluster-name=[redacted]
            - --cloud-provider=aws
            - --regional=true
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --balance-similar-node-groups=true
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/[redacted]
          ports:
            - { name: metrics, containerPort: 9101 }
          livenessProbe:
            httpGet: { port: metrics, path: /health-check }
          readinessProbe:
            httpGet: { port: metrics, path: /metrics }
          resources:
            requests: { cpu: 100m, memory: 300Mi }
            limits:   { cpu: 100m, memory: 300Mi }

     affinity:
       podAntiAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:

           # Try not to schedule two cluster autoscalers on the same node.
           - weight: 100
             podAffinityTerm:
               topologyKey: kubernetes.io/hostname
               labelSelector:
                 matchLabels:
                   app.kubernetes.io/name: cluster-autoscaler
```
My logs:
```
I0410 05:45:38.354222       1 leaderelection.go:187] attempting to acquire leader lease  operations/cluster-autoscaler...
I0410 05:45:38.422125       1 leaderelection.go:196] successfully acquired lease operations/cluster-autoscaler
E0410 05:45:40.667652       1 aws_manager.go:153] Failed to regenerate ASG cache: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::[redacted]:assumed-role/[redacted]/[redacted] is not authorized to perform: autoscaling:DescribeTags
	status code: 403, request id: dfc678a7-5b53-11e9-8a28-7343d1ac6e28
F0410 05:45:40.667672       1 cloud_provider_builder.go:149] Failed to create AWS Manager: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::[redacted]:assumed-role/[redacted]/[redacted] is not authorized to perform: autoscaling:DescribeTags
	status code: 403, request id: [redacted]
```

I assumed that the service would just retry until it was able to perform the needed operation, as the service would still be "live", just not "ready".

**Comment by MichalPloski** [comment]
@aleksandra-malinowska  We have a similar problem that occurred recently.

Last lines of its logs:
```
I0726 15:25:50.154040       1 reflector.go:286] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:149: forcing resync
I0726 15:25:50.178998       1 reflector.go:286] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:174: forcing resync
I0726 15:27:58.643672       1 main.go:232] Received signal, attempting cleanup
```
Describe fragments:
```
Liveness:       http-get http://:8085/health-check delay=0s timeout=1s period=10s #success=1 #failure=3

Last State:     Terminated
      Reason:       Error
      Exit Code:    137
```
Event log:
```
LAST SEEN   TYPE      REASON                 KIND        MESSAGE
14m         Normal    Created                Pod         Created container
14m         Normal    Started                Pod         Started container
14m         Warning   Unhealthy              Pod         Liveness probe failed: HTTP probe failed with statuscode: 500
14m         Normal    Killing                Pod         Killing container with id docker://aws-cluster-autoscaler:Container failed liveness probe.. Container will be killed and recreated.
14m         Normal    Pulled                 Pod         Container image "k8s.gcr.io/cluster-autoscaler:v1.2.2" already present on machine
14m         Normal    LeaderElection         Endpoints   cluster-autoscaler-aws-cluster-autoscaler-76677dfd4-jlggz became leader
```


yaml:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
  labels:
    app: aws-cluster-autoscaler
    chart: cluster-autoscaler-0.7.0
    heritage: Tiller
    release: cluster-autoscaler
  name: cluster-autoscaler-aws-cluster-autoscaler
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: aws-cluster-autoscaler
      release: cluster-autoscaler
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aws-cluster-autoscaler
        release: cluster-autoscaler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - aws-cluster-autoscaler
            topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - command:
        - ./cluster-autoscaler
        - --cloud-provider=aws
        - --namespace=kube-system
        - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/production
        - --expander=least-waste
        - --logtostderr=true
        - --scale-down-utilization-threshold=0.6
        - --skip-nodes-with-local-storage
        - --stderrthreshold=info
        - --v=4
        env:
        - name: AWS_REGION
          value: us-east-1
        image: k8s.gcr.io/cluster-autoscaler:v1.2.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check
            port: 8085
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: aws-cluster-autoscaler
        ports:
        - containerPort: 8085
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca-bundle.crt
          name: ssl-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        type: privileged
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: cluster-autoscaler-aws-cluster-autoscaler
      serviceAccountName: cluster-autoscaler-aws-cluster-autoscaler
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: privileged
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/ssl/certs/ca-bundle.crt
          type: ""
        name: ssl-certs
```
