### ISSUE TITLE
cluster-autoscaler scales down to point pods go into pending

### ISSUE THREAD

**Issue by tweeks024** [kubernetes/autoscaler#1836]
We are running kubernetes v1.13.3 and cluster-autoscaler v1.13.2 (seems to be the latest on 1.13).  The primary constraint in this cluster is memory.

When all deployments are created a number of pods go into Pending.  The CA adds nodes as expected and the pods are scheduled.  However, after the scale-down timers expire the nodes are scaled back down and pods  go into pending.

CA is also not removing these nodes gracefully from the kubernetes cluster (not sure if this is expected).  This continues in a loop until CA see's the cluster as unhealthy due to too many nodes in the NotReady state.   I've tried updating  ```scale-down-utilization-threshold``` to as low as 0.05 with no change in behavior.

Here is my CA config:

```
    command:
    - ./cluster-autoscaler
    - --v=4
    - --stderrthreshold=info
    - --cloud-provider=aws
    - --balance-similar-node-groups
    - --skip-nodes-with-local-storage=false
    - --expander=least-waste
    - --scale-down-utilization-threshold=0.1
    - --nodes=0:5:kube_node_shared_eng_asg_a
    - --nodes=0:5:kube_node_shared_eng_asg_b
```

An example deployment is like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myApp
  namespace: shared-int
  labels:
    app: myApp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - myApp
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Xms512m -Xmx512m
        image: myApp
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          tcpSocket:
            port: 9019
          timeoutSeconds: 3
        name: myApp
        ports:
        - containerPort: 9019
        - containerPort: 9020
        readinessProbe:
          httpGet:
            path: /health
            port: 9020
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 3
        resources:
          limits:
            cpu: '1'
            memory: 1024Mi
          requests:
            cpu: '0'
            memory: 768Mi
      restartPolicy: Always
```

*kubectl get nodes*
``` 
NAME                                            STATUS     ROLES    AGE     VERSION
kube01-shared-eng          Ready      master   40d     v1.13.3
kube02-shared-eng          Ready      master   40d     v1.13.3
kube03-shared-eng          Ready      master   40d     v1.13.3
node-shared-eng-121-159-1a NotReady   <none>   44h     v1.13.3
node-shared-eng-121-217-1a NotReady   <none>   45h     v1.13.3
node-shared-eng-122-145-1b NotReady   <none>   45h     v1.13.3
node-shared-eng-122-161-1b NotReady   <none>   4d17h   v1.13.3
node-shared-eng-122-20-1b  NotReady   <none>   44h     v1.13.3
node-shared-eng-122-251-1b NotReady   <none>   45h     v1.13.3
node01-shared-eng          Ready      <none>   33d     v1.13.3
node02-shared-eng          Ready      <none>   33d     v1.13.3
node03-shared-eng          Ready      <none>   33d     v1.13.3
```

*kubectl get pods --all-namespaces  | grep -i pending*
```
shared-int      api-gateway-shared-int-6987cdfb89-t4ckx                        0/1     Pending       0          44h
shared-int      events-classes-service-shared-int-56b598df95-6295g             0/1     Pending       0          44h
shared-int      events-classes-service-shared-int-56b598df95-tb2kz             0/1     Pending       0          44h
shared-int      platform-api-gateway-shared-int-55bbff97d5-2rlp7               0/1     Pending       0          44h
shared-int      platform-api-gateway-shared-int-55bbff97d5-789ws               0/1     Pending       0          44h
shared-int      redis-shared-int-5b4fc4658b-9zfc6                              0/1     Pending       0          44h
shared-int      template-expander-service-shared-int-6d44875745-6cvs2          0/1     Pending       0          44h
shared-int      timetrade-authserver-shared-int-5c7ffcd98-jhcdv                0/1     Pending       0          44h
shared-int      timetrade-authserver-shared-int-5c7ffcd98-pwvwg                0/1     Pending       0          44h
shared-test     events-classes-service-shared-test-99c89c574-z44pv             0/1     Pending       0          44h
shared-test     ews-notifications-shared-test-78c7cf59f4-8fjtc                 0/1     Pending       0          44h
shared-test     redis-shared-test-6dcfc6699f-n4n8c                             0/1     Pending       0          44h
shared-test     template-expander-service-shared-test-774cb6c67-84gtb          0/1     Pending       0          44h
shared-test     translation-service-shared-test-d5497dd4f-cm7j9                0/1     Pending       0          44h
```

*kubectl -n kube-system describe configmap cluster-autoscaler-status*
```
Name:         cluster-autoscaler-status
Namespace:    kube-system
Labels:       <none>
Annotations:  cluster-autoscaler.kubernetes.io/last-updated: 2019-03-27 14:16:30.080714192 +0000 UTC

Data
====
status:
----
Cluster-autoscaler status at 2019-03-27 14:16:30.080714192 +0000 UTC:
Cluster-wide:
  Health:      Unhealthy (ready=6 unready=6 notStarted=0 longNotStarted=0 registered=12 longUnregistered=0)
               LastProbeTime:      2019-03-27 14:16:29.751461837 +0000 UTC m=+163779.430960818
               LastTransitionTime: 2019-03-25 17:45:10.352154648 +0000 UTC m=+3500.031653585
  ScaleUp:     NoActivity (ready=6 registered=12)
               LastProbeTime:      2019-03-27 14:16:29.751461837 +0000 UTC m=+163779.430960818
               LastTransitionTime: 2019-03-25 17:45:41.281835145 +0000 UTC m=+3530.961334115
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC

NodeGroups:
  Name:        kube_node_shared_eng_asg_a
  Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=0 (minSize=0, maxSize=5))
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 2019-03-25 16:47:20.002716092 +0000 UTC m=+29.682214982
  ScaleUp:     NoActivity (ready=0 cloudProviderTarget=0)
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 2019-03-25 17:50:50.554241419 +0000 UTC m=+3840.233740372
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC

  Name:        kube_node_shared_eng_asg_b
  Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=0 (minSize=0, maxSize=5))
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 2019-03-25 16:47:20.002716092 +0000 UTC m=+29.682214982
  ScaleUp:     NoActivity (ready=0 cloudProviderTarget=0)
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 2019-03-25 17:55:50.294492045 +0000 UTC m=+4139.973990950
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC


Events:
  Type     Reason            Age                     From                Message
  ----     ------            ----                    ----                -------
  Warning  ClusterUnhealthy  4m2s (x15591 over 44h)  cluster-autoscaler  Cluster is unhealthy
```
