### ISSUE TITLE
addon-resizer modifies different attributes than request/limit only

### ISSUE THREAD

**Issue by piontec** [kubernetes/autoscaler#1858]
We're running addon-resizer with https://github.com/kubernetes/kube-state-metrics, which is the default deployment. Unfortunately, addon-resizer changes other properties than limits/requests on the managed pod:
```
   name: kube-state-metrics
   namespace: kube-system
 spec:
-  progressDeadlineSeconds: 2147483647
+  progressDeadlineSeconds: 600
   replicas: 1
   revisionHistoryLimit: 10
   selector:
@@ -189,6 +189,7 @@
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
       dnsPolicy: ClusterFirst
+      priorityClassName: system-cluster-critical
       restartPolicy: Always
       schedulerName: default-scheduler
       securityContext: {}
```

SInce the code seems to not update them anywhere, it must be a bug in underlying libs.
