### ISSUE TITLE
[cluster-autoscaler] Unable to build proper template node for cluster

### ISSUE THREAD

**Issue by Tzrlk** [kubernetes/autoscaler#1943]
My logs are currently full of this:
```
E0423 XX:XX:XX.XXXXXX       1 utils.go:291] Unable to build proper template node for [redacted]: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: [redacted]
```

Cloudformation permissions:
```yaml
  ClusterAutoscalerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWS::StackName}_AutoscalerPolicy'
      Users:      [ !Ref ClusterAutoscalerUser ]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect:   Allow
            Resource: '*'
            Action:
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeTags
              - autoscaling:SetDesiredCapacity
              - autoscaling:TerminateInstanceInAutoScalingGroup
```

Cloudformation worker ASG:
```yaml
  AutoScalingGroupAz1:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version:          !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:      [ !Ref SubnetAz1 ]
      Cooldown:               '360'
      DesiredCapacity:        '1'
      HealthCheckGracePeriod: 300
      HealthCheckType:        EC2
      MaxSize:                !Ref ScalingMax
      MinSize:                '1'
      TerminationPolicies:    [ Default ]
      NotificationConfigurations:
        - TopicARN: !Ref TopicScaling
          NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      MetricsCollection:
        - Granularity: 1Minute
          Metrics:
            - GroupMaxSize
            - GroupDesiredCapacity
            - GroupMinSize
            - GroupTotalInstances
            - GroupPendingInstances
            - GroupInServiceInstances
            - GroupStandbyInstances
            - GroupTerminatingInstances
      Tags:
        - { Key: !Sub 'kubernetes.io/cluster/${EksCluster}',     Value: 'owned', PropagateAtLaunch: true  }
        - { Key:      'k8s.io/cluster-autoscaler/enabled',       Value: 'true',  PropagateAtLaunch: false }
        - { Key: !Sub 'k8s.io/cluster-autoscaler/${EksCluster}', Value: 'true',  PropagateAtLaunch: false }
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize:          1
```

Cloudformation worker Launch Template:
```yaml
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType:       c5.2xlarge
        ImageId:            !Ref InstanceAmi
        KeyName:            !Ref InstanceSshKey
        IamInstanceProfile: { Arn: !Ref InstanceProfile }
        Monitoring:
          Enabled:          true
        NetworkInterfaces:
          - DeviceIndex:              0
            AssociatePublicIpAddress: false
            Groups:                   [ !Ref SecurityGroup ]
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType:          gp2
              VolumeSize:          !Ref InstanceVolumeSize
              DeleteOnTermination: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -o xtrace
            /etc/eks/bootstrap.sh ${EksCluster} \
                --apiserver-endpoint ${EksClusterEndpoint} \
                --b64-cluster-ca     ${EksClusterCacert} \
                --kubelet-extra-args "--node-labels=kubernetes.io/role=worker"
            /opt/aws/bin/cfn-signal --exit-code $? \
                --stack    ${AWS::StackName} \
                --resource NodeGroup \
                --region   ${AWS::Region}
        TagSpecifications:

          - ResourceType: instance
            Tags:
              - { Key: Name, Value: 'EKS Worker Node' }

          - ResourceType: volume
            Tags:
              - { Key: Name, Value: 'EKS Worker Node Storage' }
```

`kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

autoscaler container spec:
```yaml
        - name:  cluster-autoscaler
          image: k8s.gcr.io/cluster-autoscaler:v1.12.3
          volumeMounts:
            - { name: ssl-certs, mountPath: /etc/ssl/certs/ca-certificates.crt, readOnly: true }
          envFrom:
            - secretRef: { name: cluster-autoscaler }
          env:
            - { name: POD_NAMESPACE, valueFrom: { fieldRef: { fieldPath: metadata.namespace } } }
          # https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca
          command:
            - ./cluster-autoscaler
            - --address=:9101
            - --namespace=$(POD_NAMESPACE)
            - --stderrthreshold=info
            - --cluster-name=[redacted]
            - --cloud-provider=aws
            - --regional=true
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --balance-similar-node-groups=true
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/[redacted]
          ports:
            - { name: metrics, containerPort: 9101 }
          livenessProbe:
            httpGet: { port: metrics, path: /health-check }
          readinessProbe:
            httpGet: { port: metrics, path: /metrics }
          resources:
            requests: { cpu: 100m, memory: 300Mi }
            limits:   { cpu: 100m, memory: 300Mi }
```

I've looked through the code a bit, and it's not really much clearer as to what exactly is failing, and why the permissions supplied in the setup documentation aren't enough.
