### ISSUE TITLE
Autoscaler wrong calculate wasted resource on AWS

### ISSUE THREAD

**Issue by alantang888** [kubernetes/autoscaler#1985]
I just faced a problem with 3 kops instance groups. Each on single AZ. Only the subnet and name is different. Others are identical. 
But autoscaler calculated zone A have less memory wasted. That make autoscaler always scale up node on zone A. (Now changed `expander` to random to avoid it.)

Autoscaler log is:
```
I0506 07:50:30.800585       1 waste.go:57] Expanding Node Group nodes-applications-1a.k8s.dev.xxx.xxx would waste 52.50% CPU, 88.46% Memory, 70.48% Blended
I0506 07:50:30.800613       1 waste.go:57] Expanding Node Group nodes-applications-1b.k8s.dev.xxx.xxx would waste 52.50% CPU, 88.67% Memory, 70.59% Blended
I0506 07:50:30.800622       1 waste.go:57] Expanding Node Group nodes-applications-1c.k8s.dev.xxx.xxx would waste 52.50% CPU, 88.67% Memory, 70.59% Blended
```

kops instance group config:
```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-02T07:59:44Z
  labels:
    kops.k8s.io/cluster: k8s.dev.xxx.xxx
  name: nodes-applications-1a
spec:
  cloudLabels:
    k8s-minion-manager: use-spot
    k8s-minion-manager/not-terminate: "true"
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/node-template/label/ig: nodes
    kubernetes.io/cluster/k8s.dev.xxx.xxx: "true"
  image: 383156758163/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.2xlarge
  maxPrice: "0.5"
  maxSize: 4
  minSize: 0
  nodeLabels:
    dedicated: application-dynamic
    kops.k8s.io/instancegroup: nodes-applications
    node-role.kubernetes.io/spot-worker: "true"
  role: Node
  subnets:
  - ap-southeast-1a
  taints:
  - dedicated=application-dynamic:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-02T08:00:05Z
  labels:
    kops.k8s.io/cluster: k8s.dev.xxx.xxx
  name: nodes-applications-1b
spec:
  cloudLabels:
    k8s-minion-manager: use-spot
    k8s-minion-manager/not-terminate: "true"
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/node-template/label/ig: nodes
    kubernetes.io/cluster/k8s.dev.xxx.xxx: "true"
  image: 383156758163/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.2xlarge
  maxPrice: "0.5"
  maxSize: 4
  minSize: 0
  nodeLabels:
    dedicated: application-dynamic
    kops.k8s.io/instancegroup: nodes-applications
    node-role.kubernetes.io/spot-worker: "true"
  role: Node
  subnets:
  - ap-southeast-1b
  taints:
  - dedicated=application-dynamic:NoSchedule

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-02T08:00:21Z
  labels:
    kops.k8s.io/cluster: k8s.dev.xxx.xxx
  name: nodes-applications-1c
spec:
  cloudLabels:
    k8s-minion-manager: use-spot
    k8s-minion-manager/not-terminate: "true"
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/node-template/label/ig: nodes
    kubernetes.io/cluster/k8s.dev.xxx.xxx: "true"
  image: 383156758163/k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: m4.2xlarge
  maxPrice: "0.5"
  maxSize: 4
  minSize: 0
  nodeLabels:
    dedicated: application-dynamic
    kops.k8s.io/instancegroup: nodes-applications
    node-role.kubernetes.io/spot-worker: "true"
  role: Node
  subnets:
  - ap-southeast-1c
  taints:
  - dedicated=application-dynamic:NoSchedule
```
