### ISSUE TITLE
Undocumented minimum resource requests for VPA?

### ISSUE THREAD

**Issue by fiws** [kubernetes/autoscaler#2004]
I have a simple VPA on GKE that looks like this:

```
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  namespace: kube-system
  name: heapster-vpa
spec:
  targetRef:
    apiVersion: "extensions/v1beta1"
    kind: Deployment
    name: heapster-v1.6.1
  updatePolicy:
    updateMode: "Initial"
```

It results in scaled down cpu requirements for heapster but the Memory Requests jump to "87381333" for every container. Resulting in unneeded high memory requests for this pod.
I noticed the same behavior for other VPAs (eg. one for kube-dns).

Is there an undocumented minimum resource request and if yes, can it be changed?
