### ISSUE TITLE
Allow lower values of MinAllowed

### ISSUE THREAD

**Issue by bobo333** [kubernetes/autoscaler#2058]
We run a large number of mostly idle deployments. I'd like to be able to set the `MinAllowed` to lower than the default of `10m` for cpu. I was following the instructions from this issue: https://github.com/kubernetes/autoscaler/issues/1775 
It seems to respect the `minAllowed` values if they're higher than `10m`, but when I set them lower (tried both `0m` and `1m`), the lower bound remained at `10m`. When I set it to `50m` the `lowerBound` for `cpu` did change to `50m`, but at values below `10m` the `lowerBound` remained at `10m`

The yaml manifests I was using were
Not respected:
```
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
  namespace: my-vpa
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 1m
        memory: 1Mi
  targetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: my-dep
  updatePolicy:
    updateMode: "Off"
```

Respected:
```
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
  namespace: my-vpa
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 50Mi
  targetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: my-dep
  updatePolicy:
    updateMode: "Off"
```

I'm running `v0.5.0` of VPA, with `updateMode: off`
