### ISSUE TITLE
AKS Cluster downscaling issue

### ISSUE THREAD

**Issue by Boriszn** [kubernetes/autoscaler#2153]
Hi Team, 

Could someone please help or suggest something. We are running autoscaler in the AKS. 
When cluster is downscaling it could left 2 (or even 1) nodes for short period (for 3 / 5 min) _however min nodes count was configured to 3 node._

Is it expected behavior ? Or my configuration is wrong somehow ?

Many Thanks for help, in advance

Kubernetes version `1.13.5` 
Autoscaler configuration:
````
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
      - image: gcr.io/google-containers/cluster-autoscaler:v1.13.0
        imagePullPolicy: Always
        name: cluster-autoscaler
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        command:
        - ./cluster-autoscaler
        - --v=3
        - --logtostderr=true
        - --cloud-provider=azure
        - --skip-nodes-with-local-storage=false
        - --nodes=3:100:livepool
````
