### ISSUE TITLE
Make cluster-autoscaler log info logs to stdout and errors to stderr

### ISSUE THREAD

**Issue by marekaf** [kubernetes/autoscaler#2333]
Hi,
I'm using cluster-autoscaler with EKS with these args

```
    spec:
      containers:
      - command:
        - ./cluster-autoscaler
        - --cloud-provider=aws
        - --namespace=infra
        - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/production
        - --logtostderr=true
        - --stderrthreshold=ERROR
        - --v=4
```

I want to to log everything with severity < ERROR to stdout, >= ERROR to stderr, as is common practice with most containerized workloads.

By default cluster-autoscaler is logging everything on stderr (even warning, info, debug logs) using the flag `--logtostderr=true`. 

How do I set it up for the desired logging? Is it documented anywhere? Is is using the google/glog library? 

Thanks!
