### ISSUE TITLE
EKS 1.14 oidc provider for service account doesn't work

### ISSUE THREAD

**Issue by marcincuber** [kubernetes/autoscaler#2335]
Hi,

I was trying to make use of the new oidc provider and IAM roles for service accounts. However, I am getting access denied issues.
```
Failed to create AWS Manager: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::00000000:assumed-role/ceng-eks-test-worker-node/30e721c9-ceng-eks-test-worker-node is not authorized to perform: autoscaling:DescribeTags
```

My service account:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::00000000:role/ceng-eks-test-cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
```

My role is definitely configured correctly. It is simply cluster-autoscaler deployment not using the iam role attached to the service account.

I am using `gcr.io/google-containers/cluster-autoscaler:v1.14.4`.

Additionally, credentials are there:
```
kubectl exec -n kube-system cluster-autoscaler-6d6d95cdf9-xd7q5 env | grep AWS                        [9:51:28]
AWS_ROLE_ARN=arn:aws:iam::00000000:role/ceng-eks-test-cluster-autoscaler
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_REGION=eu-west-1
```
Can someone advise?
