### ISSUE TITLE
Cannot get resource "cronjobs/scale" in API group "batch" 

### ISSUE THREAD

**Issue by estahn** [kubernetes/autoscaler#2400]
**Error:**

Cannot get target selector from VPA's targetRef. Reason: Unhandled targetRef batch/v1beta1 / CronJob / foobar, last error cronjobs.batch "foobar" is forbidden: User "system:serviceaccount:kube-system:vpa-recommender" cannot get resource "cronjobs/scale" in API group "batch" in the namespace "foo"

Running 0.6.1

**Workaround:**

Added `cronjobs/scale` to cluster role.

**Comment by bskiba** [comment]
Proper support for CronJobs is added in #2195
This will be released with the next minor release (0.7) which I am still working on.
If there is high demand, we could cherry pick into earlier releases.

**Comment by bskiba** [comment]
We can actually also consider adding your workaround to 0.6 branch which will be easier.

**Comment by estahn** [comment]
I didn’t realised this wasn’t released, so my bad :)

I’m not fussed, whatever works for you. Obviously I want to have it sooner rather than later :)

**Comment by estahn** [comment]
@bskiba Is there anything you need help with?

**Comment by alecbrick** [comment]
I'm also interested in VPA for cronjobs. Do you have an estimate for when this will be released? Thanks!

**Comment by bskiba** [comment]
Hi all, thank you for your patience! 
I am planning to release the CronJob support in the next two weeks. Please pester me if I don't provide updates by that time here.

**Comment by bskiba** [comment]
I've just released VPA 0.7.0 with support for cronjobs. (https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.7.0)
I apologize sincerely for the delay!

Please let me know if you still encounter issues with CronJobs.

**Comment by caslurjf** [comment]
> I've just released VPA 0.7.0 with support for cronjobs. (https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.7.0)
> I apologize sincerely for the delay!
> 
> Please let me know if you still encounter issues with CronJobs.

I'm getting "ConfigUnsupported" error message. My VPA setting is:

```
---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: my-cronjob-name-vpa
spec:
  targetRef:
    apiVersion: "batch/v1beta1"
    kind: CronJob
    name: my-cronjob-name
  updatePolicy:
    updateMode: "Off"  
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 1
          memory: "1Gi"
        maxAllowed:
          cpu: 2
          memory: "3Gi"
        controlledResources: ["cpu", "memory"]
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob-name
  namespace: <KUBE_NAMESPACE>
...
```

Some idea in what I'm doing wrong ?
