### ISSUE TITLE
Provide more information on what blocks CA from terminating a node

### ISSUE THREAD

**Issue by gtseres** [kubernetes/autoscaler#2411]
Currently, cluster autoscaler (CA) is providing a configmap object (`cluster-autoscaler-status`) so that the operator can check to see if there are any candidate nodes to be terminated. This is some very useful information, but unfortunately it does not provide the reasoning behind a node not being considered a candidate.

Of course, one can check the [various cases](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node) that could block CA from evicting pods from a node, and then check every pod in the node against those requirements. Given that CA already does this work, it would be really useful if it could expose it to the user in an actionable manner. Example:

```
nodes:
  - nodeA:
      candidate: false
      blocking-pods:
       - podA:
           reason: "local-storage"
       - podB:
           reason: "no-node-satisfying-requests"
  - nodeB:
      candidate: true
  - nodeC:
      candidate: false
      blocking-pods:
        - podC:
            reason: "kube-system-pod"
        - podD:
            reason: "safe-to-evict-false"
```

This is just an example of the way CA could provide actionable information to the user, making it way easier for modifications to unblock the situation.
