### ISSUE TITLE
Failed to create magnum manager

### ISSUE THREAD

**Issue by jenningsloy318** [kubernetes/autoscaler#2430]
Hi,

I have deployed cluster-autoscaler into our kubernetes cluster which is being deployed ontop of openstack, the config:
```
        - name: cluster-autoscaler
          image: registry.aliyuncs.com/google_containers/cluster-autoscaler:v1.16.1
          imagePullPolicy: IfNotPresent
          command:
            - ./cluster-autoscaler
            - --alsologtostderr
            - --cluster-name="cluster01"
            - --cloud-config=/config/cloud-config
            - --cloud-provider=magnum
            - --v=10
            - --nodes=1:10:DefaultNodeGroup
```

but seems it can't connect to our openstack, but without detailed error message
```
I1008 07:01:38.227762       1 magnum_manager_heat.go:116] Using user-agent cluster/cluster01 cluster-autoscaler/1.16.1 gophercloud/2.0.0
F1008 07:01:38.326536       1 magnum_cloud_provider.go:162] Failed to create magnum manager: could not create container-infra client: No suitable endpoint could be found in the service catalog.
```

but with same cloud config I can deploy [cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack), and works well, we can create lb/pool/listener ...

not sure why magnum can't connect to openstack.
