### ISSUE TITLE
Autoscaler not respecting the taint tag in AWS

### ISSUE THREAD

**Issue by dcherniv** [kubernetes/autoscaler#2434]
It seems that cluster autoscaler is ignoring the taints in some cases and tries to spin up a node pool that is tainted to schedule a pod with no toleration for the taint.

Example pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  labels:
    app: dev-pay-stub-services
    pod-template-hash: 64f54bbcd
  name: dev-pay-stub-services-64f54bbcd-d5z2r
  namespace: dev
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: dev-pay-stub-services-64f54bbcd
spec:
  containers:
  - env:
REDACTED
    image: REDACTED/pay-stub-services:0.9.1-5-g3d1358f
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 30
    name: pay-stub-services
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 30
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 1500m
        memory: 3Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
REDACTED
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: newrelic.ini
        path: newrelic.ini
      name: dev-pay-stub-services
    name: newrelic-config
  - name: default-token-nj7fb
    secret:
      defaultMode: 420
      secretName: default-token-nj7fb
```
autoscaler logs from the time. Strangely it rememberd that gpu-4 had a taint. But exact gpu-0 from the another ASG in a different AZ it happily spun up.
```

Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048387       1 utils.go:237] Pod dev-pay-stub-services-64f54bbcd-27xzb can't be scheduled on nonproduction01-spot-gpu-4, predicate failed: PodToleratesNodeTaints predicate mismatch, reason: node(s) had taints that the pod didn't tolerate
-- | --

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048459       1 utils.go:227] Pod dev-pay-stub-services-64f54bbcd-htm6g can't be scheduled on nonproduction01-spot-gpu-4. Used cached predicate check results

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048470       1 scale_up.go:411] No pod can fit to nonproduction01-spot-gpu-4

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048574       1 scale_up.go:338] Skipping node group nonproduction01-spot-gpu-6 - max size reached

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048589       1 utils.go:237] Pod dev-pay-stub-services-64f54bbcd-27xzb can't be scheduled on nonproduction01-spot-gpu-7, predicate failed: PodToleratesNodeTaints predicate mismatch, reason: node(s) had taints that the pod didn't tolerate

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048661       1 utils.go:227] Pod dev-pay-stub-services-64f54bbcd-htm6g can't be scheduled on nonproduction01-spot-gpu-7. Used cached predicate check results

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048674       1 scale_up.go:411] No pod can fit to nonproduction01-spot-gpu-7

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048679       1 scale_up.go:423] Best option to resize: nonproduction01-spot-gpu-0

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048683       1 scale_up.go:427] Estimated 1 nodes needed in nonproduction01-spot-gpu-0

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048922       1 scale_up.go:521] Splitting scale-up between 4 similar node groups: {nonproduction01-spot-gpu-0, nonproduction01-spot-gpu-1, nonproduction01-spot-gpu-2, nonproduction01-spot-gpu-3}

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048933       1 scale_up.go:529] Final scale-up plan: [{nonproduction01-spot-gpu-0 0->1 (max: 1)}]

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048945       1 scale_up.go:694] Scale-up: setting group nonproduction01-spot-gpu-0 size to 1

  | Oct 9, 2019 @ 00:30:28.048 | I1009 04:30:28.048971       1 auto_scaling_groups.go:211] Setting asg nonproduction01-spot-gpu-0 size to 1
```
here's the setting for the node pool in aws.
![image](https://user-images.githubusercontent.com/19437418/66500356-5ba0d280-ea8f-11e9-93e4-ea438d454a3f.png)

So a couple of questions. Does autoscaler only finds out about the taints when it tries to spin up an instance from the nodepool?
Judging by the logs it appears there's some caching of the taints/labels going on. How long will it cache them for? 
Why did it spin up an instance from a tainted node pool?
How can i make sure that pods that don't tolerate any taints wont trigger a scaling action?
