### ISSUE TITLE
can not work with vertical-pod-autoscaler

### ISSUE THREAD

**Issue by hongli-my** [kubernetes/autoscaler#2467]
in this case,  can not get pod resource recommendation
step1.    create deployment, and pod label:  `app1:  xxx`
step2.   after some minutes, create vpa,   and this vpa's label : `app1: xxx` , so pod can matches vpa
in that case above,  recommender can not calculate  pod resource.
because  https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L167

in step 1: `cluster.findOrCreateAggregateContainerState(containerID)`  can not find vpa
but `pod.Containers` have been initialization.   after create vpa,   [code1](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L167) will not call.

when pod label change ,[code2](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L128) will call,  recommender will work well.

maybe  need check `cluster.findOrCreateAggregateContainerState(containerID)` result before initialize `pod.Containers`

**Comment by bskiba** [comment]
Which VPA version and API are we talking about?
Would you mind sharing your VPA object and deployment yaml?

**Comment by hongli-my** [comment]
I think it doesn't matter to the config.
vpa:  latest
```
apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: my-rec-vwa-update
spec:
  selector:
    matchLabels:
      vpa1: app1
  updatePolicy:
    updateMode: "Update"

```

deployment.yml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-rec-deployment
  labels:
    purpose: try-recommend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        purpose: try-recommend
        vpa1: app1
    spec:
      containers:
      - name: my-rec-container
        image: polinux/stress
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "sleep 10000" ]
        resources:
          limits:
            memory: "50Mi"
            cpu: "2"
```
