### ISSUE TITLE
Not triggering gpu scale up on AWS/EKS 

### ISSUE THREAD

**Issue by ujjwalsfix** [kubernetes/autoscaler#2506]
Seeing the following error - 

```event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"gpu3-5vrjp", UID:"cf6affef-fc40-11e9-ab2d-12c6abee5b20", APIVersion:"v1", ResourceVersion:"180529", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 6 Insufficient nvidia.com/gpu```

```
apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-test
spec:
  template:
    spec:
      containers:
      - name: gpu-test
        image: nvidia/cuda:9.2-devel
        resources:
          limits:
            nvidia.com/gpu: 1          
        command: ["echo", "start"]
      restartPolicy: Never
  backoffLimit: 4
```

Is there a nodeSelector or label on the ASG that I am missing here?
