### ISSUE TITLE
CA for aws cannot scale asg from zero node

### ISSUE THREAD

**Issue by xinxingliu90** [kubernetes/autoscaler#2642]
We use cluster autoscaler version of 1.13 on aws.  The issue is we are not able to scale asg from zero. The configs are:

1. In node group creation script, we set the node label to be : some_label=true
2. We tag the asg as:
 Key: k8s.io/cluster-autoscaler/node-template/label/some_label
Value: true

It used to work yesterday after this change has been made, the asgs were able to scale from zero. But today it does not work anymore. Any ideas?

**Comment by xinxingliu90** [comment]
@Jeffwan

**Comment by xinxingliu90** [comment]
@Jeffwan

**Comment by Jeffwan** [comment]
@xinxingliu90  I would suggest you to give more CA logs and we can diagnose. Here's a configuration I am using to scale from 0. 

Deployment.
```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: k8s.amazonaws.com/accelerator
                 operator: In
                 values:
                 - nvidia-tesla-v100
                 - nvidia-tesla-k80
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU

```

You have to label node `k8s.amazonaws.com/accelerator:nvidia-tesla-v100` and also tag ASG

```
  - name: gpu-v100
    instanceType: p3.2xlarge
    availabilityZones: ["us-west-2b"]
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    #volumeSize: 100
    ssh:
      allow: true
      publicKeyPath: '~/.ssh/id_rsa.pub'
    labels:
      k8s.amazonaws.com/accelerator: nvidia-tesla-v100  #kubernete node label
    tags:
      k8s.io/cluster-autoscaler/node-template/label/k8s.amazonaws.com/accelerator: nvidia-tesla-v100  # aws ASG

```
This is an eksctl node group example, if you use other tools, please apply equivalent changes.
