### ISSUE TITLE
GKE: Cluster autoscaler does not scale down if gpus are used

### ISSUE THREAD

**Issue by martinVyoo** [kubernetes/autoscaler#2689]
I have a Pod running on a node pool that is autoscaled **min**:0 **max**:1, another node on another pool is available which has less resources, but enough to run the pod.

Some points:

- The node pool will scale down if the pod is not running on it, so it is not a problem of kube-system pods that are preventing the scale down
- I have made sure the pod can in fact be evicted, according to the [faq](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node) (you can see the pod definition below)
- the node in the node pool I am expecting to scale down is under 50% utilization
- Another node with sufficient resources is available to run the pod
- I am running on GKE so I cannot see the logs, the only thing I can rely on is the status configmap
- I have two other separate nodes to host kube-system pods
- My pod is using only 1 gpu, while the node I want to scale down has 4 gpus available

Here is the configuration of my pod, with a pdb as well, just in case
I also have an hpa configured, but I do not think its relevant

**Kubernetes Version**: 1.14.9-gke.2

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myPod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myPod
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: myPod
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: cloud.google.com/preemptible
                    operator: In
                    values:
                      - "true"
      containers:
        - name: ****
          image: *****
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "5"
              memory: "6G"
            requests:
              cpu: "2"
              memory: "500M"
              nvidia.com/gpu: "1"
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: ****

      restartPolicy: Always
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: myPod-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: myPod

```

This is the current status for the autoscaler:
```
Cluster-autoscaler status at 2019-12-24 16:54:40.000217268 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=4 unready=0 notStarted=0 longNotStarted=0 registered=4 longUnregistered=0)
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-23 18:12:06.416746875 +0000 UTC m=+28.383958861
      ScaleUp:     NoActivity (ready=4 registered=4)
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-23 18:12:06.416746875 +0000 UTC m=+28.383958861
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-24 15:07:12.710179354 +0000 UTC m=+75334.677391339

    NodeGroups:
      Name:        https://content.googleapis.com/compute/v1/projects/****/zones/us-east1-c/instanceGroups/scaleDown-Pool
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=0, maxSize=1))
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-23 18:12:06.416746875 +0000 UTC m=+28.383958861
      ScaleUp:     NoActivity (ready=1 cloudProviderTarget=1)
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-23 18:12:06.416746875 +0000 UTC m=+28.383958861
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-24 15:07:12.710179354 +0000 UTC m=+75334.677391339

      Name:        https://content.googleapis.com/compute/v1/projects/*****/zones/us-east1-c/instanceGroups/static-pool
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=1, maxSize=1))
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-24 15:14:22.429755456 +0000 UTC m=+75764.396967443
      ScaleUp:     NoActivity (ready=1 cloudProviderTarget=1)
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-24 15:14:22.429755456 +0000 UTC m=+75764.396967443
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-12-24 16:54:39.780771153 +0000 UTC m=+81781.747983168
                   LastTransitionTime: 2019-12-23 20:53:44.231291996 +0000 UTC m=+9726.198504001
```

Current utilization of the pod:
```
NAME                                   CPU(cores)   MEMORY(bytes)   
myPod-6cdc99fcfb-c89cb                  1m           69Mi  
```
Current utilization of the nodes:
```
NAME                                              CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
gke-scaleDown-c2991066-cw7v                       54m          0%     1248Mi          2%        
gke-static-pool-e33d0e69-1837                     49m          0%     1097Mi          9% 
```
Current Allocation on the nodes:
```
scaleDown
Resource                   Requests        Limits
  --------                   --------        ------
  cpu                        2400m (15%)     6050m (38%)
  memory                     720200960 (1%)  6534773760 (11%)
  ephemeral-storage          0 (0%)          0 (0%)
  attachable-volumes-gce-pd  0               0
  nvidia.com/gpu             1               1

static-pool
Resource                   Requests    Limits
  --------                   --------    ------
  cpu                        400m (6%)   1050m (17%)
  memory                     210Mi (1%)  510Mi (4%)
  ephemeral-storage          0 (0%)      0 (0%)
  attachable-volumes-gce-pd  0           0
  nvidia.com/gpu             0           0
```
I am expecting the node pool "scaleDown" to be scaled down to 0 nodes and the pod "myPod" to be moved to the "static-pool", which has a node available to host the pod
