### ISSUE TITLE
VPA - Document the current recommendation algorithm

### ISSUE THREAD

**Issue by bskiba** [kubernetes/autoscaler#2747]
Document 
* how recommendations are calculated out of raw samples for CPU and Memory.
* when it is reasonable to expect a stable recommendation for a new workload

Please note that VPA recommendation algorithm is not part of the API and is subject to change without notice

**Comment by hochuenw-dd** [comment]
@bskiba any updates on this?

**Comment by yashbhutwala** [comment]
This would be awesome!!  How can I help?

**Comment by yashbhutwala** [comment]
I've been digging around the code for a bit, this is what I understand so far, please correct me where I'm wrong 😃 

To answer this:

> how recommendations are calculated out of raw samples for CPU and Memory.

recommendations are calculated using [decaying histogram](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/util/decaying_histogram.go#L43) of weighted samples from the metrics server, where the newer samples are assigned higher weights;  older samples are decaying and hence affect less and less w.r.t. to the recommendations.  [CPU](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go#L174) is calculated using the [90th percentile of all cpu samples](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L102), and [memory](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go#L175) is calculated using the [90th percentile](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L106) [**peak**](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go#L96) over the 8 day window]. 

> when it is reasonable to expect a stable recommendation for a new workload

[8 days](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/aggregations_config.go#L28) of history is used for recommendation (1 memory usage sample [per day](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/aggregations_config.go#L35)).  Prometheus can be used a history provider in this calculation.  By default, vpa is collecting data about all controllers, so when new vpa objects are created, they are already providing stable recommendations (unless you specify `memory-save=true`).  All active vpa recommendations are checkpointed.


...I'm not sure if it's possible to get a "stable" recommendation before 8 days...

**Comment by djjayeeta** [comment]
@yashbhutwala Great Summary!! 

I am getting a huge upper bound for my recommendation at the startup and trying to understand the behavior. 

Below is the VPA object. 

`Name:         xxx-vpa
Namespace:   xxxx
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscaler","metadata":{"annotations":{},"name":"kube-apiserver-vpa","namesp...
API Version:  autoscaling.k8s.io/v1
Kind:         VerticalPodAutoscaler
Metadata:
  Creation Timestamp:  2020-04-30T20:39:43Z
  Generation:          165
  Resource Version:    1683082
  Self Link:           xxxx
  UID:                <some_number>
Spec:
  Resource Policy:
    Container Policies:
      Container Name:  c_name
      Controlled Resources:
        cpu
        memory
      Min Allowed:
        Cpu:           100m
        Memory:        400Mi
      Container Name:  c_name2
      Mode:            Off
  Target Ref:
    API Version:  apps/v1beta2
    Kind:         StatefulSet
    Name:         name
  Update Policy:
    Update Mode:  Auto
Status:
  Conditions:
    Last Transition Time:  2020-04-30T20:40:07Z
    Status:                True
    Type:                  RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  c_name
      Lower Bound:
        Cpu:     100m
        Memory:  400Mi
      Target:
        Cpu:     125m
        Memory:  903203073
      Uncapped Target:
        Cpu:     125m
        Memory:  903203073
      Upper Bound:
        Cpu:     2967m
        Memory:  16855113438
Events:          <none>
`

I don't want to set an upper limit in the VPA object. I don't have checkpoints as history is loaded from prometheus server. But I noticed this huge upperbound (numbers may be slightly different ) irrespective of whether I load from check point or prometheus. Can you tell why does the algorithm give such a high upper bound?

Also, there are no OOM events in VPA recommender logs.

I did the same experiment without prometheus server and got similar numbers. I checked the checkpoint of VPA
`"status": {
			"cpuHistogram": {
				"bucketWeights": {
					"1": 10000,
					"10": 728,
					"11": 1088,
					"12": 121,
					"2": 2891,
					"3": 1009,
					"4": 686,
					"5": 240,
					"8": 41,
					"9": 5436
				},
				"referenceTimestamp": "2020-05-01T00:00:00Z",
				"totalWeight": 51.24105164098685
			},
			"firstSampleStart": "2020-04-30T20:39:30Z",
			"lastSampleStart": "2020-04-30T22:11:02Z",
			"lastUpdateTime": null,
			"memoryHistogram": {
				"referenceTimestamp": "2020-05-02T00:00:00Z"
			},
			"totalSamplesCount": 552,
			"version": "v3"
		}` 

The surprising case is there is no memory histogram. Is this because it will only appear after 24 hr? 

I deleted the VPA object, checkpoint and then restarted the VPA object but still getting huge upper bounds after 2 hours of startup. How is it recommending memory without any histogram?

Can you please answer this?

**Comment by yashbhutwala** [comment]
@djjayeeta good questions!!  I'm not an expert here, but as far as I understand it, the most important value for you to look at is **Target**.  This is the recommendation given for you to set the **_requests_** to.  **_There is no limit recommendation given by VPA currently_**.  

**Lower and Upper bound** are meant to only be used by the **VPA updater** to allow pod to be running if the requests are in that range;  and not evict them.  For upper bound, I suspect this is set by default to node's capacity (as in your case this is 16Gi). just fyi, Uncapped Target gives the recommendation before applying constraints specified in the VPA spec, such as min or max.

With this in mind, in your case, the target of `125m` cpu and `0.85Gi` (903203073 bytes) mem seems reasonable.

> The surprising case is there is no memory histogram. Is this because it will only appear after 24 hr?
Yes, it samples the peak per day afaik.

**Comment by bskiba** [comment]
@yashbhutwala, thanks for taking time to answer here, your answer is very precise. 👍 
If you would like, could you add this answer to the [FAQ](/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md)? I think it would prove very useful to other users

**Comment by avmohan** [comment]
@djjayeeta high upper bound at startup would be due to confidence factor scaling. With more data, it will go closer towards the 95th percentile. 
https://github.com/kubernetes/autoscaler/blob/87eae1d207742bef168bf40e842b5a78b0600a26/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L129
https://github.com/kubernetes/autoscaler/blob/87eae1d207742bef168bf40e842b5a78b0600a26/vertical-pod-autoscaler/pkg/recommender/logic/estimator.go#L114

**Comment by shekhar-rajak** [comment]
Hi, Can I work on this? I think there is enough information added in the comment: https://github.com/kubernetes/autoscaler/issues/2747#issuecomment-616037197 and https://github.com/kubernetes/autoscaler/issues/2747#issuecomment-622252843 . 

I can rephrase it and add in the FAQ: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md

**Comment by Duske** [comment]
Hi @yashbhutwala, is it still the case that the VPA does not recommend the resource limits and only the requests?

**Comment by yashbhutwala** [comment]
@Duske yes.

**Comment by gosoon** [comment]
I do not find relevant instructions of Recommender Components algorithm in the project. It is still a little complicated to learn from the code. Is there no documentation of the algorithm in the community？

eg:
initialize histogram algorithm and how is it designed.
calculate the recommended value algorithm.

**Comment by ashvinsharma** [comment]
I agree. I would like to know what heuristics are applied in the algorithm to ensure that correct target values are sent to different services with different usage patterns.

**Comment by alvaroaleman** [comment]
/reopen

I don't think this is solved and it is very hard to find information about this

**Comment by ManuelMueller1st** [comment]
I am wondering why VP recommender uses targetMemoryPeaksPercentile := 0.9.
Shouldn't it use the maximum observed memory usage to avoid OOM kill?

https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L108

**Comment by pierreozoux** [comment]
@ManuelMueller1st it is a request not a limit.

**Comment by ManuelMueller1st** [comment]
> @ManuelMueller1st it is a request not a limit.

We set limits and requests to the same value.

**Comment by mwarkentin** [comment]
@pierreozoux many people (including @thockin as a general rule, with possible caveats of course) recommend setting memory requests == limits as memory is an uncompressable resource and you may over-allocate memory on a host resulting in random OOMs anyways.

https://home.robusta.dev/blog/kubernetes-memory-limit

![image](https://github.com/user-attachments/assets/08753577-d2ad-4ff1-abaf-9ac534d0680a)

**Comment by mwarkentin** [comment]
I also think a high level overview of how the algorithm works would be super helpful for making people comfortable with using VPA particularly for memory recommendations.

**Comment by iamzili** [comment]
@mwarkentin, if you want to maintain a 1:1 ratio between memory requests and limits, you can achieve this by setting both memory requests and limits to the same values when you initially deploy the pods first:

The `TargetBound` contains the recommended optimal amount of resources, which is calculated by the Recommender. It is used to set resource requests. The base for `TargetBound` is the 90th percentile, with an additional safety margin (default 15%, configurable via the `--recommendation-margin-fraction` flag). The Recommender doesn't compute the limits ... instead, the limits are set based on the ratio we initially define when we deploy the pods first with resource requests and limits. For example, when you deploy a Deployment with 2 pods, and you set both memory requests and limits to 100MiB, if the memory request is updated to 200MiB (because of new recommended value), the limit is automatically adjusted to 200MiB as well.

Additionally, it's crucial to note that the `TargetBound`, `LowerBound`, and `UpperBound` achieve maximum accuracy when there is 8 days of historical data. Any data older than that is discarded from the state btw.

**Comment by sftim** [comment]
BTW, it would be great to add VPA to the [official documentation](https://k8s.io/docs/)

**Comment by mwarkentin** [comment]
@iamzili just saw this, nice work on that write up. Does it seem reasonable to link directly from here for people to discover more easily?

Alternatively incorporating this or something similar in the repo docs themselves would be super.

**Comment by raywainman** [comment]
@iamzili your writeup is great!!

**Comment by iamzili** [comment]
@jpawelczak Sure! I'm open to this. Let's connect on the Kubernetes Slack channel - could you please DM me there? it should be fairly easy to find me based on my last name.

**Comment by jpawelczak** [comment]
@iamzili , that is great! I joined k8s slack and DMed you

**Comment by tspearconquest** [comment]
Does VPA set limits at this time? I see earlier in this thread (some years ago) that it did not back then but I'm seeing odd behavior for a resource I have managed by VPA.

My VPA as you can see below has `maxAllowed.memory` configured to 1536Mi (1.5Gi):
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: source-controller-platform-admin
  namespace: flux-system
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      maxAllowed:
        cpu: 1000m
        memory: 1536Mi
      minAllowed:
        cpu: 50m
        memory: 768Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: source-controller-platform-admin
  updatePolicy:
    minReplicas: 1
    updateMode: Auto
```

Namespace limit range allows up to 2560Mi per pod and per container (1 container per pod) and specifies defaults less than that to limit any pods not managed by VPA:
```
apiVersion: v1
kind: LimitRange
metadata:
  name: flux-system
  namespace: flux-system
spec:
  limits:
  - default:
      cpu: "1"
      ephemeral-storage: 1280Mi
      memory: 1280Mi
    defaultRequest:
      cpu: 500m
      ephemeral-storage: 1280Mi
      memory: 1280Mi
    max:
      cpu: "1"
      ephemeral-storage: 2560Mi
      memory: 2560Mi
    type: Container
  - max:
      cpu: "1"
      ephemeral-storage: 2560Mi
      memory: 2560Mi
    type: Pod
```

Namespace resource quota allows up to 25Gi total memory usage in the namespace:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: limit-total-namespace-cpu-memory-storage-usage
  namespace: flux-system
spec:
  hard:
    limits.ephemeral-storage: 25Gi
    limits.memory: 25Gi
    requests.cpu: "20"
    requests.ephemeral-storage: 25Gi
    requests.memory: 25Gi
```

My deployment and replicaset have memory defined as:
```
resources:
  limits:
    memory: 1536Mi
  requests:
    cpu: 50m
    memory: 64Mi
```

Yet, when the pod is created by the replicaset, I get this error in the replicaset events (it's a singleton service but there are other singleton pods in the same namespace using some of the memory):
```
message: 'pods "source-controller-platform-admin-74dfbb9c79-7k7w8" is forbidden:
  exceeded quota: limit-total-namespace-cpu-memory-storage-usage, requested: limits.memory=18Gi,
  used: limits.memory=25440Mi, limited: limits.memory=25Gi'
```

Namespace memory usage currently without this pod:
```
limits.memory: 23904Mi/25Gi
```

This is from another pod in the same namespace targeted by a different VPA also got 18Gi limit applied by VPA recommendation and took up a large percentage of the available limits.memory quota.

My VPA doesn't seem to be recommending limits of 18Gi for this pod as seen below:
```
status:
  conditions:
  - lastTransitionTime: "2025-08-03T15:06:50Z"
    status: "True"
    type: RecommendationProvided
  recommendation:
    containerRecommendations:
    - containerName: manager
      lowerBound:
        cpu: 50m
        memory: 768Mi
      target:
        cpu: 63m
        memory: 768Mi
      uncappedTarget:
        cpu: 63m
        memory: "764046746"
      upperBound:
        cpu: 628m
        memory: 1536Mi
```

And nothing I have configured in the namespace should be configuring the limit that high (18Gi), as seen with the limit range resource defined above.

However, if I remove the VPA, the pod gets created with the value from the deployment and all is well; so it clearly seems to be the VPA mutating the pod at admission causing it to get a limit value set to 18Gi which exceeds the namespace resource quota.

So again I just want to confirm if VPA now supports setting limits and has any issues with this?

This is the AKS managed supported installation of VPA. The recommender pod runs this image:

`mcr.microsoft.com/oss/v2/kubernetes/autoscaler/vpa-recommender:v1.2.1-1`
