### ISSUE TITLE
AWS node group on EKS cluster does not autoscale from 0.

### ISSUE THREAD

**Issue by vickyvikas7988** [kubernetes/autoscaler#2823]
CA is not scaling when my ASG desired count is 0 and when I increase the count to 1 it scales. Is it due to the  --expander=least-waste?

```
Image:      k8s.gcr.io/cluster-autoscaler:v1.13.1
Command:
      ./cluster-autoscaler
      --cloud-provider=aws
      --namespace=kube-system
      --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/production-*****
      --expander=least-waste
      --logtostderr=true
      --stderrthreshold=info
```

    Image ID:      docker-pullable://k8s.gcr.io/cluster-autoscaler@sha256:7ff5a60304b344f2f29c804c7253632bbc818794f6932236a56db107a6a8f5af
Start Time:     Wed, 05 Feb 2020 09:23:37 +0100

**Comment by daganida88** [comment]
Show the cluster autoscaler logs, only that way you will know what the problem is.
It can be permissions issues, or missing tags on your ASG:

k8s.io/cluster-autoscaler/enabled: true

**Comment by BEvgeniyS** [comment]
I'm having same issue, it doesn't scale up from 0. If there's already at least one instance, it will launch another one as required. (so permissions are fine).

Command & arguments:
```  cluster-autoscaler:
...
    Command:
      ./cluster-autoscaler
      --v=4
      --stderrthreshold=info
      --cloud-provider=aws
      --skip-nodes-with-local-storage=false
      --expander=least-waste
      --balance-similar-node-groups=true
      --scale-down-utilization-threshold=0.75
      --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/dev-eks
```


relevant log:
```I0225 02:41:32.948497       1 static_autoscaler.go:147] Starting main loop
I0225 02:41:32.951369       1 utils.go:626] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0225 02:41:32.952098       1 utils.go:254] Pod m3db-cluster-rep2-0 can't be scheduled on dev-eks-himem-nodes-c-NodeGroup-1D1A7D14IIJ9P, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't match node selector
I0225 02:41:32.952120       1 scale_up.go:411] No pod can fit to dev-eks-himem-nodes-c-NodeGroup-1D1A7D14IIJ9P
I0225 02:41:32.952539       1 scale_up.go:416] No expansion options
```

It says `No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop`, but my pod actually has the affinity:

```
apiVersion: v1
kind: Pod
...
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - us-west-2c
          - key: himem
            operator: In
            values:
            - "true"
```


My autoscaling group also has `failure-domain.beta.kubernetes.io/zone` tag.



I think it doesn't know which autoscaling group to expand if there's 0 instances in it. If it has at least one, then cluster-autoscaler can make a good guess and expand the ASG that has that existing instance. Otherwise, it seems like it can't map affinity rules to ASG

Please let me know if there's a way out of this problem. (maybe assigning `himem=true` tag to autoscaling group or anything like that?)
