### ISSUE TITLE
VPA - Can not solve Recommender "selector not found"

### ISSUE THREAD

**Issue by DragonBanana** [kubernetes/autoscaler#2953]
Hello everybody!
We were investigating VPA technology. But we have encountered some issues while trying to test it. During our test the VPA was not working as we hoped. We also tried *examples/hamster.yaml* and it was working, so we were wondering why our custom deployment file can not scale and get recommendations correctly.
Our Kubernetes cluster is installed 'bare-metal'.

This is my service.yaml file.
```
apiVersion: v1
kind: Service
metadata:
  name: prime-numbers
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: prime-numbers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-numbers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime-numbers
  template:
    metadata:
      labels:
        app: prime-numbers
    spec:
      containers:
      - name: prime-numbers
        image: pentabanana/prime-numbers:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prime-numbers-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: prime-numbers
```

And I checked that it is working correctly.

Running:
```
kubectl describe vpa
```
```
Name:         prime-numbers-vpa
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscaler","metadata":{"annotations":{},"name":"prime-numbers-vpa","namespa...
API Version:  autoscaling.k8s.io/v1beta2
Kind:         VerticalPodAutoscaler
Metadata:
  Creation Timestamp:  2020-03-21T14:49:50Z
  Generation:          2
  Resource Version:    4725246
  Self Link:           /apis/autoscaling.k8s.io/v1beta2/namespaces/default/verticalpodautoscalers/prime-numbers-vpa
  UID:                 a7330bd4-fc60-4294-b2ca-0d177f8d2d64
Spec:
  Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         prime-numbers
  Update Policy:
    Update Mode:  Auto
Status:
  Conditions:
    Last Transition Time:  2020-03-21T14:50:01Z
    Status:                True
    Type:                  RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  prime-numbers
      Lower Bound:
        Cpu:     25m
        Memory:  262144k
      Target:
        Cpu:     25m
        Memory:  262144k
      Uncapped Target:
        Cpu:     25m
        Memory:  262144k
      Upper Bound:
        Cpu:     25m
        Memory:  262144k

```

Then checking the vpa logs:
```
kubectl --namespace=kube-system get pods|grep vpa
```
```
vpa-admission-controller-7f47476b47-tpght   1/1     Running   0          23d
vpa-recommender-654ddbd47b-ndqg7            1/1     Running   0          23d
vpa-updater-6cd84c884-fl6mn                 1/1     Running   0          23d
```
Then when we try to check the VPA recommender log, we found this error:
```
kubectl --namespace=kube-system logs vpa-recommender-654ddbd47b-ndqg7| grep -e '^E[0-9]\{4\}'
```
```
E0307 21:15:01.481128       1 cluster_feeder.go:476] Error while fetching legacy selector. Reason: v1beta1 selector not found
E0307 21:16:01.481084       1 cluster_feeder.go:476] Error while fetching legacy selector. Reason: v1beta1 selector not found
E0307 21:17:01.481069       1 cluster_feeder.go:476] Error while fetching legacy selector. Reason: v1beta1 selector not found
E0307 21:18:01.481404       1 cluster_feeder.go:476] Error while fetching legacy selector. Reason: v1beta1 selector not found
E0307 21:19:01.481128       1 cluster_feeder.go:476] Error while fetching legacy selector. Reason: v1beta1 selector not found
E0307 21:20:01.481112       1 cluster_feeder.go:476] Error while fetching legacy selector. Reason: v1beta1 selector not found
E0307 21:20:01.493407       1 cluster_feeder.go:476] Error while fetching legacy selector. Reason: v1beta1 selector not found
E0307 21:21:01.481091       1 cluster_feeder.go:476] Error while fetching legacy selector. Reason: v1beta1 selector not found
```

I hope you can help us to solve the issue.
Thanks for your time.
