### ISSUE TITLE
VPA: Limit Prometheus queries to a custom namespaces

### ISSUE THREAD

**Issue by povilasv** [kubernetes/autoscaler#3010]
I would like to run VPA for a single namespace. Right now I can do this with custom Webhook configuration.
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vpa-webhook-config
webhooks:
- admissionReviewVersions:
  - v1beta1
  failurePolicy: Ignore
  matchPolicy: Exact
  name: vpa.k8s.io
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: In
      values: ["MY_AWESOME_NAMESPACE"]
```

What would be also useful is a way to limit Prometheus queries to a custom namespaces.

What do you think? I can do a PR ;)
