### ISSUE TITLE
[Need Help] Priority expander behavior when used alongside ASG tags in EKS

### ISSUE THREAD

**Issue by krishna-birla** [kubernetes/autoscaler#3066]
Consider an AWS EKS cluster running K8 1.14.x with cluster autoscaler 1.14.7, consisting of four auto scaling groups as follows:

- spot-nodes
k8s.io/cluster-autoscaler/node-template/label/usage=main
- on-demand-nodes
k8s.io/cluster-autoscaler/node-template/label/usage=fallback
- spot-gpu-nodes (has GPUs)
k8s.io/cluster-autoscaler/node-template/label/usage=main-gpu
- on-demand-gpu-nodes (has GPUs)
k8s.io/cluster-autoscaler/node-template/label/usage=fallback-gpu

<hr>

The `cluster-autoscaler-priority-expander` config map has two priority groups, and looks like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10: 
      - .*on-demand-nodes.*
      - .*on-demand-gpu-nodes.*
    50: 
      - .*spot-nodes.*
      - .*spot-gpu-nodes.*
```

<hr>

The pods look like this:

- Pod 1 (`pod1.yaml`)
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
   usage: main
```
- Pod 2 (`pod2.yaml`)
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
   usage: main-gpu
```
- Pod 3 (`pod3.yaml`)
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
   usage: fallback
```
- Pod 4 (`pod4.yaml`)
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-4
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
   usage: fallback-gpu
```
- Pod 5 (`pod5.yaml`)
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-5
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
```
- Pod 6 (`pod6.yaml`)
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-6
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
```
<hr>

Assume that all ASGs have enough resources.

What would be the behavior of the following commands?

- `kubectl create -f pod1.yaml`
- `kubectl create -f pod2.yaml`
- `kubectl create -f pod3.yaml`
- `kubectl create -f pod4.yaml`
- `kubectl create -f pod5.yaml`
- `kubectl create -f pod6.yaml`

Will ASG tags override the priority group specifications when `nodeSelector` labels and priorities conflict i.e. in the case of pods 3 and 4? Or will they get scheduled as per the priorities defined in the config map (hence ignoring the ASG tags)?

When `nodeSelector` labels and priorities DO NOT conflict i.e. in the case of pods 1 and 2, will the scheduling happen based on ASG tags, priority groups or pod requests (i.e. a pod with GPU requests will go on GPU nodes)? In case if it happens based on priority, since the node from a priority group is selected at random, what if a non-GPU node is selected for a GPU requesting pod.

In case where no `nodeSelector` is defined i.e. in the case of pods 5 and 6, what if the random choice of the priority expander selects a non GPU node from the highest priority group, for a GPU requesting pod?

Thanks in advance!
