### ISSUE TITLE
VPA Helm Chart 

### ISSUE THREAD

**Issue by techdragon** [kubernetes/autoscaler#3068]
It would be very useful to have a Helm Chart for deploying the Vertical Pod Autoscaler. At the moment its one of the few parts I cant deploy in any kind of idempotent/config management toolchain ( other than using shell execution of course 😄) 

If there is a recommended one it should be documented somewhere, if not, could someone more familiar with the install scripting look at if there are any blockers to making a helm chart?

**Comment by dbirks** [comment]
I've noticed a chart by @sebastien-prudhomme that he may want to contribute:
https://github.com/cowboysysop/charts/tree/master/charts/vertical-pod-autoscaler

**Comment by jkbschmid** [comment]
Any update on this issue? Is a Helm chart or support for any other deploy tool planned or generally desired?

**Comment by sebastien-prudhomme** [comment]
@jkbschmid i'm the author of the above chart.

If you look at the cluster-autoscaler Helm chart, it's maintained by the Helm community not the Kubernetes organization.

My feeling is that Kubernetes developpers don't want to take care of application packaging. They just provide raw YAML the same way some open source products just provide source code without DEB or RPM package.

I can understand it because some people, like me, prefer Helm, other people prefer Kustomize and so on.

**Comment by sudermanjr** [comment]
Found this issue after I created my own chart today. Seems very similar to the other one mentioned here. We will continue to maintain this one for now since it is a component needed by another tool of ours.

https://github.com/FairwindsOps/charts/pull/358

**Comment by rabidscorpio** [comment]
@jonkerj Did anything happen with this? Did you submit your chart? I'd love to see something official adopted.

**Comment by jonkerj** [comment]
No, it went dead after my message on 7 Sep. If a PR is desired from the VPA devs, we'd be glad to submit ours. 

We have mixed experience with putting a lot of effort into polishing something "internal" for PR/publication, so I'd like a confirmation from the devs before we put time into it (which we'd love to do).

**Comment by fredgate** [comment]
Maybe @bskiba has some answer.

**Comment by bskiba** [comment]
@jbartosik @kgolab for comment

**Comment by jonkerj** [comment]
And it went silent again. Let's try and see if a PR that adds the chart can shed more light on this mystery 😉

**Comment by jonkerj** [comment]
Let me retract my previous offer. It seems our chart is not so rolled on our own as I claimed: we have a local fork of cowboysysops (@sebastien-prudhomme). So it is up to @sebastien-prudhomme (apparantly the best VPA chart currently out there) to include his work into this repo or not. 

On the other hand: our offer still stands. Equinix is willing to submit a quality Helm chart, but I'd like confirmation from the project people before we put time and effort into this.

**Comment by imageschool** [comment]
Still no confirmation..?!

**Comment by rileyai-dev** [comment]
@jbartosik @kgolab @bskiba A project already exists (https://github.com/cowboysysop/charts/tree/master/charts/vertical-pod-autoscaler) and AFAIK the owner is willing to contribute to its integration into your repo. @jonkerj is willing to submit a chart. All we need from the maintainers is an approval or at least an explanation...

It's been 2.5 years and still nothing! Can't we, at least, have a message from the team about this?

**Comment by jbartosik** [comment]
@rileyai-dev I'm happy to accept contributions but I don't have capacity to maintain Helm charts.

**Comment by martinnirtl** [comment]
Hi @sebastien-prudhomme!
i just read the history of this issue (including your comment), and wonder what's your stand on moving the chart to this repository and contribute to it here? i think, it would gain much more attraction here and the community is definitely waiting for a helm chart for vpa 😃

**Comment by mrclrchtr** [comment]
I landed here because I was looking for the easiest way to install VPA. Do you rather usehttps://github.com/cowboysysop/charts/tree/master/charts/vertical-pod-autoscaler or https://github.com/FairwindsOps/charts/tree/master/stable/vpa ?

It would be really great if there was an official chat.

**Comment by nikimanoledaki** [comment]
@sebastien-prudhomme, with 55+ 👍's, it seems that the community would really appreciate this contribution! Would you be willing to donate the Chart that you have built to the Kubernetes project? That way we can all help to add best practices etc.

@techdragon or a maintainer - would it be possible to reopen this issue, please?

**Comment by techdragon** [comment]
I really hate auto close bots... glad it was just closed not locked.

**Comment by marcin-wlodarczyk** [comment]
@jonkerj is this quality VPA chart already published?

**Comment by sebastien-prudhomme** [comment]
@nikimanoledaki feel free to use my chart to build an official chart.

**Comment by nikimanoledaki** [comment]
Thank you @sebastien-prudhomme for offering to contribute the chart 🌟

Since @sebastien-prudhomme gave the green light - @jonkerj, does your offer still stand? 😄

**Comment by MattSurabian** [comment]
Been a while since @jonkerj was active on this thread, but in case they're not interested in taking up this effort I'd be happy to do so. I have a branch started on my own autoscaler fork but it seems the biggest constraint is going to be reconciling how the deployment assets are managed today in this repo vs how they were being managed in @sebastien-prudhomme 's chart repo which I imagine is the reason this effort has languished.

While it's possible to almost drop the old chart into the charts folder and call this done (so tempting!) it's worth noting that for cluster-autoscaler helm is the first class citizen and all deployment assets are managed up at the root `/charts` level. Since VPA hasn't had a chart, once one is added something needs to be done with the `hack` and `deploy` folders otherwise there will be two locations for maintaining manifest assets which is a nightmare.

I think priority for this effort should be not totally blowing up the workflow of the existing VPA project developers while also ensuring minimal/no values file changes for folks who have been on the unofficial community chart. Some of the existing `hack` scripts could be modified to accomplish things via helm which might be a start on that front. Success seems easy to measure since the output of `./vertical-pod-autoscaler/hack/vpa-process-yamls.sh print` should be able to be compared against `helm template` calls to ensure correctness.

Smaller considerations for manifest assets are things like how in the existing chart repo rbac resources are managed on a per component level while the existing VPA deploy logic lumps them all into one file (vpa-rbac). Personally I like the way the chart has things broken out, it seems desirable for long term maintenance and clarity. There's also the management of the base CRDs to consider.

@nikimanoledaki, curious to hear your and others reaction to the above. Happy to help in the implementation effort but want to make sure we start in the right direction.

**Comment by mohag** [comment]
> I think priority for this effort should be not totally blowing up the workflow of the existing VPA project developers while also ensuring minimal/no values file changes for folks who have been on the unofficial community chart. Some of the existing `hack` scripts could be modified to accomplish things via helm which might be a start on that front. Success seems easy to measure since the output of `./vertical-pod-autoscaler/hack/vpa-process-yamls.sh print` should be able to be compared against `helm template` calls to ensure correctness.

It might make sense to get it to match and then use `helm template` to generate the YAMLs from that script... (I'm not sure how the maintainers feel about centralising the workflow on Helm though) (It is commonly done, e.g. for Calico)

(This is mainly a comment to keep the bot from closing the issue)

**Comment by sftim** [comment]
A datapoint: the Kubernetes project doesn't routinely provide Helm charts for other components.

**Comment by jonkerj** [comment]
I've been zoned out of discussion for far too long, sorry for that.

> [@jonkerj](https://github.com/jonkerj) is this quality VPA chart already published?

Only internally within our company

> Thank you [@sebastien-prudhomme](https://github.com/sebastien-prudhomme) for offering to contribute the chart 🌟
> 
> Since [@sebastien-prudhomme](https://github.com/sebastien-prudhomme) gave the green light - [@jonkerj](https://github.com/jonkerj), does your offer still stand? 😄

VPA used to be a key ingredient in one of our products, but that product's future has taken a wild detour and the team structure has been rearranged a bit, reducing capacity for maintenance of external projects. Combined with the speed of decision making/discussion (years have passed since our offer) in this project makes us withdraw our offer, I'm afraid.

**Comment by especially-relative** [comment]
> A datapoint: the Kubernetes project doesn't routinely provide Helm charts for other components.

Most of those can be deployed via a raw manifest and are relatively simply deployments. VPA's install involves a shell script to manage admission controller certs that does not play nicely with GitOps.

Actually... is that `vpa-up.sh` script strictly needed or does the `kustomize.yaml` in the deploy folder work?

**Comment by mohag** [comment]
> > A datapoint: the Kubernetes project doesn't routinely provide Helm charts for other components.
> 
> Most of those can be deployed via a raw manifest and are relatively simply deployments. VPA's install involves a shell script to manage admission controller certs that does not play nicely with GitOps.
> 
> Actually... is that `vpa-up.sh` script strictly needed or does the `kustomize.yaml` in the deploy folder work?

Helm does have this function: https://helm.sh/docs/chart_template_guide/function_list/#genselfsignedcert

(I deploy it with Ansible normally and have these steps to deal with the webhook cert): (It might be a bit clearer what gets generated)
```yaml
    - name: Check if we have a VPA webhook certificate secret
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: vpa-tls-certs
        namespace: kube-system
        kubeconfig: "{{ kubectl_config | default(omit) }}"
        context: "{{ kubectl_context | default(omit) }}"
      register: k8s_vpa_secret

    - name: VPA secret generation
      block:
      # A lot of this is running on localhost, that we kan lookup the files later...
      - name: Tempdir for for VPA secret
        delegate_to: localhost
        become: no
        ansible.builtin.tempfile:
          state: directory
        register: k8s_vpa_tempdir

      - name: Generate CA private key for VPA secret
        delegate_to: localhost
        become: no
        community.crypto.openssl_privatekey:
          path: "{{ k8s_vpa_tempdir.path }}/ca.key"

      - name: Generate CA CSR for VPA secret
        delegate_to: localhost
        become: no
        community.crypto.openssl_csr_pipe:
          privatekey_path: "{{ k8s_vpa_tempdir.path }}/ca.key"
          basicConstraints:
          - "CA:TRUE"
          subject: "CN=vpa_webhook_ca"
          subjectAltName:
          - "DNS:vpa_webhook_ca"
        register: k8s_vpa_ca_csr

      - name: Generate CA for VPA secret
        delegate_to: localhost
        become: no
        community.crypto.x509_certificate:
          csr_content: "{{ k8s_vpa_ca_csr.csr }}"
          provider: selfsigned
          privatekey_path: "{{ k8s_vpa_tempdir.path }}/ca.key"
          path: "{{ k8s_vpa_tempdir.path }}/ca.crt"
          selfsigned_not_after: "+100000d"

      - name: Generate private key for VPA secret
        delegate_to: localhost
        become: no
        community.crypto.openssl_privatekey:
          path: "{{ k8s_vpa_tempdir.path }}/webhook.key"

      - name: Generate CSR for VPA secret
        delegate_to: localhost
        become: no
        community.crypto.openssl_csr_pipe:
          privatekey_path: "{{ k8s_vpa_tempdir.path }}/webhook.key"
          basicConstraints:
          - "CA:FALSE"
          key_usage:
          - nonRepudiation
          - digitalSignature
          - keyEncipherment
          extended_key_usage:
          - clientAuth
          - serverAuth
          subject: "CN=vpa-webhook.kube-system.svc"
          subjectAltName:
          - "DNS:vpa-webhook.kube-system.svc"
        register: k8s_vpa_csr

      - name: Generate certficate for VPA secret
        delegate_to: localhost
        become: no
        community.crypto.x509_certificate:
          csr_content: "{{ k8s_vpa_csr.csr }}"
          provider: ownca
          ownca_privatekey_path: "{{ k8s_vpa_tempdir.path }}/ca.key"
          ownca_path: "{{ k8s_vpa_tempdir.path }}/ca.crt"
          privatekey_path: "{{ k8s_vpa_tempdir.path }}/webhook.key"
          path: "{{ k8s_vpa_tempdir.path }}/webhook.crt"
          ownca_not_after: "+99000d"

      # This is not on localhost, but the lookups are
      - name: Create VPA certificate secret on cluster
        kubernetes.core.k8s:
          state: present
          apply: yes
          kubeconfig: "{{ kubectl_config | default(omit) }}"
          context: "{{ kubectl_context | default(omit) }}"
          definition:
            apiVersion: v1
            kind: Secret
            metadata:
              namespace: kube-system
              name: vpa-tls-certs
            type: Opaque
            data:
              caKey.pem: "{{ lookup('file',k8s_vpa_tempdir.path + '/ca.key') | b64encode }}"
              caCert.pem: "{{ lookup('file',k8s_vpa_tempdir.path + '/ca.crt') | b64encode }}"
              serverKey.pem: "{{ lookup('file',k8s_vpa_tempdir.path + '/webhook.key') | b64encode }}"
              serverCert.pem: "{{ lookup('file',k8s_vpa_tempdir.path + '/webhook.crt') | b64encode }}"
```

For Helm that would likely involve [`genCA`](https://helm.sh/docs/chart_template_guide/function_list/#genca) and [`genSignedCert`](https://helm.sh/docs/chart_template_guide/function_list/#gensignedcert). (My 100k / 99k days validity is probably not ideal, but I do not want to figure out how to figure out if a cert is about to expire...)

The manifests only mount the certs into the admission controller deployment. A quick look at the code does not seem to indicate any logic to generate the certs internally. (And with the provided manifests, the pod would fail to start since it won't be able to mount the secret if it is not supplied) (A Helm hook to generate the secret might be an option as well...)
