### ISSUE TITLE
CA 1.15.6 not able to scale from ASG with min=0

### ISSUE THREAD

**Issue by jvaibhav123** [kubernetes/autoscaler#3101]
Hi,

I have CA version 1.15.6 running my kubeadm cluster. The ASG is tagged correctly like below
```
k8s.io/cluster-autoscaler/node-template/label/nodeclass | spot
k8s.io/cluster-autoscaler/node-template/taint/spotenabled | 'false':NoSchedule
k8s.io/cluster-autoscaler/node-template/label/asg_type | small
node-role.kubernetes.io/nodeclass | spot
```
CA is configured with autodiscover ASG. 

I have sample deployment like below
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
    nodeclass: spot
    project: test1
  name: nginx-asg-test
  namespace: test-monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        nodeclass: spot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/nodeclass
                operator: In
                values:
                - spot
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        asg_type: small
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: spotenabled
        operator: Equal
        value: "false"
```

However CA doesnt scale up the ASG from 0. The pod always remain in pending status with below message.
```
Normal   NotTriggerScaleUp  8m13s (x8 over 12m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 7 node(s) didn't match node selector, 9 node(s) had taints that the pod didn't tolerate
  Normal   NotTriggerScaleUp  2m9s (x43 over 12m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 9 node(s) had taints that the pod didn't tolerate, 7 node(s) didn't match node selector
  Warning  FailedScheduling   69s (x18 over 12m)   default-scheduler   0/10 nodes are available: 10 node(s) didn't match node selector.
```

The CA logs show below

```
I0428 18:41:21.656806       1 utils.go:229] Pod nginx-asg-test-679df8c4f5-x4b6h can't be scheduled on dt-ue2-test-opa-resources-t3.medium-20200428T2358-0, predicate failed: PodToleratesNodeTaints predicate mismatch, reason: node(s) had taints that the pod didn't tolerate, taints on node: []v1.Taint{v1.Taint{Key:"spotenabled", Value:"'false'", Effect:"NoSchedule", TimeAdded:(*v1.Time)(nil)}}
I0428 18:41:21.656810       1 utils.go:221] Pod nginx-asg-test-679df8c4f5-nfq2x can't be scheduled on dt-ue2-test-opa-resources-t3.medium-20200428T2358-0. Used cached predicate check results
```
Toleration exists in deployment and taints are applied at ASG . I am not sure whats missing. Could you please help here?

I saw similar tickets in the past but not sure if this is something related conf issue or ?
