### ISSUE TITLE
autoscaling with gpu fails

### ISSUE THREAD

**Issue by magnusja** [kubernetes/autoscaler#3448]
Hey there,

this is my yaml config:

```yaml
    resources:
      limits:
        cpu: "16"
        memory: 60Gi
        nvidia.com/gpu: "2"  # also tried 4 which is the actual number of gpus
      requests:
        cpu: "12"
        memory: 50Gi
        nvidia.com/gpu: "2"  # also tried 4 which is the actual number of gpus
```

I am always getting this error (GCP):
```
0/8 nodes are available: 8 Insufficient cpu, 8 Insufficient memory, 8 Insufficient nvidia.com/gpu.
```
It does not really what I put in the yaml file it is pretty much always 8,7 or 9. The pod never gets scheduled even though I have a node pool with 4 gpus and 16 CPUs, 200GB of RAM (machine type is n1-highmem-32).

The UI fails miserably and is splitting nvidia and com/gpu. not sure if only a UI problem or a general problem.
![image](https://user-images.githubusercontent.com/1659457/90910951-85799400-e3d8-11ea-9643-61a239fd37cd.png)
