### ISSUE TITLE
Helm chart doesn't add service account annotations

### ISSUE THREAD

**Issue by lexsys27** [kubernetes/autoscaler#3454]
I want to install cluster autoscaler using the latest Helm chart. Here is my `values.yaml`:

```
autoDiscovery:
  clusterName: dev
rbac:
  serviceAccount:
    name: autoscaler
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::XXX:role/k8s-system-autoscaler-role
```

After applying configuration I do `kubectl get sa/autoscaler -o yaml` and see no annotation named `eks.amazonaws.com/role-arn`. That mean CA can't authenticate using OIDC provider and fails to start.

I expect Helm chart to add annotation `eks.amazonaws.com/role-arn: arn:aws:iam::XXX:role/k8s-system-autoscaler-role` to the SA `autoscaler`
