### ISSUE TITLE
How to run cluster-autoscaler (vanilla) in DigitalOcean

### ISSUE THREAD

**Issue by pablokbs** [kubernetes/autoscaler#3469]
Hello, I'm trying to run CA in my DO cluster, but I don't want to use their in-house version as it doesn't allow me to change any flag.

I tried running it myself but I faced a few problems, the first one was that even when having a fixed node-pool, CA seems to be running in the DO side, so the leader election collides with the vanilla one. I fixed this by disabling leader-election. I'm currently running the following manifest, but it's failing with the error below.

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
rules:
  - apiGroups: [""]
    resources: ["events", "endpoints"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["endpoints"]
    resourceNames: ["cluster-autoscaler"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch", "list", "get", "update"]
  - apiGroups: [""]
    resources:
      - "pods"
      - "services"
      - "replicationcontrollers"
      - "persistentvolumeclaims"
      - "persistentvolumes"
    verbs: ["watch", "list", "get"]
  - apiGroups: ["extensions"]
    resources: ["replicasets", "daemonsets"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["watch", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "replicasets", "daemonsets"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
  - apiGroups: ["coordination.k8s.io"]
    resourceNames: ["cluster-autoscaler"]
    resources: ["leases"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-autoscaler-status", "cluster-autoscaler-priority-expander"]
    verbs: ["delete", "get", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.3
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=digitalocean
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/k8s-1-18-6-do-0-sfo2-xxxxxxxxxxx
            - --leader-elect=false
```

The error I'm getting is:

```
cluster-autoscaler-7857c7b6c4-8wlhv cluster-autoscaler I0828 02:13:00.293494       1 cloud_provider_builder.go:29] Building digitalocean cloud provider.
cluster-autoscaler-7857c7b6c4-8wlhv cluster-autoscaler F0828 02:13:00.293521       1 digitalocean_cloud_provider.go:182] Failed to create DigitalOcean manager: access token is not provided
```

How do I provide the token to the deployment? I can't find any docs for this.

This is the full log if you want to check it out: [gist](https://gist.github.com/pablokbs/bf29766d816ae8238c6f7718d0ea69c4)

cc @timoreimann

**Comment by tobiaskohlbau** [comment]
Hello, to be fair upfront I've never used digital ocean but I was just making myself familiar with the autoscaler and discovered your issue and wanted to try to help.

From looking into the code I observed that you should use _--cloud-config_ as a flag.
https://github.com/kubernetes/autoscaler/blob/d9e8fa3cbba3c3c76adf96e70bbb1277fad60ea7/cluster-autoscaler/main.go#L88
As the code documents it should be a path to the actual cloud-config. The cloud-config itself must be in JSON format according to:
https://github.com/kubernetes/autoscaler/blob/d9e8fa3cbba3c3c76adf96e70bbb1277fad60ea7/cluster-autoscaler/cloudprovider/digitalocean/digitalocean_manager.go#L72-L81

The struct of the config is shown here:
https://github.com/kubernetes/autoscaler/blob/d9e8fa3cbba3c3c76adf96e70bbb1277fad60ea7/cluster-autoscaler/cloudprovider/digitalocean/digitalocean_manager.go#L56-L68

So I would use a ConfigMap to provide the needed `cloud-config.json`.

```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-configmap
  labels:
    app: autoscaler
data:
  cloud-config.json: |
    {
       "cluster_id": "ID",
       "token": "TOKEN",
       "url": "URL"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.3
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=digitalocean
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/k8s-1-18-6-do-0-sfo2-xxxxxxxxxxx
            - --leader-elect=false
            - --cloud-config=/autoscaler/cloud-config.json
          volumeMounts:
            - name: autoscaler-configmap-volume
               mountPath: /autoscaler
        volumes:
        - name: autoscaler-configmap-volume
           configMap:
             name: autoscaler-configmap
```

I hope I did not made any typos.

**Comment by pablokbs** [comment]
Thanks @tobiaskohlbau ! your comment helped me a lot, I'm pasting below my manifests (there were some issues with extra spaces, I know, yaml, right?)

Now CA runs, but is not actually doing anything, seems like it can't find the node-pool, logs [here](https://gist.github.com/pablokbs/83bb40341a429109c32485a88c1e6f08)

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-configmap
  namespace: kube-system
  labels:
    app: autoscaler
data:
  cloud-config.json: |
    {
       "cluster_id": "c1f72bcd-f5b8-4c36-a934-xxxxxxxx", # grab this from your "server" line in the kubeconfig
       "token": "xxxxx", # get this from the kubeconfig file 
       "url": "https://api.digitalocean.com" 
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.3
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=digitalocean
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/k8s-1-18-6-do-0-sfo2-1598155562734
            - --leader-elect=false
            - --cloud-config=/autoscaler/cloud-config.json
          volumeMounts:
            - name: autoscaler-configmap-volume
              mountPath: /autoscaler
      volumes:
        - name: autoscaler-configmap-volume
          configMap:
            name: autoscaler-configmap
```

I'm following this [small doc](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/digitalocean) and added the tags to the node-pool, but it seems like CA can't find the node-pool to start adding nodes.
