### ISSUE TITLE
VPA ControlledResources doesn't work.

### ISSUE THREAD

**Issue by nairb774** [kubernetes/autoscaler#3501]
Using a VPA like the following results in the CPU recommendations being produced and applied:

```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hamster
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hamster
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: ["memory"]
```

It looks like in the process of building the [container name to aggregate state map](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/routines/vpa.go#L27) the `ControlledResources` value is not copied from the working state to the per-container aggregate state in [AggregateStateByContainerName](https://github.com/kubernetes/autoscaler/blob/a80841eed5359df78c9bf806918c16af6a4aaf6d/vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go#L294-L306). This prevents the ControlledResource information from flowing down to where the filtering is applied.

[These changes](https://github.com/kubernetes/autoscaler/commit/eb72f989343e646ad41ba8f8f9ef48184c37e086), while hacky, address the problem and result in controlled resources working correctly. The main reason for not submitting a PR, is its not clear to me that this is the right change. In some ways the `ControlledResources` hanging off the `AggregateContainerState` breaks the abstraction boundary. Alternatively, [the filtering](https://github.com/tweks/autoscaler/blob/51eb724400a2ee366b3049b29a294ccf079c852d/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L83-L85) is possibly being done at the wrong place in the pipeline. Maybe the ControlledResources should be observed in the updater or the admission controller rather than in the recommender?

@tweks you seem to have done the initial implementation - thoughts?
