### ISSUE TITLE
Unable to get Autodiscovery to work with EKS therefore no Deployment

### ISSUE THREAD

**Issue by witchbutter** [kubernetes/autoscaler#3504]
I have been using autoscaler successfully for quite a while.  I am trying to update using the 1.0.3 Helm chart which is supposed to autodiscover based on cluster name, but no matter what I do no autoscaler deployment gets made.  All of the tags are already in place as well as IAM permissions applied to the worker node roles because, as I said, I have been using the autoscaler successfully already without Helm.  There seems to be no way to troubleshoot the autodiscovery?  Even with --debug there are no error messages.  

These are my custom values applied to the helm install:
```
cluster-autoscaler-chart:
  autoDiscovery:
    clusterName: mycluster
    tags:
      - k8s.io/cluster-autoscaler/enabled
      - k8s.io/cluster-autoscaler/mycluster
  #autoscalingGroups:
  #  - name: ng1
  awsRegion: us-east-2
  cloudProvider: aws
  image:
    # The major version of the tag should match the version of the cluster
    tag: 1.17.3
  extraArgs:
    leader-elect: false
    min-replica-count: 1
  replicaCount: 1
  serviceMonitor:
    enabled: true
```
