### ISSUE TITLE
Cluster Autoscaler failed to start on Bottlerocket Node

### ISSUE THREAD

**Issue by tommy-sho** [kubernetes/autoscaler#3513]
## environment
- EKS: v1.17
- Cluster Autoscaler: v1.17.3

## description
I made EKS node group by eksctl and cluster.yaml is like below, 
```
  - name: ng-bottlerocket
    amiFamily: Bottlerocket
    instanceType: m5.large
    desiredCapacity: 5
    minSize: 0
    maxSize: 10
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    securityGroups:
        ...
    ssh:
      allow: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/eks-cluster: "owned"
```

if the cluster autoscaler pod run on Bottlerrocket node, the pod always couldn't start running.
'kubeclt describe' command show below message. It seems an error occurs related rootfs system.
Anyone has same problem or information? Thx

```
  Warning  Failed     2m22s (x4 over 3m15s)  kubelet, ip-172-20-27-91.ap-northeast-1.compute.internal  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/etc/ssl/certs/ca-bundle.crt" to rootfs at "/run/containerd/io.containerd.runtime.v2.task/k8s.io/cluster-autoscaler/rootfs/etc/ssl/certs/ca-certificates.crt" caused: not a directory: unknown
```
