### ISSUE TITLE
The Affinity don't support template - helm chart

### ISSUE THREAD

**Issue by LozanoMatheus** [kubernetes/autoscaler#3516]
Hi there,

I'm trying to set up the affinity and prevent the PODs to run in the same node, but the `templates/deployment.yaml` don't support template.

I'm trying set on `values.yaml`
```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: "{{ .Release.Name }}"
```

The output - It's considering the `"{{ .Release.Name }}"` as a string:
```yaml
...
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: '{{ .Release.Name }}'
...
```

If I remove the quotes:
```text
history.go:52: [debug] getting history for release cluster-autoscaler
Error: failed to parse values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Release.Name":interface {}(nil)}
helm.go:94: [debug] error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Release.Name":interface {}(nil)}
failed to parse values.yaml
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues
	/home/circleci/helm.sh/helm/pkg/cli/values/options.go:54
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:134
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
```
