### ISSUE TITLE
VPA 'no pods found'

### ISSUE THREAD

**Issue by hprotzek** [kubernetes/autoscaler#3531]
We are running a vpa for Prometheus Operator instances on GKE 1.18.6-gke.3504. We thought after the issue #2159  got fixed, this should be working. But we now we get `No recommendation provided from the recommendation engine: No pods found.`

Other vpa configurations, with non operator resources are working as expected. Is this possible again related to the CRDs of the Prometheus Operator?

```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus-example
  updatePolicy:
    updateMode: Auto
status:
  conditions:
  - lastTransitionTime: "2020-09-22T06:14:30Z"
    message: 'No recommendation provided from the recommendation engine: No pods found.'
    reason: 'No recommendation provided from the recommendation engine: No pods found.'
    status: "False"
    type: RecommendationProvided
  recommendation: {}
```

```
apiVersion: apps/v1
kind: StatefulSet
  name: prometheus-example
  namespace: prometheus-example
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: prometheus-example
    uid: 857262d5-e10a-4eff-8d9f-d84696821b5f
spec:
...
```
