### ISSUE TITLE
Doesn't scale up ASG from 0 with Mixed Instance Policy

### ISSUE THREAD

**Issue by nucleusv** [kubernetes/autoscaler#3535]
**Problem:** 
Austoscaler doesn't scale up the ASG with metal nodes from 0, 
IF desiredCapasity is 0, it means that until autoscaler will see in cluster a running node it can not build node-template on ASG tags annotations. When desiredCapacity is 1, a node is added to cluster when ASG is created and then Autoscaler triggers up properly.

Pods are assigned to those nodes via NodeSelector and tolerations:
```
           nodeSelector:                   
              kubernetes.io/os: linux
              node-type: metal
            tolerations:
              - key: spotQAMetalInstance
                operator: Equal
                value: 'true'
                effect: PreferNoSchedule
```

**Autoscaler version**: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.18.1

**ASG with MixedInstancePolicy (eksctl config)**:
```
   name: 'ngm--spot-metal'
    availabilityZones: ["eu-west-1a","eu-west-1b","eu-west-1c"]
    amiFamily: AmazonLinux2
    labels:
      kubernetes.io/os: linux
      node-lifecycle: preemptible
      lifecycle: Ec2Spot
      node-type: metal
      aws.amazon.com/spot: "true"
    taints:
      spotQAMetalInstance: "true:PreferNoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/node-type: metal
      k8s.io/cluster-autoscaler/node-template/resources/cpu: "96"
      k8s.io/cluster-autoscaler/node-template/resources/memory: "192294Mi"
      k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage: "600Gi"
      k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
      k8s.io/cluster-autoscaler/node-template/taint/spotQAMetalInstance: "true:PreferNoSchedule"
    instancesDistribution:
      spotAllocationStrategy: capacity-optimized
      maxPrice: 3.5
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      instanceTypes:
        - c5d.metal
        - m5d.metal
        - r5d.metal
    ami: auto
    minSize: 0
    maxSize: 3
    desiredCapacity: 1
```

**Such events on pending pods:** 
pod didn't trigger scale-up (it wouldn't fit if a new node is added): 3 Insufficient cpu, 1 node(s) didn't match node selector
