### ISSUE TITLE
Option to ignore custom resources

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/autoscaler#3537]
Is there a configuration available to ignore vpa from fetching custom resources?

I was able to get around the RBAC errors on the custom resources by adding to the clusterrole system:vpa-target-reader.
```
- apiGroups: 
  - '*'
  resources:
  - '*/scale'
  verbs:
  - get
  - watch
```

But ideally, I want to ignore these resources. Is this possible?
