### ISSUE TITLE
Add aggregation taget to clusterroles for custom resources

### ISSUE THREAD

**Issue by Jamstah** [kubernetes/autoscaler#3669]
It would be useful to add an `aggregationRule` to the `ClusterRole`s so that operators with custom resources that support the scale subresource can add read permissions for their CRs to the VPA operator without the user needing to manually do it.

For example, adding this to the rbac:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:vpa-target-reader
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.example.com/aggregate-to-vpa-target-reader: "true"
rules:
  ... no change ...
```

https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
