### ISSUE TITLE
Cluster Autoscaler is not running (i.e. log is empty) - Setting up AutoScaler in AWS EKS

### ISSUE THREAD

**Issue by ameliatqy** [kubernetes/autoscaler#3688]
Hello guys,

It seems that I have a problem getting Cluster Autoscaler to start functioning. These are the steps I took:

1. Create EKS using config file below. Note that the node group is unmanaged group.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kube-test
  region: us-west-2
  version: '1.18'

nodeGroups:
  - name: eks-atee
    instanceType: p2.xlarge
    availabilityZones: ["us-west-2b"]
    labels:
      node-group: research-atee
    taints:
      production: "false:NoSchedule"
    desiredCapacity: 0
    minSize: 0
    maxSize: 2
    volumeSize: 60
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      allow: true
      publicKeyPath: 'turk1'
    tags:
      k8s.io/cluster-autoscaler/node-template/label/node-group: research-atee
      k8s.io/cluster-autoscaler/node-template/taint/production: "false:NoSchedule"
```

2. Check that the IAM policy is set for my nodeGroup
<img width="1328" alt="Screen Shot 2020-11-12 at 4 57 59 PM" src="https://user-images.githubusercontent.com/33330101/99014774-4014c080-2508-11eb-8de0-fae29e2f7f18.png">

3. Check that the tags are in my AutoScaling group (in EC2 console, AutoScaling menu):
<img width="1321" alt="Screen Shot 2020-11-12 at 4 56 25 PM" src="https://user-images.githubusercontent.com/33330101/99014697-0e035e80-2508-11eb-94fe-6ab0040b15ec.png">

4. Apply (i.e. deploy) autoscaler using the following YAML file (i.e. `kubectl apply -f deployment_autoscale_multi_asg.yaml`). Below, I did try to start the AutoCluster manually based on https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml. I tried auto-discovery like in  https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html but that did not work as well:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
rules:
  - apiGroups: [""]
    resources: ["events", "endpoints"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["endpoints"]
    resourceNames: ["cluster-autoscaler"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch", "list", "get", "update"]
  - apiGroups: [""]
    resources:
      - "pods"
      - "services"
      - "replicationcontrollers"
      - "persistentvolumeclaims"
      - "persistentvolumes"
    verbs: ["watch", "list", "get"]
  - apiGroups: ["extensions"]
    resources: ["replicasets", "daemonsets"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["watch", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "replicasets", "daemonsets"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
  - apiGroups: ["coordination.k8s.io"]
    resourceNames: ["cluster-autoscaler"]
    resources: ["leases"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-autoscaler-status", "cluster-autoscaler-priority-expander"]
    verbs: ["delete", "get", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.18.3
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --nodes=0:2:eksctl-kube-test-nodegroup-eks-atee-NodeGroup-000000
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-bundle.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"
```
5. Type in `kubectl -n kube-system logs -f deployment/cluster-autoscaler` - log is completely empty. Tried one sample deployment, the nodes did not scale at all.

So, what could be the issue here? Any help is appreciated
