### ISSUE TITLE
Cluster Autoscaler examples and helm chart is different

### ISSUE THREAD

**Issue by foriequal0** [kubernetes/autoscaler#3724]
I wanted to deploy cloud-autoscaler using Helm Chart to ease the maintance.
So I've tweaked helm values to match with the AWS Cloud Autoscaler manual ([here](https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/cluster-autoscaler.html)) and the example ([here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml))
```js
{
  fullnameOverride: "cluster-autoscaler",
  image: {
    // Updated as the manual says
    tag: "v1.18.3",
    pullPolicy: "Always"
  },
  
  // As in the example
  resources: {
    limits: {
      cpu: "100m",
      memory: "300Mi"
    },
    requests: {
      cpu: "100m",
      memory: "300Mi"
    }
  },
  // As in the example
  podDisruptionBudget: null,

  cloudProvider: "aws",
  awsRegion: "<YOUR CLUSTER REGION>",

  autoDiscovery: {
    clusterName: "<YOUR CLUSTER NAME>"
  },
  extraArgs: {
    // Helm chart default values
    // logtostderr: true, // Doesn't exist in the example
    stderrthreshold: "info",
    v: 4,
    // Exists in the example
    "skip-nodes-with-local-storage": false,
    expander: "least-waste",
    // Exists in the manual
    "balance-similar-node-groups": true,
    "skip-nodes-with-system-pods": false
  }
}
```
However there are still subtle differences:
1. The chart has extra `ClusterRole` for batch, batch/extensions, but the example doesn't:
```yaml
  - apiGroups: ["batch"],
    resources: ["jobs", "cronjobs"]
    verbs: ["watch", "list", "get"]
```
2. The example has extra `Role` for some resources
The chart has a role only for
```yaml
  - apiGroups: [""],
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: [""],
    resources: ["cluster-autoscaler-status"]
    verbs: ["delete", "get", "update"]
```
However the example has more roles:
```yaml
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-autoscaler-status", "cluster-autoscaler-priority-expander"]
    verbs: ["delete", "get", "update", "watch"]
```
(edit: I think `cluster-autoscaler-status` for the example isn't necessary, but the chart needs it when there is `expander=priority`)
3. The example doesn't have `Service`
4. The example has volumes and volume mounts, but the chart doesn't:
```yaml
...
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt #/etc/ssl/certs/ca-bundle.crt for Amazon Linux Worker Nodes
              readOnly: true
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"
```

Can somebody can explain the difference? I think the examples should be based on the helm charts to reduce the confusions.
