### ISSUE TITLE
Priority expander: {node-group} not found in priority expander configuration

### ISSUE THREAD

**Issue by kxesd** [kubernetes/autoscaler#3735]
While using `cluster-autoscaler:v1.18.3` with kubernetes 1.18.10 we are seeing in the logs that it cannot find some node groups

priority-expander configMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
data:
  priorities: |-
    10:
      - .*
    20:
      - .*nodes-a-ondemand.*
      - .*nodes-b-ondemand.*
    30:
      - .*nodes-a-spot.*
      - .*nodes-b-spot.*
```

cluster-autoscaler container arguments:
```
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --expander=priority
            - --skip-nodes-with-local-storage=false
            - --skip-nodes-with-system-pods=false
            - --nodes=1:2:nodes-cifs.cluster.k8s.tld
            - --nodes=0:12:nodes-a-ondemand.cluster.k8s.tld
            - --nodes=2:12:nodes-a-spot.cluster.k8s.tld
            - --nodes=0:12:nodes-b-ondemand.cluster.k8s.tld
            - --nodes=2:12:nodes-b-spot.cluster.k8s.tld
            - --nodes=0:4:nodes-ssd-spot.cluster.k8s.tld
            - --balance-similar-node-groups=true
```

We see these messages in the logs:
```
1 priority.go:91] Priority expander: node group nodes-a-ondemand.cluster.k8s.tld not found in priority expander configuration. The group won't be used.
1 priority.go:91] Priority expander: node group nodes-b-ondemand.cluster.k8s.tld not found in priority expander configuration. The group won't be used.
```

Originally we did not have the wildcard regex at priority 10 however after reading the suggestion [HERE](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md#configuration) we added it. However even with the wildcard regex it still does not match the node group and the message persists in the logs.
> Note that if a group name doesn't match any of the regular expressions in the priority list it will not be considered for expansion. To ensure that all of your groups are autoscaled you might want to add a "catch-all" regex of .* (with a low priority) to your priorities list.

Previously on `cluster-autoscaler:v1.18.2` we did not see this message however we did see the issue that was fixed in #3308

**Comment by umialpha** [comment]
It may not be a bug. it looks more like a **misleading log.**
When **the priority of certain node group is below max priority currently found** or **the regex pattern is not matched**, the node group is skipped. So I think it's because CA found a better group, e.g spot, ssd.

Code Ref: 	[https://github.com/kubernetes/autoscaler/blob/2ff1f55689abbbd230bd3f43c634a0d972b17e84/cluster-autoscaler/expander/priority/priority.go#L139](url)

**Comment by balusarakesh** [comment]
we use AWS EKS node groups, CA seems to use the AWS auto-scaling group instead of node group names
expander config:
```
apiVersion: v1
kind: ConfigMap
data:
  priorities: |-
    20:
      - .*spot.*
    10:
      - .*on-demand.*
```

logs:
```
Priority expander: node group eks-40bbb26b-8679-eb64-d33a-4ba475413529 not found in priority expander configuration. The group won't be used
```

`eks-40bbb26b-8679-eb64-d33a-4ba475413529` is actually an auto-scaling group and NOT a node group. Node groups are named something like `app-standard-spot-a-qa-5bkjmt`
