### ISSUE TITLE
Cannot use a Service as a targetRef for the VPA (Vertical Pod Autoscaler)?

### ISSUE THREAD

**Issue by RayBB** [kubernetes/autoscaler#3752]
I am trying use a [Service](https://kubernetes.io/docs/concepts/services-networking/service/) as the targetRef (target reference) for a [VPA](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler).

When I try to do this I get the error below. 
I have checked that the VPA,Pod,Service are all in the same namespace.

Any ideas why this isn't working?
All the contributors here have already done so much hard work to make this and I really appreciate it.
Hope this question is helpful to others in the future.

## Error 
```
Message:               Cannot read targetRef. Reason: Unhandled targetRef v1 / Service / my-service, last error the server could not find the requested resource
Status:                True
Type:                  ConfigUnsupported
```

## Example Config

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    job-name: daily-report-generation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376

apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: service-vpa
spec:
  targetRef:
    apiVersion: "v1"
    kind:       Service
    name:       my-service
  updatePolicy:
    updateMode: "Auto"
```

I also asked about this on the Kubernetes Slack [here](https://kubernetes.slack.com/archives/C09R1LV8S/p1607475076397700). Cross-posting it to GitHub for discoverability. Will update this post if I get an answer on Slack.
