### ISSUE TITLE
Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list

### ISSUE THREAD

**Issue by herrbpl** [kubernetes/autoscaler#3799]
**Which component are you using?**:

cluster-autoscaler
**What version of the component are you using?**:

us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.18.1

Component version: Cluster Autoscaler 1.18.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-15T00:59:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
aws cloud provider

**What did you expect to happen?**:
Autoscale should start

**What happened instead?**:

```
I0108 11:04:34.227764       1 cloud_provider_builder.go:29] Building aws cloud provider.
F0108 11:04:34.227958       1 aws_cloud_provider.go:363] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list
```
**How to reproduce it (as minimally and precisely as possible)**:
Not sure. It started to fail when tried to use 1.18.1. For some clusters, it works, for others, it does not. Really not sure why.

**Anything else we need to know?**:
IAM policy set for nodes:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "WorkerAutoscalingAll",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeLaunchTemplateVersions",
                "autoscaling:DescribeTags",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeAutoScalingGroups",
                "ec2:DescribeInstanceTypes"
            ],
            "Resource": "*"
        },
        {
            "Sid": "eksWorkerAutoscalingOwn",
            "Effect": "Allow",
            "Action": [
                "autoscaling:UpdateAutoScalingGroup",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:SetDesiredCapacity"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled": "true",
                    "autoscaling:ResourceTag/kubernetes.io/cluster/prod-k8s-02": "owned"
                }
            }
        }
    ]
}
```
values.yaml
```yaml
---
  autoDiscovery: 
    clusterName: "prod-k8s-02"
  awsRegion: "eu-central-1"
  cloudProvider: "aws"  
  rbac: 
    create: "true"
    pspEnabled: "true"
  tolerations: 
    - effect: NoSchedule  
      operator: "Equal"
      value: "true"
      key: node-role.kubernetes.io/controlplane
    - effect: NoExecute  
      operator: "Equal"
      value: "true"
      key: node-role.kubernetes.io/etcd
  nodeSelector:
    node-role.kubernetes.io/controlplane: "true"
```
