### ISSUE TITLE
Cluster Autoscaler fails to scale up AWS Managed Node Group which has multiple instance_types

### ISSUE THREAD

**Issue by pre** [kubernetes/autoscaler#3856]
**Which component are you using?**: cluster-autoscaler 

**What version of the component are you using?**: v1.20.0 (installed via helm-chart 9.4.0)

```
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  write-status-configmap: true
  skip-nodes-with-local-storage: false
  scale-down-enabled: true
  balance-similar-node-groups: true
  min-replica-count: 2
  scale-down-utilization-threshold: 0.5
  scale-down-non-empty-candidates-count: 5
  max-node-provision-time: 15m0s
  scan-interval: 10s
  scale-down-delay-after-add: 1m
  scale-down-delay-after-delete: 0s
  scale-down-delay-after-failure: 3m
  scale-down-unneeded-time: 1m
```

**What k8s version are you using (`kubectl version`)?**: EKS 1.18

**What environment is this in?**: EKS 1.18

**What did you expect to happen?**:

We have multiple Managed Node Groups which have different instance types in each of them. 

For example, there is one compute oriented Managed Node Group which provides all the variants of EC2 c5 instance types:
```
  instance_types = ["c5.large", "c5.xlarge", "c5.2xlarge", "c5.4xlarge", "c5.9xlarge", "c5.12xlarge", "c5.18xlarge", "c5.24xlarge"]
```

[It seems](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-up-work) that cluster-autoscaler does not understand that a Managed Node Group can provide with different instance types. 

Let's assume that cluster is already running one type of an instance from this Managed Node Group, for example `c5.large`. 
When a Deployment requests an instance type from that same Managed Node Group, but type which _is not_ yet available in the cluster, the pods stay in Pending stage indefinitely. (nodeSelector for eg. `c5.24xlarge`).

[It seems](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-up-work) that cluster-autoscaler does not understand that the Managed Node Group, which has already provided `c5.large`, can _also_ provide eg. `c5.24xlarge`. 

Hence, the Pods which requested `c5.24xlarge` do not trigger scale up of a new machine, because cluster-autoscaler thinks that this Managed Node Group only provides `c5.large` instances, although the Managed Node Group can provide _any_ `c5.*`instance types (see array above). 

The workaround for this could be to create a separate Managed Node Group for each of the instance types, each group containing only a single instance_type. However, due to a [limitation in the Managed Node Group](https://github.com/aws/containers-roadmap/issues/724), you cannot currently have `min_size: 0`. This means that each Managed Node Group would need to always be running at least one node. 

TL;DR It seems that cluster-autoscaler is not currently compatible with EKS Managed Node Groups with multiple instance_types. Please correct me if I'm wrong! I'd like to find out a workaround for this issue.
