### ISSUE TITLE
Enabling Pod Security policy causing Autodiscovery errors

### ISSUE THREAD

**Issue by KR411-prog** [kubernetes/autoscaler#3865]
I have enabled PSP in Cluster autoscaler ,
```
rbac:
  create: true
  pspEnabled: true
  serviceAccount:
    create: false
    # from IAM Roles for Service Account
    name: aws-cluster-autoscaler
autoDiscovery:
  enabled: true
  clusterName: $CLUSTER_NAME
  tags:
  - "kubernetes.io/cluster/$CLUSTER_NAME"
  - "k8s.io/cluster-autoscaler/enabled"
```

This was working well before enabling psp. But after enabling it, I am getting below errors,
```
E0202 03:46:56.809571       1 aws_manager.go:262] Failed to regenerate ASG cache: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
I am not sure what has caused this issue..The pod is in crashlooping status.

It created the PSP. But pod is in error..Please let me know how to fix this.
```
NAME                     PRIV    CAPS   SELINUX    RUNASUSER   FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
aws-cluster-autoscaler   false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,secret,hostPath,emptyDir,projected,downwardAPI
```

Kubernetes platform: EKS
Version: 1.16
Cluster autoscaler chart version: 1.1.1
