### ISSUE TITLE
cluster-autoscaler : KubeSchedulerConfiguration plugin configuration PodTopologySpread

### ISSUE THREAD

**Issue by Ramyak** [kubernetes/autoscaler#3879]
**Which component are you using?**:

component: cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Scheduler now supports [PodTopologySpread - Cluster-level default constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#cluster-level-default-constraints) from kubernetes release 1.18 - [commit](https://github.com/kubernetes/kubernetes/commit/1b4b1553328892e1e5486b5151f423ef78668b52).

**1. PodTopologySpread - `defaultConstraints` at the cluster level**: Cluster-autoscaler does not consider PodTopologySpread `defaultConstraints` at the cluster level. 

```
apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
profiles:
  - pluginConfig:
      - name: PodTopologySpread
        args:
          defaultConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
          defaultingType: List
```
Pods remain unscheduled. You get the error.
Note: Pod specs do not have `topologySpreadConstraints` in this case.
```
I0210 18:03:11.409934       1 filter_out_schedulable.go:118] Pod test-app-5b75d455c9-7gpf5 marked as unschedulable can be scheduled on node ip-172-21-145-192.ec2.internal (based on hinting). Ignoring in scale up.
```

**2. PodTopologySpread when set at deployment**: works since pod spec starts having topologySpreadConstraints.
```
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app: some-app
        release-unixtime: "1611668612"
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
```

**Describe the solution you'd like.**:

Cluster-autoscaler consider [PodTopologySpread - Cluster-level default constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#cluster-level-default-constraints) during attempts to schedule pods

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by vadasambar** [comment]
This is expected behavior. `ScheduleAnyway` constraint is processed during Scoring (Priority Function) part of the scheduling process in the scheduler. It is not processed during Filtering (Predicate) part of the scheduling process in the scheduler. 

CA only uses `Filter` part in the simulations (`PreFilter` and `Filter` extension points to be precise)
- `CheckPredicates` function
  - PreFilter: https://github.com/kubernetes/autoscaler/blob/32c6bbc0c9eced9c756525e15dfb3cfb00a52226/cluster-autoscaler/simulator/predicatechecker/schedulerbased.go#L153
  - Filter: https://github.com/kubernetes/autoscaler/blob/32c6bbc0c9eced9c756525e15dfb3cfb00a52226/cluster-autoscaler/simulator/predicatechecker/schedulerbased.go#L163
- `FitsAnyNodeMatching` function
  - PreFilter: https://github.com/kubernetes/autoscaler/blob/32c6bbc0c9eced9c756525e15dfb3cfb00a52226/cluster-autoscaler/simulator/predicatechecker/schedulerbased.go#L109
  - Filter: https://github.com/kubernetes/autoscaler/blob/32c6bbc0c9eced9c756525e15dfb3cfb00a52226/cluster-autoscaler/simulator/predicatechecker/schedulerbased.go#L129 

---

`ScheduleAnyway` is a part of scoring phase of the `PodTopologySpread` plugin
- https://github.com/kubernetes/autoscaler/blob/bd2ff82aa1e369456022935591464d37f63881d6/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go#L71

While `DoNotSchedule` is a part of the filter/predicate phase of the `PodTopologySpread` plugin
- https://github.com/kubernetes/autoscaler/blob/bd2ff82aa1e369456022935591464d37f63881d6/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L256

---

As long as `DoNotSchedule` is used, CA should respect the constraint. One problem I see with the current implementation in the CA is, we do not support a custom default constraint. We use the default one. If you specify a `DoNotSchedule` custom default constraint, CA might not respect it.

**Comment by jdomag** [comment]
@vadasambar 
You said that CA respects default cluster constrain, but also that CA doesn't support `ScheduleAnyway`.
But the default cluster constrain is `ScheduleAnyway` according to the docs:
```
defaultConstraints:
  - maxSkew: 3
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: ScheduleAnyway
  - maxSkew: 5
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: ScheduleAnyway
```
Can you elaborate on this one, please?
