### ISSUE TITLE
Priority Expander selecting random node pools.

### ISSUE THREAD

**Issue by danthegoodman1** [kubernetes/autoscaler#3890]
**Which component are you using?**: Cluster Autoscaler with Priority Exapnder

**What version of the component are you using?**: 1.20.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ v1.18.9-eks-d1db3c
</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**:

Cluster Autoscaler would select one node group over another when scaling up consistently.

**What happened instead?**:

Cluster Autoscaler would inconsistently select node groups. Sometimes it would respect the priority, but other times it would add nodes from the lower priority group.

**How to reproduce it (as minimally and precisely as possible)**:

Here are the node groups and CA config used:

```sh
aws eks create-nodegroup \
--cluster-name <clustername> \
--ami-type "AL2_x86_64" \
--nodegroup-name cli7-ng \
--disk-size 50 \
--subnets "subnet-..." \
--instance-types "m5.xlarge" \
--remote-access ec2SshKey="..." \
--node-role "..." \
--labels createdFrom="cli" \
--client-request-token hellothereee \
--capacity-type ON_DEMAND \
--scaling-config minSize=1,maxSize=20,desiredSize=1

aws eks create-nodegroup \
--cluster-name <clustername> \
--ami-type "AL2_x86_64" \
--nodegroup-name cli6-ng \
--disk-size 50 \
--subnets "subnet-..." \
--instance-types "c5.xlarge" \
--remote-access ec2SshKey="..." \
--node-role "..." \
--labels createdFrom="cli" \
--client-request-token hellothereee \
--capacity-type ON_DEMAND \
--scaling-config minSize=1,maxSize=20,desiredSize=1
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10:
    - cli6-ng.*
    50:
    - cli7-ng.*
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
rules:
  - apiGroups: [""]
    resources: ["events", "endpoints"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["endpoints"]
    resourceNames: ["cluster-autoscaler"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch", "list", "get", "update"]
  - apiGroups: [""]
    resources:
      - "pods"
      - "services"
      - "replicationcontrollers"
      - "persistentvolumeclaims"
      - "persistentvolumes"
    verbs: ["watch", "list", "get"]
  - apiGroups: ["extensions"]
    resources: ["replicasets", "daemonsets"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["watch", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "replicasets", "daemonsets"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
  - apiGroups: ["coordination.k8s.io"]
    resourceNames: ["cluster-autoscaler"]
    resources: ["leases"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-autoscaler-status", "cluster-autoscaler-priority-expander"]
    verbs: ["delete", "get", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.20.0
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=priority
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/<clustername>
            - --max-node-provision-time=5m0s
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt #/etc/ssl/certs/ca-bundle.crt for Amazon Linux Worker Nodes
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"

```

**Anything else we need to know?**:

I noticed when trying to configure a priority expand to scale a spot node pool over my on demand node pool that the AWS documentation vs the official k8s documentation have some significant differences.

Notably, k8s uses `priorities` while AWS uses `priority`. Furthermore, if you follow the links, aws says:

> Cluster Autoscaler will try to scale up the Amazon EC2 Auto Scaling group matching the name p2-node-group. If this operation doesn't succeed within --max-node-provision-time, it will attempt to scale an Amazon EC2 Auto Scaling group matching the name p3-node-group...

indicating that the lowest value will try to expand first, while k8s says:

> The priority should be a positive value. The highest value wins. For each priority value, a list of regular expressions should be given. If there are multiple node groups matching any of the regular expressions with the highest priority...

indicating that the highest value will try to expand first.

Here are the examples each provide for reference

AWS: https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priority: |-
    10:
      - .*p2-node-group.*
    50:
      - .*p3-node-group.*
```
(they say 10 will launch first)

k8s: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10: 
      - .*t2\.large.*
      - .*t3\.large.*
    50: 
      - .*m4\.4xlarge.*
```
(they say 50 will launch first)
