### ISSUE TITLE
Cluster-autoscaler doesn't scale nodes for pods with RuntimeClass.

### ISSUE THREAD

**Issue by iusergii** [kubernetes/autoscaler#3943]
**Which component are you using?**:
Cluster-autoscaler.

**What version of the component are you using?**:
v.1.19.1, v.1.20.0.

**What environment is this in?**:
Cluster v.1.19.8 is deployed with kops in AWS.

**What did you expect to happen?**:
I want to add ARM64 Instances (instance groups) to my cluster and manage the scheduling/scalling of Pods with RuntimeClass. 
```yaml
apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: linux-arm64
handler: 'docker'
scheduling:
  nodeSelector:
    kubernetes.io/os: 'linux'
    kubernetes.io/arch: 'arm64'
  tolerations:
  - effect: NoSchedule
    key: arch
    operator: Equal
    value: "arm64"
```
Pods which has this runtimeclass are not triggering the scale-up of arm64 instances. 

**What happened instead?**:
Pod stuck in Pending state. CA log:
```
Pod ... can't be scheduled on arm64..., predicate checking error: node(s) didn't match Pod's node affinity; predicateName=NodeAffinity; reasons: node(s) didn't match Pod's node affinity; debugInfo=
```

**Anything else we need to know?**:
Once I scaled instances manually from 0 to 1 - pod scheduled successfully on the arm64 node.
