### ISSUE TITLE
Daemonset annotation cluster-autoscaler.kubernetes.io/safe-to-evict = true

### ISSUE THREAD

**Issue by Vitorspk** [kubernetes/autoscaler#3970]
Hello,

- I have a doubt referent to the annotation: ` "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"`

- I have a node with 3 pods and one of them is sidecar and this pod has the annotation configured in the daemonset:

```
   template:
     metadata:
       labels:
         app.kubernetes.io/name: xxx-agent
         app.kubernetes.io/version: 1.2.6
       annotations:
         "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
```

- Pods are from the kube-system but I spent the annotation to ignore the kube-system in the autoscaler according to the documentation:

```
           name: cluster-autoscaler
           resources:
             limits:
               cpu: 100m
               memory: 300Mi
             requests:
               cpu: 100m
               memory: 300Mi
           command:
             - --skip-nodes-with-system-pods = false
```

- I don't have any disk being created in these nodes, I don't have any PDB.

- Does annotation work in the sidecar daemonset?

NOTE:

After create autoscaler on cluster this is solved and now deleting pod from daemonset.
