### ISSUE TITLE
CA fails to schedule nodes onto spot ASG's with zero instances producing "node(s) didn't match node selector" on EKS

### ISSUE THREAD

**Issue by alexmnyc** [kubernetes/autoscaler#4010]
My nodes:
```
--kubelet-extra-args "--node-labels=node.kubernetes.io/lifecycle=spot,group-name=spot,instance=m5.xlarge" 'pie-gp-8pN1ZRZI'
```
My ASG of instance=m5.xlarge
```
desired=0 min=0 max=20
```
Scheduling this deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-to-scaleout
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        service: nginx
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-to-scaleout
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
      nodeSelector:
        instance: m5a.large
```

CA logs:

```
node(s) didn't match node selector
```

Related to https://github.com/kubernetes/autoscaler/issues/4002 ?

**Comment by bpineau** [comment]
Hi,
Is cluster-autoscaler launched with `--scale-up-from-zero`?
Does the ASG have a matching label (ie. `k8s.io/cluster-autoscaler/node-template/label/instance: m5a.large` (per pod's nodeSelector, or `m5.xlarge` per kubelet args above))?

**Comment by alexmnyc** [comment]
@bpineau I tried adding these labels to the ASG yesterday as you mentioned,  and to the kubelet extra args --node-labels i.e. "--node-labels=node.kubernetes.io/lifecycle=spot,group-name=spot,instance=m5a.large"

![image](https://user-images.githubusercontent.com/1847565/115565091-13b75a00-a287-11eb-8447-d7b94b3e1eda.png)

I did a deployment with both selectors and still the same results

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-to-scaleout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        service: nginx
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-to-scaleout
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
      nodeSelector:
        instance: m5a.large
        k8s.io/cluster-autoscaler/node-template/label/instance: m5a.large
```
