### ISSUE TITLE
Tagging annotation for AWS autoscaler ASG's

### ISSUE THREAD

**Issue by gavinvandermerwe** [kubernetes/autoscaler#4025]
**Which component are you using?**:

AWS Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

I am looking into creating "disposable" EKS kubernete's environments in AWS. I use terraform for as much as I can but I find that ASG's are created using this. It would be super useful if I could propogate tags via annotations on these ASG's because then I could reliably discover and delete the right ones using the aws cli.

**Describe the solution you'd like.**:

Maybe something like: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
  annotations:
    cluster-autoscaler.kubernetes.io/tags: '<my-superflous-tag-name-so-i-can-tear-it-down-easy>:<my-superflous-tag-value-so-i-can-tear-it-down-easy>'

```

**Describe any alternative solutions you've considered.**:

A total n00b with kubernete's. Been doing way too much pivotal cloud foundry. :)

**Additional context.**:

Thank you for understanding, this might already be implemented, if so ... please be kind when telling me off :)
