### ISSUE TITLE
Autoscaler deployment is not created by helm flux operator

### ISSUE THREAD

**Issue by DannyKR** [kubernetes/autoscaler#4063]
Hello,

I am trying to create the cluster-autoscaler with flux, but the deployment is not created.
Only the cluster-autoscaler service is created, but not the deployment? 

This is my HelmRelease file:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: cluster-autoscaler
  chart: 
    repository: https://kubernetes.github.io/autoscaler
    name: cluster-autoscaler
    version: 9.9.2
  awsRegion: eu-west-1
  rbac:
    create: true
    pspEnabled: true
    autoDiscovery:                                                                                                                      
      clusterName: ekscluster

```
Thanks in advance
