### ISSUE TITLE
controlledValues: RequestsOnly dosn't works

### ISSUE THREAD

**Issue by ivanov-aleksander** [kubernetes/autoscaler#4075]
**Which component are you using?**: 

vertical-pod-autoscaler,

**What version of the component are you using?**: 

Component version: 0.9.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"8ab00ff68a1763b5a506a7073cb8e67b12dfbcd7", GitTreeState:"clean", BuildDate:"2021-03-10T23:40:01Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: 

Azure AKS

**What did you expect to happen?**:

VPA sets only requests.

**What happened instead?**:

VPA sets requests and limits

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
  updatePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: "RequestsOnly"
    updateMode: Initial
```

**Anything else we need to know?**:

**Comment by ivanov-aleksander** [comment]
@johanneswuerbach could you help with this bug?

**Comment by johanneswuerbach** [comment]
The config seems wrong, could you try to configure it like?

```yaml

resourcePolicy:
  containerPolicies:
  - containerName: '*'
    controlledValues: RequestsOnly
    controlledResources:
    - cpu
    - memory
updatePolicy:
  updateMode: Initial
```
