### ISSUE TITLE
Set node group pool1 size from 0 to 0, expected delta 0

### ISSUE THREAD

**Issue by vladimirtiukhtin** [kubernetes/autoscaler#4107]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

v1.21.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What environment is this in?**:

Hetzner Cloud

**Commandline**
```
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.0
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --cloud-provider=hetzner
            - --stderrthreshold=info
            - --nodes=3:5:CX11:HEL1:pool1
          env:
          - name: HCLOUD_TOKEN
            valueFrom:
              secretKeyRef:
                name: hcloud
                key: token
          - name: HCLOUD_CLOUD_INIT
            value: XXXX
          - name: HCLOUD_SSH_KEY
            value: XXXX
          - name: HCLOUD_NETWORK
            value: XXXX
          imagePullPolicy: "Always"
```
**What did you expect to happen?**:

Node scaling to work

**What happened instead?**:

```
I0528 22:25:58.726332       1 hetzner_node_group.go:421] Set node group pool1 size from 0 to 0, expected delta 0
```

**How to reproduce it (as minimally and precisely as possible)**:

Just deploy it using official sample https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml
