### ISSUE TITLE
Autoscaler chart is missing some rules

### ISSUE THREAD

**Issue by phenixdotnet** [kubernetes/autoscaler#4114]
**Which component are you using?**:
Cluster Autoscaler Helm chart

**What version of the component are you using?**:
Latest

**What k8s version are you using (`kubectl version`)?**:
v1.20.4-eks-6b7464 & v1.19.6-eks-49a6c0

**What environment is this in?**:
EKS on AWS

**What did you expect to happen?**:
Autoscaler can access to all required resource in the cluster or doesn't try to access to unneeded resources

**What happened instead?**:
cluster-autoscaler logs report a permission denied when trying to access to some csi related resources:
```
k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:serviceaccount:REDACTED:REDACTED-cluster-autoscaler" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
````
and for `csistoragecapacities`

**How to reproduce it (as minimally and precisely as possible)**:
Launch cluster-autoscaler from the helm chart with service account and RBAC enabled

**Anything else we need to know?**:
We fixed it by changing the [cluster role](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/templates/clusterrole.yaml#L104) from:
```
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - csinodes
  verbs:
  - watch
  - list
  - get
``` 
to 
```
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - csinodes
  - csidrivers
  - csistoragecapacities
  verbs:
  - watch
  - list
  - get
```

But I'm not sure this change is the best/correct as I don't know the minimum permissions required for `csidrivers` and `csistoragecapacities`
