### ISSUE TITLE
How to pass GCP service account the cluster autoscaler pod

### ISSUE THREAD

**Issue by rimusz** [kubernetes/autoscaler#4212]
Is there a way to pass and use GCP service account to Cluster Autoscaler helm chart?
I do not want to update VMs Cloud API scope, but use pass that from the application level.
Thanks

**Comment by rimusz** [comment]
never mind found it myself :) 
Create a secret with GCP service account:
```
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-gcp-sa
  namespace: kube-system
type: Opaque
data:
  gcp-api-sa-key.json: "xxxxxxxxxxxx"
```

And add it to the override-values.yaml:
```
autoDiscovery:
  clusterName: <gke-cluster-name>

autoscalingGroupsnamePrefix:
  - name: gke-<gke-cluster-name>
    maxSize: 10
    minSize: 1

cloudProvider: gce

priorityClassName: system-node-critical

extraArgs:
  skip-nodes-with-local-storage: false
  skip-nodes-with-system-pods: false
  scale-down-enabled: true
  scale-down-utilization-threshold: 0.6
  scale-down-non-empty-candidates-count: 5
  scan-interval: 10s

extraEnv:
  GOOGLE_APPLICATION_CREDENTIALS: /data/gcp-sa/gcp-api-sa-key.json

extraVolumeSecrets:
  gcp-sa-vol:
    name: cluster-autoscaler-gcp-sa
    mountPath: /data/gcp-sa/
```

And install it with:
```
$ helm upgrade --install cluster-autoscaler -n kube-system helm/cluster-autoscaler --version 9.10.2 -f override-values.yaml
```
