### ISSUE TITLE
[VPA] Ability to control amount of acceptable throttling

### ISSUE THREAD

**Issue by Niksko** [kubernetes/autoscaler#4230]
**Which component are you using?**:
VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
We have a number of workloads (cluster-autoscaler) being a good example, where we have to constantly tweak the request:limit ratio in order to avoid the workload being throttled. This work is toil, and we would like an automated way of handling this. These workloads are cluster critical, and as such, throttling is unacceptable.

**Describe the solution you'd like.**:
As proposed in [this old issue](https://github.com/kubernetes/autoscaler/issues/3091), some way of configuring the VPA to set limits such that a workload is not throttled at least some percentage of the time.

Something like:

```
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: hamster-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: hamster
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu", "memory"]
        noThrottlingTarget: 0.99
```

The `noThrottlingTarget: 0.99` instructs the VPA to choose CPU limits such that the container's CPU is throttled roughly 99% of the time.

**Describe any alternative solutions you've considered.**:
The current solution is to just set the request:limit ratio very high. e.g. `request: 100m`, `limit: 1`. However this feels hacky, because the goal of setting limits is to ensure that runaway processes don't exhaust the CPU of a node.
