### ISSUE TITLE
Cluster autoscaler ignore node taints?

### ISSUE THREAD

**Issue by anemptyair** [kubernetes/autoscaler#4231]
**Which component are you using?**: 
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.16.6

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Cluster auto scale ignore node taints

We have added some taints for cluster nodes. Auto scale will failed when node are enough but with taints that pods can not be schedule into them.
Can cluster auto scaler ignore nodes taints ?

**Describe the solution you'd like.**:

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by bpineau** [comment]
If those taints names are known in advance, there's a `--ignore-taint` flag to that effect.

**Comment by vadasambar** [comment]
@pierluigilenoci would these be the right steps to reproduce for this issue?
1. Scale up a node
2. Add a taint to the node
3. Deploy a workload (Deployment/Pod) which wants to schedule on the new node (but can't because it doesn't have tolerations for the recently added taint)

cluster-autoscaler will not scale up thinking it can fit the workload in 3 on the tainted node.

**Comment by pierluigilenoci** [comment]
@vadasambar exactly.

**Comment by vadasambar** [comment]
cluster-autoscaler might not be considering the newly added taints like you say. Might need deeper investigation.

**Comment by vadasambar** [comment]
I can reproduce the problem.
### Steps to reproduce
1. Deploy your own CA (cluster-autoscaler) (how? check [this](https://github.com/kubernetes/autoscaler/issues/966#issuecomment-1473125867))
2. Induce scale up (use workload with anti-affinity to make CA bring up new nodes)
```
kubectl scale deploy node-scale-up-with-pod-anti-affinity --replicas=4
deployment.apps/node-scale-up-with-pod-anti-affinity scaled

```
![image](https://user-images.githubusercontent.com/34534103/226533719-38dec2da-a441-4288-b34a-42c4d143a3b7.png)

3. Taint the new node
```
kubectl taint no gke-cluster-1-default-pool-7c54e36a-h2gg test=true:NoSchedule
node/gke-cluster-1-default-pool-7c54e36a-h2gg tainted
```
4. Create workload to schedule on the tainted node
```
kubectl create deploy nginx --image=nginx --replicas=1
deployment.apps/nginx created
```
Use `nodeSelector` to target the tainted node
![image](https://user-images.githubusercontent.com/34534103/226533880-bbe0e867-cb31-4cb6-bf62-c5db7e08bb75.png)

5. Pod gets stuck in `Pending` forever
![image](https://user-images.githubusercontent.com/34534103/226533079-96bcb5dd-1a21-4623-aec9-efe06b999931.png)

Example scale up workload
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-scale-up-with-pod-anti-affinity
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-scale-up-with-pod-anti-affinity
  replicas: 1
  template:
    metadata:
      labels:
        app: node-scale-up-with-pod-anti-affinity
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - node-scale-up-with-pod-anti-affinity
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: node-scale-up-with-pod-anti-affinity
        image: registry.k8s.io/pause:2.0
```
