### ISSUE TITLE
[VPA] Recommender cannot detect OOM if container restart policy is 'Never'

### ISSUE THREAD

**Issue by CappuccinoCup** [kubernetes/autoscaler#4279]
I created a pod like this to try "OOM" event capture feature.
```
kind: Pod
metadata:
  name: vpa-test-pod
  ...
spec:
  containers:
  - name: main
    ...
  restartPolicy: Never
...
```
It is OOMKilled after a while as expected. But the recommendation remains unchanged. I check the logs and find that no OOM event is detected. Perhaps it's because of these codes:
[Check restart count > 0 in Observer](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go#L150)
```
if containerStatus.RestartCount > 0 &&
    containerStatus.LastTerminationState.Terminated != nil &&
    containerStatus.LastTerminationState.Terminated.Reason == "OOMKilled" {
...
```
Is there any reason to ignore OOM event caused by pods with 'restartPolicy' set to 'Never'? If not, maybe we can add some codes to detect them?
