### ISSUE TITLE
[cluster-autoscaler] Helm chart cannot handle duplicate extra args for `balancing-ignore-label`

### ISSUE THREAD

**Issue by ArchiFleKs** [kubernetes/autoscaler#4306]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: 1.21.0

Component version: AWS EKS 1.21

**What k8s version are you using (`kubectl version`)?**: AWS EKS 1.21

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: `--balancing-ignore-label` must be specified X time, X being the number of label an operator want to ignore.

Currently because extraArgs use map, this:

```
    ¦ ¦ extraArgs:                                                                     
    ¦ ¦ ¦ scale-down-utilization-threshold: 0.7                                        
    ¦ ¦ ¦ balancing-ignore-label: topology.ebs.csi.aws.com/zone                        
    ¦ ¦ ¦ balancing-ignore-label: eks.amazonaws.com/nodegroup                          
    ¦ ¦ ¦ balancing-ignore-label: eks.amazonaws.com/nodegroup-image                    
    ¦ ¦ ¦ balancing-ignore-label: eks.amazonaws.com/sourceLaunchTemplateId             
    ¦ ¦ ¦ balancing-ignore-label: eks.amazonaws.com/sourceLaunchTemplateVersion    
``` 

Does not work because only the last value will be parse

**What happened instead?**:  All the extra args should be reflected in the deployment

**How to reproduce it (as minimally and precisely as possible)**:

set this as values:

```
extraArgs:                                                                     
 scale-down-utilization-threshold: 0.7                                        
 balancing-ignore-label: topology.ebs.csi.aws.com/zone                        
 balancing-ignore-label: eks.amazonaws.com/nodegroup                          
 balancing-ignore-label: eks.amazonaws.com/nodegroup-image                    
 balancing-ignore-label: eks.amazonaws.com/sourceLaunchTemplateId             
 balancing-ignore-label: eks.amazonaws.com/sourceLaunchTemplateVersion    
```

**Anything else we need to know?**:

I'm not sur how to solve this, either create a specific use case for this particular flag, I don't know if there are other flags that can be specified. Or add an `extraArgsList` that allow users to specifiy args as a yaml list in addition to the `extraArgs` map.
