### ISSUE TITLE
HETZNER - Custom Labels on scaled nodes

### ISSUE THREAD

**Issue by ThatDeveloper** [kubernetes/autoscaler#4604]
**Which component are you using?**:
Hetzner

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
More and more developers decide to let their more and more complex solutions run on kubernetes and in order for them to spot a place to run, need labels on them. (Affinity)
With adding the possibility to add multiple (n) custom labels to the `--nodes=` that will get applied on a scale event, that would be great. Also, the node pool could be selected / preffered if the labels match the ones of the pod.

**Describe the solution you'd like.**:
`--nodes=1:10:CPX21:FSN1:pool1:[abc.io/services]`
`--nodes=1:10:CPX51:FSN1:pool1:[abc.io/services,abc.io/regular]`
The selection of the nodepool would look if [label...] is present and select based on this; scale up would add these labels to the node.

**Describe any alternative solutions you've considered.**:
Working with prebuilt images, but the cluster autoscaler can not differentiate.

**Comment by AzSiAz** [comment]
Documentation is not fantastic but you can already scale up based on `pool1` in your exemple

But it's not based on Kubernetes labels but Hetzner node labels

```yaml
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hcloud/node-group
                operator: In
                values:
                  - pool1
```
