### ISSUE TITLE
How to prevent my RabbitMQ pod from Autoscaling and restarting.

### ISSUE THREAD

**Issue by yuvansh33** [kubernetes/autoscaler#4652]
I’m using EKS version 1.21, I want to setup my pods and services in such a way that cluster autoscaler can not disturb a particular pod and it should stay in that node only on which it was scheduled initially and until and unless i want to do some changes manually. I’ve already tried using system-node-critical as priority class name , but unfortunately it didn’t make any difference . Despite of the fact that i gave my pod the highest priority available still my pod got reschedule on another pod because cluster autoscaler shift the pods to under-utilised node for better usage of instances  which resulted the error on those services which are dependent on each other, for example server is dependent on rabbitMQ services and if the pod of rabbitMQ get rescheduled then it leads to error on server.

- This is my code for rabbitmq.yaml file

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: staging
spec:
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: kube-system
      version: "8.22.3"
  interval: 5m
  releaseName: rabbitmq
  values:
    priorityClassName: system-node-critical
    replicaCount: 4
    auth:
        username: staging
        password: rabbitmq-secret
        existingPasswordSecret: rabbitmq-secret
        erlangCookie: **************************
    extraConfiguration: |-
      default_vhost=use2-mmc-1021
      consumer_timeout=86400000
    memoryHighWatermark:
        enabled: "true"
        type: absolute
        value: 1536MB
    resources:
        limits:
            cpu: 500m
            memory: 2048Mi
        requests:
            cpu: 500m
            memory: 2048Mi
    livenessProbe:
        initialDelaySeconds: 120
        timeoutSeconds: 20
        periodSeconds: 30
        failureThreshold: 6
        successThreshold: 1
    readinessProbe:
        initialDelaySeconds: 10
        timeoutSeconds: 20
        periodSeconds: 30
        failureThreshold: 3
        successThreshold: 1
    service:
        type: ClusterIP
    serviceAccount:
        create: true
```
