### ISSUE TITLE
Safe-to-evict annotation not working with RabbitMQ Pod.

### ISSUE THREAD

**Issue by yuvansh33** [kubernetes/autoscaler#4668]
I’m using EKS version 1.21, I want to setup my pods and services in such a way that cluster autoscaler can not disturb a particular pod and it should stay in that node only on which it was scheduled initially and until and unless i want to do some changes manually. I’ve already tried using system-node-critical as priority class name and Safe-to-evict annotation as well , burt still my problem persists . My rabbitmq pods are still restaring despite of having priorityclass and safe-to-evict annotation still my pod got reschedule on another node because cluster autoscaler shift the pods to under-utilised node for better usage of instances which resulted the error on those services which are dependent on each other, for example server is dependent on rabbitMQ services and if the pod of rabbitMQ get rescheduled then it leads to error on server.
I'm attacing my Rabbitmq.yaml code and cluster autoscaler logs screenshots as well.
please help me with this issue.

``` apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: staging
spec:
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: kube-system
      version: "8.22.3"
  interval: 5m
  releaseName: rabbitmq
  values:
    priorityClassName: system-node-critical
    replicaCount: 4
    auth:
        username: staging
        password: rabbitmq-secret
        existingPasswordSecret: rabbitmq-secret
        erlangCookie: *************************************
     extraConfiguration: |-
      default_vhost=********
      consumer_timeout=86400000
    memoryHighWatermark:
        enabled: "true"
        type: absolute
        value: 1536MB
    resources:
        limits:
            cpu: 500m
            memory: 2048Mi
        requests:
            cpu: 500m
            memory: 2048Mi
    livenessProbe:
        initialDelaySeconds: 120
        timeoutSeconds: 20
        periodSeconds: 30
        failureThreshold: 6
        successThreshold: 1
    readinessProbe:
        initialDelaySeconds: 10
        timeoutSeconds: 20
        periodSeconds: 30
        failureThreshold: 3
        successThreshold: 1
    service:
        type: ClusterIP
    serviceAccount:
        create: true
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
 ```

Cluster Autoscaler logs :-
![Screenshot 2022-02-07 at 3 41 56 PM](https://user-images.githubusercontent.com/98579964/152770231-d74f7655-e026-4bd3-999f-57b8a1917a76.png)

**Comment by ricardojdsilva87** [comment]
Hello we have the same issue, it seems that the pod annotation doesn't matter when deleting nodes.
These pods are ephemeral, they are spawned run a job and then are deleted. It seems that the node is deleted even if there is still a running pod (some of them already running for more than 20 minutes)
We are running CA 1.20.2 in kubernetes 1.20.15 with the following extra args:
```
extraArgs:
  v: 4
  stderrthreshold: info
  logtostderr: true
  scale-down-utilization-threshold: 0.07
  scale-down-non-empty-candidates-count: 10
  max-empty-bulk-delete: 5
  scale-down-unneeded-time: 10m
  scale-down-delay-after-add: 20m
  skip-nodes-with-system-pods: false
```
The annotation is also added to the pods that we don't want to remove:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
```

Is there some more information that I can retrieve to debug the issue?
Thank you
