### ISSUE TITLE
Cluster Autoscaler for Exoscale - FailedScheduling

### ISSUE THREAD

**Issue by rpbaquing-cloudmade** [kubernetes/autoscaler#4782]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: 9.16.2

Component version: latest

**What k8s version are you using (`kubectl version`)?**: 1.23

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**: exoscale

**What did you expect to happen?**: to deploy cluster-autoscaler

**What happened instead?**: the pod got stuck in pending status. 
```
Warning  FailedScheduling  79s   default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector.
Warning  FailedScheduling  11s   default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector.
```

**How to reproduce it (as minimally and precisely as possible)**:

1. Clone the repository - kubernetes/autoscaler
2. Go to autoscaler/cluster-autoscaler/cloudprovider/exoscale/examples
3. Create the secret required for the credentials in Exoscale using the *generate-secret.sh* script
4. Apply the manifests cluster-autoscaler-run-on-control-plane.yaml to deploy cluster-autoscaler.

**Anything else we need to know?**:

I was expecting it will tolerate the taints in the control plane, but I don't think it is the case here.

**Comment by skol101** [comment]
@jbartosik any update on the issue?

**Comment by jbartosik** [comment]
Hi, I work on VPA. I also label issues to make it easier to find issues I want to check. I think @MaciekPytel is point of contact for CA

**Comment by PhilippeChepy** [comment]
Hello,

On my view, the deployment provided as an example is missing a proper toleration field. If you are deploying your cluster with `kubeadm`, you probably want to update the Deployment for something like that instead:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - name: cluster-autoscaler
          image: exoscale/cluster-autoscaler:latest
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - /cluster-autoscaler
            - --cloud-provider=exoscale
            - --stderrthreshold=info
            - --cordon-node-before-terminating
            #- --scale-down-delay-after-add=30s
            #- --scale-down-unneeded-time=30s
            #- --unremovable-node-recheck-timeout=30s
          env:
          - name: EXOSCALE_API_KEY
            valueFrom:
              secretKeyRef:
                key: api-key
                name: exoscale-api-credentials
          - name: EXOSCALE_API_SECRET
            valueFrom:
              secretKeyRef:
                key: api-secret
                name: exoscale-api-credentials
          - name: EXOSCALE_ZONE
            valueFrom:
              secretKeyRef:
                key: api-zone
                name: exoscale-api-credentials
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-certificates.crt"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
```


Please note that `node-role.kubernetes.io/control-plane` was `node-role.kubernetes.io/master` in previous releases (before `kubeadm` v1.24.x).
