### ISSUE TITLE
Cluster Autoscaler ignoring safe to evict annotations on pods running as part of Job

### ISSUE THREAD

**Issue by apatil4** [kubernetes/autoscaler#4813]
**Which component are you using?**: Cluster Autoscaler

**What version of the component are you using?**: V1.21.0 (us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.21.0)

Component version: 1.21.0

**What k8s version are you using (`kubectl version`)?**:  

<details><summary><code>kubectl version</code> Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: Cluster autoscaler to not terminate the pod. The pod that is running the process had a utilization which is pretty low i.e 0.008 but we want it to remain and not be terminated.  The pod is being run as a part of a Job. 

**What happened instead?**: When looking at the logs, Cluster Autoscaler does not even look at the annotation but simply looks at the utilization percentage and if its low then it kills the pod.

**How to reproduce it (as minimally and precisely as possible)**: Create a job template and annotate it and its pod with cluster-autoscaler.kubernetes.io/safe-to-evict": "false" annotation. The cpu utilization threshold can be set to 90% so it can bring down the pod even if the annotation is set.

**Anything else we need to know?**: Below is the configuration of the cluster autoscaler 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.21.0
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/dev-mllab
            - --balance-similar-node-groups
            - --skip-nodes-with-system-pods=false
            - --aws-use-static-instance-list=true
            - --scale-down-unneeded-time=5m
```

Below is the top few lines of the output of the job description command. We use the kubernetes python sdk and not a template and hence verified using `kubectl describe job` command
```
Name:           test-CA
Namespace:      team-mlops
Selector:       controller-uid=2ac4a704-476a-4dc0-9247-d0b305e08422
Labels:         department=A
                engineer=B
                environment=C
                task=H
Annotations:    cluster-autoscaler.kubernetes.io/safe-to-evict: false
Parallelism:    1
Completions:    1
Start Time:     Thu, 14 Apr 2022 12:21:44 -0500
Pods Statuses:  1 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:      controller-uid=2ac4a704-476a-4dc0-9247-d0b305e08422
                    department=A
                    engineer=B
                    experiment=C
  Annotations:      cluster-autoscaler.kubernetes.io/safe-to-evict: false
  .....
```
