### ISSUE TITLE
The vpa recommendation not update for a long time, about 14h

### ISSUE THREAD

**Issue by qhh0205** [kubernetes/autoscaler#4855]
Hi, guys, i hava create a vpa resource, and give the pod cpu load, so the vpa give the recommendations of cpu as expected, but after the pod restart about 14 hours ago, it seems that the vpa recommendations are no longer updated, although the actual value is far less than the recommended value. So, does the vpa recommender not work? or some bug here?

The following is the vpa recommnedation that not update for 14 hours:
```
...
status:
  conditions:
  - lastTransitionTime: "2022-04-24T12:43:42Z"
    status: "True"
    type: RecommendationProvided
  recommendation:
    containerRecommendations:
    - containerName: test-pod-affi-default
      lowerBound:
        cpu: 25m
        memory: "1238431657"
      target:
        cpu: 93m
        memory: "1312092764"
      uncappedTarget:
        cpu: 93m
        memory: "1312092764"
      upperBound:
        cpu: 101m
        memory: "1432930163"
```

The following is the pod actual resource usage(Obviously, there is a big difference between the recommended value and the actual value):
```
~# kubectl top pod -n wy-ext
NAME                                     CPU(cores)   MEMORY(bytes)
test-pod-affi-default-86c755fb7b-hxsn4   4m           984M

~# kubectl  get pod -n wy-ext
NAME                                     READY   STATUS    RESTARTS   AGE
test-pod-affi-default-86c755fb7b-hxsn4   1/1     Running   0          14h
```

The following is the pod CPU utilization(used/limit) trend:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/12775142/166866207-f4ff2712-6cc4-4341-9d38-62d20d02f2fa.png">

The following is the VerticalPodAutoscalerCheckpoint data:
```
...
spec:
  containerName: test-pod-affi-default
  vpaObjectName: test-pod-affi-vpa-default
status:
  cpuHistogram:
    bucketWeights:
      "0": 10000
      "1": 94
      "2": 5
      "6": 5412
      "7": 10
      "19": 10
    referenceTimestamp: "2022-05-05T00:00:00Z"
    totalWeight: 240.61163327498286
  firstSampleStart: "2022-04-24T08:04:42Z"
  lastSampleStart: "2022-05-05T05:05:42Z"
  lastUpdateTime: "2022-05-05T05:05:43Z"
  memoryHistogram:
    bucketWeights:
      "37": 3359
      "38": 10000
    referenceTimestamp: "2022-05-06T00:00:00Z"
    totalWeight: 1.0934615917825656
  totalSamplesCount: 15662
  version: v3
```
