### ISSUE TITLE
Only one container policy used for recommendation

### ISSUE THREAD

**Issue by vsevel** [kubernetes/autoscaler#4861]
**Which component are you using?**:

`vertical-pod-autoscaler`

**What version of the component are you using?**:

```
I0503 08:29:34.972158       1 main.go:15] Version: vertical-pod-autoscaler-operator v4.8.0-202111041632.p0.git.ef8ad45.assembly.stream-dirty

I0503 08:29:47.410096       1 main.go:76] Vertical Pod Autoscaler 0.9.0 Admission Controller

I0427 15:50:24.492768       1 main.go:75] Vertical Pod Autoscaler 0.9.0 Updater

I0506 08:49:41.974041       1 main.go:71] Vertical Pod Autoscaler 0.9.0 Recommender
```

**What k8s version are you using (`kubectl version`)?**:

Running on OpenShift `4.8` / Kubernetes `1.21` 

```
$ kubectl version


Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8+ee73ea2", GitCommit:"f7310cc5b1c14454dcd067838ca8407e9da13a26", GitTreeState:"clean", BuildDate:"2022-03-10T05:52:32Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What environment is this in?**:

On-premise

**What did you expect to happen?**:

I am using this definition:

```
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: container-advisory-facade-jvm
        controlledResources:
          - memory
        controlledValues: RequestsOnly
        mode: Auto
      - containerName: container-advisory-facade-jvm
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
        mode: Auto
```

I am expecting a recommendation provided for both container policies.

**What happened instead?**:

Recommendation provided only for memory:

```
status:
  conditions:
    - lastTransitionTime: '2022-05-05T09:25:34Z'
      status: 'True'
      type: RecommendationProvided
  recommendation:
    containerRecommendations:
      - containerName: container-advisory-facade-jvm
        lowerBound:
          memory: '323371511'
        target:
          memory: '351198544'
        uncappedTarget:
          memory: '351198544'
        upperBound:
          memory: '433137284'
```

I have seen situations where only cpu was provided.

**How to reproduce it (as minimally and precisely as possible)**:

Use the above spec. Check the status of the object after its gets updated.

**Anything else we need to know?**:

The only way we got it to work was to use a single policy with 2 controlled resources:

```
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: container-advisory-facade-jvm
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
        mode: Auto
```

then we get:

```
status:
  conditions:
    - lastTransitionTime: '2022-05-05T09:25:34Z'
      status: 'True'
      type: RecommendationProvided
  recommendation:
    containerRecommendations:
      - containerName: container-advisory-facade-jvm
        lowerBound:
          cpu: 25m
          memory: '323371584'
        target:
          cpu: 25m
          memory: '351198544'
        uncappedTarget:
          cpu: 25m
          memory: '351198544'
        upperBound:
          cpu: 28m
          memory: '433097475'
```

This is not ideal for us, because sometimes we want memory to be recommended by not applied. So we would like to express:

```
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: container-advisory-facade-jvm
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
        mode: Auto
      - containerName: container-advisory-facade-jvm
        controlledResources:
          - memory
        controlledValues: RequestsOnly
        mode: Off
```

And as a result we would like `containerRecommendations` for both cpu and memory, but only apply the `cpu` recommendation.
