### ISSUE TITLE
targetRef field misbehaviour

### ISSUE THREAD

**Issue by rafaeljesus** [kubernetes/autoscaler#4891]
**Which component are you using?**:

VPA in GKE

**What version of the component are you using?**:

Component version: GKE v1.21.10-gke.2000

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-dispatcher", GitCommit:"2a8027f41d28b788b001389f3091c245cd0a9a60", GitTreeState:"clean", BuildDate:"2022-01-21T20:31:13Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:

GKE

**What did you expect to happen?**:

I have two stateful sets and one vpa for each:

<details><summary>vpa0</summary>
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sts0
  labels:
    app: sts
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       sts0
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1 
  resourcePolicy:
    containerPolicies:
      - containerName: nginx
        mode: "Auto"
</details>

<details><summary>sts0</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts0
  labels:
    app: sts
spec:
  selector:
    matchLabels:
      app: sts
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: logs
          mountPath: /root/logs
        - name: www
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: "1"
            memory: 128Mi
          limits:
            cpu: "3"
            memory: 128Mi
      volumes:
        - name: logs
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: resizable-balanced
      resources:
        requests:
          storage: 512Mi
```
</details>

<details><summary>vpa1</summary>
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sts1
  labels:
    app: sts
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       sts1
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1 
  resourcePolicy:
    containerPolicies:
      - containerName: nginx
        mode: "Auto"
</details>

<details><summary>sts1</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts1
  labels:
    app: sts
spec:
  selector:
    matchLabels:
      app: sts
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: logs
          mountPath: /root/logs
        - name: www
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: "1"
            memory: 128Mi
          limits:
            cpu: "3"
            memory: 128Mi
      volumes:
        - name: logs
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: resizable-balanced
      resources:
        requests:
          storage: 512Mi
```
</details>

I was expecting`vpa0` to apply resources recommendations to `sts0`, and `vpa1` to `sts1`

**What happened instead?**:

But I have noticed both `sts0` and `sts1` were being updated by `vpa1`, and the `vpa0` was not applying any recommendations to `sts0`

I could make it work by adding selector labels that differentiate one stateful set from another:

`sts0`
```yaml
spec:
  selector:
    matchLabels:
      app: sts
      shard_id: "0"
```

`sts1`
```yaml
spec:
  selector:
    matchLabels:
      app: sts
      shard_id: "1"
```

I think this is why https://github.com/kubernetes/autoscaler/blob/e661d61c0861ed61fa89242a45a8dc4b0caca395/vertical-pod-autoscaler/pkg/target/fetcher.go#L162
