### ISSUE TITLE
VPA Initial mode does not set memory request according to recommended values

### ISSUE THREAD

**Issue by masterphenix** [kubernetes/autoscaler#4994]
**Which component are you using?**: vertical-pod-autoscaler

**What version of the component are you using?**: 0.10.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"8211ae4d6757c3fedc53cd740d163ef65287276a", GitTreeState:"clean", BuildDate:"2022-03-31T20:28:03Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**: AKS cluster on Azure

**What did you expect to happen?**:

I have a deployment with the following resources set in the container template (there is only one container):
```
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 60m
            memory: 600Mi
```
In the same namespace, there is a limitRange, with the following configuration:
```
  spec:
    limits:
    - default:
        cpu: "2"
        memory: 2Gi
      defaultRequest:
        cpu: 60m
        memory: 32Mi
      max:
        cpu: "2"
        memory: 4Gi
      type: Container
```

I defined a VPA targetting that deployment, in Initial update mode, with the following policy:
```
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
```

Both recommender and admission-controller pods are running, and reporting no errors.
The VPA recommends the following:
```
  recommendation:
    containerRecommendations:
    - containerName: testpod
      lowerBound:
        cpu: 15m
        memory: "2538099186"
      target:
        cpu: 23m
        memory: "4743403291"
      uncappedTarget:
        cpu: 23m
        memory: "4743403291"
      upperBound:
        cpu: 116m
        memory: "6248599546"
```

First issue here is that memory target is beyond the 4Gi maximum defined in the limitRange ; it should be **4294967296**.

Then, when I delete pod, and a new pod pops up again, it's ressources are set like this:
```
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 23m
        memory: 600Mi
```

CPU request is set correctly according to VPA target recommendation ; however, memory target seems to be capped to the request that is defined in the Deployment resource ; it should be set to the limitRange maximum, which is 4Gi, and not 600Mi.

**What happened instead?**:

Memory request value set in the pod does not match VPA recommendation (which does not take limitRange into account).

**Anything else we need to know?**:

Recommender config:
```
      - args:
        - --pod-recommendation-min-cpu-millicores=15
        - --pod-recommendation-min-memory-mb=30
        - --v=4
        image: k8s.gcr.io/autoscaling/vpa-recommender:0.10.0
```

Also, the following annotations are applied on the pod:
```
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu limit for container testpod'
    vpaObservedContainers: testpod
    vpaUpdates: 'Pod resources updated by testpod: container 0: memory capped
      to fit Max in container LimitRange, cpu request, memory request'
```
