### ISSUE TITLE
hostname topology spread constraint/anti-affinity causes mass overscaling since CA v1.21.1

### ISSUE THREAD

**Issue by matthewstokes01** [kubernetes/autoscaler#5019]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:

Component version: cluster-autoscaler v1.21.1 / image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f17
[cluster-autoscaler-overscaling-issue.log](https://github.com/kubernetes/autoscaler/files/9094525/cluster-autoscaler-overscaling-issue.log)
50a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**: AWS EKS, self managed auto scaling groups

**What did you expect to happen?**: I expected cluster autoscaler to provision enough nodes to evenly distribute 200 pods. With the instance size of t3.medium this should have resulted in around 17 pods per node, so around 12 instances.

**What happened instead?**: The cluster autoscaler notices the ~170 pods that are pending and initially estimates it needs between 17 nodes, it then changes the ASG desired size to 17. A few moments later, it loops through again and see the pending pods, and estimates it needs 171 nodes. In the time it takes to launch 171 nodes, the initial 17 nodes have been created and all the pods are now scheduled as expected. CA now needs to downscale the cluster from 171 nodes to around 17.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create an EKS cluster running EKS v1.22
2) Install cluster-autoscaler v1.21.1 or higher
3) Create an ASG across 3 AZ's, and set the values to:
```
Instance Type: t3.medium
Desired Capacity: 3
Minimum Capacity: 3
Maximum Capacity: 300
```
4) Create a deployment such as this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-pause
  name: demo-pause
  namespace: demo-pause
spec:
  replicas: 0
  selector:
    matchLabels:
      app: demo-pause
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 5%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-pause
      name: demo-pause
      namespace: demo-pause
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.1
        name: demo-pause
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: demo-pause
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
```
5) Scale the deployment to 200 replicas: `kubectl scale deployment demo-pause -n demo-pause --replicas 200`
6) Observe cluster-autoscaler logs and the desired instance count on the AWS ASG, it will go initially from 3 -> either 17 or 19 to eventually 194 instances

**Anything else we need to know?**:
This wasn't an issue in V1.21.0, and in V1.21.1 there was a change to the `BinpackingNodeEstimator` component which seems related.

**The cluster-autoscaler logs are attached**
