### ISSUE TITLE
Support in-place resource update feature for VPA

### ISSUE THREAD

**Issue by wangchen615** [kubernetes/autoscaler#5046]
**Which component are you using?**: Vertical Pod Autoscaler

**Is your feature request designed to solve a problem? If so, describe the problem this feature should solve.**:
In Kubernetes 1.25, the in-place resource update feature would be available in alpha. Any pods with this feature enabled would have a field to specify the restarting policies as the following. Pods controlled by VPA with a `NoRestart` policy should not be evicted by the VPA updater. Instead, it should be patched with the new recommended request directly.

```
apiVersion: v1
kind: Pod
metadata:
  name: 1pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
    resizePolicy:
    - resourceName: cpu
      policy: NoRestart
    - resourceName: memory
      policy: NoRestart
```

**Describe the solution you'd like.**:
In the VPA updater, whenever existing logic decides to evict the pod, we should add a check on the pod spec to determine if `NoRestart` policy is enabled. If so, a patch request should be sent via updater directly to the pod without evicting it.

An example patch command looks like this:
```
		patchCommand := fmt.Sprintf(`{
			"spec":{
					"containers":[
						{
							"name":"containerName", 
							"resources":{"requests":"cpu":%s},"limits":{"cpu":%s}}
						}]
					}
			}`, resizeCPUValStr)

                 testPod, pErr := f.ClientSet.CoreV1().Pods(testPod.Namespace).Patch(context.TODO(),
			testPod.Name, types.StrategicMergePatchType, []byte(patchCommand), metav1.PatchOptions{})
```

**Describe any alternative solutions you've considered.**: None

**Additional context.**:  The place where the VPA updater evicts the pod is here: https://github.com/kubernetes/autoscaler/blob/fc0666c88e325ea32ceabcfa1f834f5e39e265a3/vertical-pod-autoscaler/pkg/updater/logic/updater.go#L196

**Comment by voelzmo** [comment]
Just to document a caveat regarding the capping of requests here, so we keep this in mind:
* [The Recommender](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.10.0/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L109) only caps according to [`minAllowed` and `maxAllowed`](https://github.com/kubernetes/autoscaler/blob/6d1a1514af4406bb967ae6f50e9589f7d41f9af8/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L191-L198)
* [The admission-controller](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.10.0/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L87) is currently responsible for [capping to the existing limit in case `controlledValues: RequestsOnly` is set or to an existing `LimitRange` in the namespace](https://github.com/kubernetes/autoscaler/blob/6d1a1514af4406bb967ae6f50e9589f7d41f9af8/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L103-L140)

We probably need to move the limit-capping logic to a different place, so we don't have different behavior for the eviction and in-place update case.

**Comment by jbartosik** [comment]
I'm writing this down and I'll send a PR when it's ready.

I was thinking about something a little different:
- Add actuation modes so we have `Recreate` (exists already), `InPlace`, `InPlaceWithFallbackToEvict`
- we might want controls for when to fall back to deleting pods
- we might want to limit how frequently we update in place

I heard that some time ago scaling down in place could cause problems, so we might want to allow scalign up in place but evicting to scale down.

I didn't think about per-resource configuration (yet).

**Comment by voelzmo** [comment]
> Add actuation modes so we have Recreate (exists already), InPlace, InPlaceWithFallbackToEvict

Can you elaborate a bit on your thinking why we need additional actuation modes? In theory, these settings are already configured on the Pod itself with 
```
resizePolicy:
    - resourceName: cpu
      policy: NoRestart
    - resourceName: memory
      policy: NoRestart
```
