### ISSUE TITLE
oci provider is not included in k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.1 image

### ISSUE THREAD

**Issue by Noksa** [kubernetes/autoscaler#5085]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
1.23.1

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```
</pre></details>

**What environment is this in?**:
OCI self-managed k8s 1.24

**What did you expect to happen?**:
autoscaler works almost out of the box

**What happened instead?**:
autoscaler says 'unknown cloud provider oci' when it starts and quits

**How to reproduce it (as minimally and precisely as possible)**:
Run this manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cluster-autoscaler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cluster-autoscaler
    spec:
      containers:
      - command:
        - ./cluster-autoscaler
        - --v=5
        - --logtostderr=true
        - --cloud-provider=oci
        - --nodes=1:10:ocid1.instancepool.oc1.iad.aaaaaaaaaaaaaaaaaaaaaa
        - --scale-down-delay-after-add=10m
        - --scale-down-unneeded-time=10m
        - --namespace=kube-system
        env:
        - name: OCI_USE_INSTANCE_PRINCIPAL
          value: "true"
        - name: OCI_REGION
          value: us-ashburn-1
        image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.1
        imagePullPolicy: Always
        name: cluster-autoscaler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cluster-autoscaler
      serviceAccountName: cluster-autoscaler
      terminationGracePeriodSeconds: 30

```

**Anything else we need to know?**:
If I rebuild the autoscaler myself and build an image - it works as expected, 'oci' provider is included in my image.
