### ISSUE TITLE
[cluster-autoscaler v.1.23.1] unable to find instance type within launch template

### ISSUE THREAD

**Issue by TekTimmy** [kubernetes/autoscaler#5173]
**Which component are you using?**:
Autoscaler on AWS EKS

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Until today we are using three different node groups in our EKS on AWS: small, medium and large. The groups have different CPU and memory using different ec2 spot instances. The number of groups will grow in the future and  due to the hardcoded overrides in the AWS launch template we have to create one CloudFormation template for each group, also they have to be maintained from time to time to include new instance types and remove outdated ones.

**Describe the solution you'd like.**:
We want to remove the hardcoded ec2 instance types from our cloud formation template. So we can have one cloud formation template where the instance requirements (CPU, memory etc) are parameters of the cloud formation template. The AWS launch template can select ec2 instance types dynamically based on the provided `InstanceRequirements` but the autoscaler ends up with error message:
> E0907 15:19:43.152989       1 aws_wrapper.go:301] Failed to query launch tempate NodeLaunchAzThree_vT7bNiGwl8Ri: unable to find instance type within launch template

**Describe any alternative solutions you've considered.**:
The approach that we had and would like to avoid is hardcode the ec2 instance types into the cloud formation script causing one file per instance group (same CPU / Memory).

**Additional context.**:
Here is the shortened version of our cloud formation script (only one AvailibilityZone) that deploys a EKS node group:
```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  The Amazon AWS EKS worker nodes configuration.
Parameters:
  VpcNetworkId:
    Type: AWS::EC2::VPC::Id
    Description: >-
      The VPC of the worker nodes.
  ClusterName:
    Type: String
    AllowedPattern: "^\\S+$"
    Description: >-
      The cluster name.
  ClusterControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: >-
      The security group of the cluster control plane.
  VpcSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: >-
      The subnets where the worker nodes can be created.
  NodeKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: eks
    Description: >-
      The EC2 key pair to allow SSH access to the instances.
  NodeImageId:
    Type: AWS::EC2::Image::Id
    Description: >-
      See
      https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
      for a list of AWS AMIs available for EKS.
  NodeInstanceRequirementsMinMemory:
    Type: Number
    Default: 8192
    MinValue: 4096
    Description: >-
      The minimal memory in MiB the nodes must have.
  NodeInstanceRequirementsVCpus:
    Type: Number
    Default: 4
    MinValue: 2
    Description: >-
      The number of vCpus the nodes must have.
Resources:
  NodeProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - eks-node-instance-role

  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for all nodes in the cluster
      VpcId: !Ref VpcNetworkId
  NodeSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref NodeSecurityGroup
      SourceSecurityGroupId: !Ref NodeSecurityGroup
      IpProtocol: -1
      FromPort: 0
      ToPort: 65535
  NodeSecurityGroupFromClusterControlPlaneIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref NodeSecurityGroup
      SourceSecurityGroupId:
      IpProtocol: tcp
      FromPort: 1025
      ToPort: 65535
  ClusterControlPlaneEgressToNodeSecurityGroup:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: >-
        Allow the cluster control plane to communicate with the kubelets
        and pods running on the worker nodes.
      GroupId: !Ref ClusterControlPlaneSecurityGroup
      DestinationSecurityGroupId: !Ref NodeSecurityGroup
      IpProtocol: tcp
      FromPort: 1025
      ToPort: 65535
  NodeSecurityGroupFromClusterControlPlaneOn443Ingress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: >-
        Allow pods running extension API servers on port 443 to receive
        communication from cluster control plane.
      GroupId: !Ref NodeSecurityGroup
      SourceSecurityGroupId: !Ref ClusterControlPlaneSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
  ClusterControlPlaneEgressToNodeSecurityGroupOn443:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: >-
        Allow the cluster control plane to communicate with pods running
        extension API servers on port 443.
      GroupId: !Ref ClusterControlPlaneSecurityGroup
      DestinationSecurityGroupId: !Ref NodeSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
  ClusterControlPlaneSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: >-
        Allow pods to communicate with the cluster API server.
      GroupId: !Ref ClusterControlPlaneSecurityGroup
      SourceSecurityGroupId: !Ref NodeSecurityGroup
      IpProtocol: tcp
      ToPort: 443
      FromPort: 443

  NodeAsgAzOne:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 0
      MaxSize: 100
      MinSize: 0
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandAllocationStrategy: lowest-price
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: lowest-price
          SpotInstancePools: 20
          SpotMaxPrice: 0.6
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref NodeLaunchAzOne
            Version: !GetAtt NodeLaunchAzOne.LatestVersionNumber
      VPCZoneIdentifier: !Ref VpcSubnetId
      Tags:
        - Key: k8s.io/cluster-autoscaler/enabled
          Value: ''
          PropagateAtLaunch: false
        - Key: !Sub k8s.io/cluster-autoscaler/${ClusterName}
          Value: ''
          PropagateAtLaunch: false
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: false
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: 0
        MinSuccessfulInstancesPercent: 100
        PauseTime: PT5M
        WaitOnResourceSignals: true

  NodeLaunchAzOne:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref NodeImageId
        InstanceRequirements:
          AcceleratorCount:
            Min: 0
            Max: 0
          CpuManufacturers:
            - intel
          MemoryMiB:
            Min: !Ref NodeInstanceRequirementsMinMemory
          VCpuCount:
            Min: !Ref NodeInstanceRequirementsVCpus
            Max: !Ref NodeInstanceRequirementsVCpus
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
              VolumeSize: 50
              VolumeType: gp2
        EbsOptimized: true
        IamInstanceProfile:
          Arn: !GetAtt NodeProfile.Arn
        InstanceInitiatedShutdownBehavior: terminate
        KeyName: !Ref NodeKeyPairName
        Monitoring:
          Enabled: true
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeleteOnTermination: true
            DeviceIndex: 0
            Groups:
              - !GetAtt NodeSecurityGroup.GroupId
            SubnetId: !Ref VpcSubnetId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${AWS::StackName}-az1
          - ResourceType: instance
            Tags:
              - Key: !Sub kubernetes.io/cluster/${ClusterName}
                Value: owned
        UserData:
          Fn::Base64:
            !Sub |
            #!/bin/bash
            set -o xtrace
            /etc/eks/bootstrap.sh ${ClusterName} ${NodeBootstrapArgs}
            /opt/aws/bin/cfn-signal --exit-code $? \
                    --stack  ${AWS::StackName} \
                    --resource NodeAsgAzOne  \
                    --region ${AWS::Region}

```
