### ISSUE TITLE
Use environment varibles in the Cluster Autoscaler

### ISSUE THREAD

**Issue by mtavaresmedeiros** [kubernetes/autoscaler#5188]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
Cluster Autoscaler: 1.21.1
Helm Chart Version: 9.13.1

Component version:
v1.21.14-eks-6d3986b

<details><summary><code>kubectl version</code> Output</summary><br><pre>
 kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-13T19:07:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
EKS - AWS

**What did you expect to happen?**:
Use Environment Variables

**What happened instead?**:
Using environment variables doesn't work

**How to reproduce it (as minimally and precisely as possible)**:
Try to change environments variables:
--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/$EKS_CLUSTER_NAME

**Comment by TekTimmy** [comment]
this can't be a bug of the autoscaler from my perspective..
For me it works! We inject the configmap into the environment like this:
```yaml
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.1
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 600Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=$(IAC_CAS_LOG_LEVEL)
            - --cloud-provider=$(IAC_CAS_CLOUD_PROVIDER)
            - --skip-nodes-with-local-storage=$(IAC_CAS_SKIP_NODES_WITH_LOCAL_STORAGE)
            - --expander=$(IAC_CAS_EXPANDER)
            - --balance-similar-node-groups=$(IAC_CAS_BALANCE_SIMILAR_NODE_GROUPS)
            - --scale-down-enabled=$(IAC_CAS_SCALE_DOWN_ENABLED)
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/$(IAC_CLUSTER_NAME)
            - --scan-interval=$(IAC_CAS_SCAN_INTERVAL)
            - --skip-nodes-with-system-pods=$(IAC_CAS_SKIP_NODES_WITH_SYSTEM_PODS)
          envFrom:
            - configMapRef:
                name: iac-cluster-autoscaler
```
