### ISSUE TITLE
Vertical Pod autoscaling doesn't scale less than 255 Mi

### ISSUE THREAD

**Issue by superset1** [kubernetes/autoscaler#5242]
**Which component are you using?**: vertical-pod-autoscaler

**What version of the component are you using?**: 
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration

Component version:
**What k8s version are you using (`kubectl version`)?**:  
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.20.7
```
</pre></details>

**What environment is this in?**: 
prd, stage, dev

**What did you expect to happen?**: 
Scale less than 255Mi. Because kubectl top pod:
```
CPU(cores)   MEMORY(bytes)
26m          35Mi
```

**What happened instead?**:
```
  recommendation:
    containerRecommendations:
    - containerName: assembly-task-service
      lowerBound:
        cpu: 25m
        memory: 262144k
      target:
        cpu: 25m
        memory: "380258472"
      uncappedTarget:
        cpu: 25m
        memory: "380258472"
      upperBound:
        cpu: 25m
        memory: "418082068"
```

**How to reproduce it (as minimally and precisely as possible)**: apply vpa to any deploy

**Anything else we need to know?**: no
