### ISSUE TITLE
Scaling from 0 doesn't work for GPU nodes. Reasons: Insufficient nvidia.com/gpu

### ISSUE THREAD

**Issue by VitaliiBabii** [kubernetes/autoscaler#5278]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
1.22.3

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
```
serverVersion:
  buildDate: "2022-06-16T05:33:55Z"
  compiler: gc
  gitCommit: 5824e3251d294d324320db85bf63a53eb0767af2
  gitTreeState: clean
  gitVersion: v1.22.11
  goVersion: go1.16.15
  major: "1"
  minor: "22"
  platform: linux/amd64
```

</pre></details>

**What environment is this in?**:
We are using AWS EC2 instances to run kubernetes

For GPU we use instances g4dn.2xlarge and g4dn.4xlarge
```
  Kernel Version:             4.18.0-372.26.1.el8_6.x86_64
  OS Image:                   Rocky Linux 8.6 (Green Obsidian)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  cri-o://1.22.5
  Kubelet Version:            v1.22.11
  Kube-Proxy Version:         v1.22.11
```

**What did you expect to happen?**:
Cluster Autoscaler scales from 0 GPU Autoscaling Group when new pods request GPU.

**What happened instead?**:
Cluster Autoscaler do not trigger scale up from 0 nodes.

When there are 0 nodes in ASG and new pods created and requests GPU Cluster Autoscaler(CA) do not trigger scale up. 
In CA logs I can see message like 
`I1027 11:02:58.428887       1 scale_up.go:300] Pod cuda-vector-add can't be scheduled on 2.gpu-small.nodes.aws-us-east, predicate checking error: Insufficient nvidia.com/gpu; predicateName=NodeResourcesFit; reasons: Insufficient nvidia.com/gpu; debugInfo=`
After CA restart it starts to work as expected. But after some time CA again stops to scale from 0.
Looks like CA when ASG scaled to 0 at some point stops to see GPU resources.

**How to reproduce it (as minimally and precisely as possible)**:
When ASG scaled to 0 just try to run gpu pod like:

```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
  annotations:
    workload: nvidia-gpu
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1"
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=10.0"
      resources:
        limits:
          cpu: 8
          memory: 32Gi
          nvidia.com/gpu: 1
        requests:
          cpu: 4
          memory: 24Gi
          nvidia.com/gpu: 1
  nodeSelector:
    workload: walle-gpu-small
  tolerations:
  - effect: NoSchedule
    key: workload
    operator: Equal
    value: walle-gpu-small
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
```

ASG Labels like
```
k8s.io/cluster-autoscaler/node-template/label/nvidia.com/gpu: true
k8s.io/cluster-autoscaler/node-template/resources/nvidia.com/gpu: 1

```
doesn't work.
