### ISSUE TITLE
VPA admission controller should be able to use a standard cert-manager certificates

### ISSUE THREAD

**Issue by youwalther65** [kubernetes/autoscaler#5318]
**Which component are you using?**:
VPA admission webhook

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Currently VPA admission controller uses the [gencerts.sh ](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh) script for creating the vpa-tls-certs secret. This TLS secret contains 4 PEM files. Creating this file with cert-manager is not possible.

**Describe the solution you'd like.**:
VPA admission controller should be able to use a standard cert-manager certificate create with:

````yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-admission-cert
  namespace: kube-system
spec:
  commonName: vpa-webhook.kube-system.svc
  dnsNames:
    - vpa-webhook
    - vpa-webhook.kube-system
    - vpa-webhook.kube-system.svc
  duration: 10000h0m0s
  issuerRef:
...
  renewBefore: 9999h0m0s
  secretName: vpa-tls-certs
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: "RSA"
    size: 2048
````

**Describe any alternative solutions you've considered.**:

**Additional context.**:
