### ISSUE TITLE
AutoScaler not scheduling a pod on node group

### ISSUE THREAD

**Issue by paulcarlton-ww** [kubernetes/autoscaler#5319]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

v1.23.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

</pre></details>

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

Pod to be scheduled on node group

**What happened instead?**:

I1118 13:32:36.868201       1 scale_up.go:300] Pod podinfo-79c4469b46-jg6mc can't be scheduled on eks-test-one-app-two-ng-aac242cc-8048-1b87-0493-dc987d8aebb8, predicate checking error: node(s) didn't match Pod's node affinity/selector; predicateName=NodeAffinity; reasons: node(s) didn't match Pod's node affinity/selector; debugInfo=

**How to reproduce it (as minimally and precisely as possible)**:

Deploy pod with spec

```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - app-two
```

Configure node group with label

```yaml
  labels:
    role: app-two
```
