### ISSUE TITLE
Info logs are showing up after setting verbosity of logs to 0 and stderrthreshold to error

### ISSUE THREAD

**Issue by MarkArts** [kubernetes/autoscaler#5404]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
Helm chart version: 9.21.1
deployed autoscaler image tag: v1.23.0

Component version:
**What k8s version are you using (`kubectl version`)?**:

<details>
  <summary>
    <code>kubectl version</code>
    </summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS EKS managed k8s.

**What did you expect to happen?**:
After settings the log verbosity to 0 (or 1) in the helm values:
```
  extraArgs:
    v: 0
```
I would expect only error and or fatal logs to apear.

**What happened instead?**:
The following logs are in the output of the autoscaler:
```
I0109 14:41:41.017300       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache                                                                                                                                          

I0109 14:41:41.017358       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 11.05µs
```

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the v9.21.1 helm chart of autoscaler and check the output of the autoscaler pod

**Anything else we need to know?**:
Seems like the code correctly logs the `Start refreshing....` lines as info:
https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/cluster-autoscaler/clusterstate/utils/node_instances_cache.go#L156 

The container spec (including the verbosity option) deployed by the helm chart:
```yml
spec:
  containers:
  - command:
    - ./cluster-autoscaler
    - --cloud-provider=aws
    - --namespace=kube-system
    - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/euc1-testing
    - --logtostderr=true
    - --stderrthreshold=info
    - --v=0
    env: {redacted}
    image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health-check
        port: 8085
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: aws-cluster-autoscaler
    ports:
    - containerPort: 8085
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:  {redacted}
 ```
 
 I also tried setting `stderrthreshold` to `error` or `ERROR` but this had no effect and the README doesn't mention it's needed:
 https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-increase-the-information-that-the-ca-is-logging
