### ISSUE TITLE
Cluster Autoscalse (AWS) stuck in CrashLoopBackOff but works after recreating Node Group

### ISSUE THREAD

**Issue by dgard1981** [kubernetes/autoscaler#5429]
**Which component are you using?**:

helm charts

**What version of the component are you using?**:

Component version: 9.21.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-eks-ffeb93d", GitCommit:"abb98ec0631dfe573ec5eae40dc48fd8f2017424", GitTreeState:"clean", BuildDate:"2022-11-29T18:45:03Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:

AWS

**What did you expect to happen?**:

I expected to see the `cluster-autoscaler` pod start and run successfully.

**What happened instead?**:

The `cluster-autoscaler` pod was in a `CrashLoopBackOff` state. Every attempted restart was producing the following error.

```
F0119 10:07:08.649471       1 aws_cloud_provider.go:369] Failed to generate AWS EC2 Instance Types: NoCredentialProviders: no valid providers in chain. Deprecated.
```

To try and solve the issue, I deleted and recreated the Node Group, which to my surprise worked. I use CloudFormation for this, so the Node Group configuration was identical.

I do have the full stack trace, but it's too long to be allowed in this comment.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Although I've now got the `cluster-autoscaler` working, I'm keen to understand why it wasn't working in the first instance.

The IAM Role used by the Node Group is created independently of the Node Group and was not changed when I deleted and recreated the Node Group.

```yaml
  EksNodeGroupRole:
    # checkov:skip=CKV_AWS_111:Ensure IAM policies does not allow write access without constraints
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Allow the Kubernetes nodes to manage AWS resources.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
      Policies:
        - PolicyName: CluserAutoscaler
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeAutoScalingInstances
                  - autoscaling:DescribeInstances
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:DescribeTags
                  - autoscaling:SetDesiredCapacity
                  - autoscaling:TerminateInstanceInAutoScalingGroup
                  - ec2:DescribeLaunchTemplateVersions
                  - ec2:DescribeInstanceTypes
                Effect: Allow
                Resource: '*'
```
