### ISSUE TITLE
Rancher: Custom CA for cloud config

### ISSUE THREAD

**Issue by bennysp** [kubernetes/autoscaler#5438]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.26.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2+rke2r1", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T16:04:41Z", GoVersion:"go1.18.3b7", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:

N/A

**What happened instead?**:

`F0121 21:22:16.799439 1 rancher_provider.go:69] failed to create rancher cloud provider: failed to get ServerGroups: Get "https://rancher.domain.com/api?timeout=32s": x509: certificate signed by unknown authority `

**How to reproduce it (as minimally and precisely as possible)**:

Deploy rancher with custom CA for the Management cluster.

**Anything else we need to know?**:

My Rancher cluster is using a custom CA. I believe the cloud config may need an option to specify the CA (like in a kubeconfig file).

**Comment by atsai1220** [comment]
You can mount the CA via the Helm values
``` yaml
extraVolumes:
- name: ssl-certs
  configMap:
    name: your-ca
extraVolumeMounts:
- name: ssl-certs
  mountPath: /etc/ssl/certs
  readOnly: true
```

With this ConfigMap as the same namespace as the autoscaler.
``` yaml
apiVersion: v1
data:
  ca-certificates.crt: |
    -----BEGIN CERTIFICATE-----
...
...
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: your-ca
```
