### ISSUE TITLE
Cluster Autoscaler Pods(Deployed on Fargate) going to CrashLoopBackoff state until Node Group is created

### ISSUE THREAD

**Issue by sujith1594** [kubernetes/autoscaler#5449]
**Which component are you using?**: Helm charts, cluster-autoscaler

**What version of the component are you using?**: 

Component version: Helm chart[9.21.0) , image tag: v1.21.0

**What k8s version are you using (`kubectl version`)?**:

`1.21`
$ kubectl version

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-ffeb93d", GitCommit:"f76e2b475d1433cdb6bd546e9e8f129fde938fb7", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What environment is this in?**: AWS

**What did you expect to happen?**: cluster autoscaler  should be in Running State when depoyed on Fargate without Managed Node Group. 

**What happened instead?**: Cluster autoscaler pod is going into crashloopbackoff state until NodeGroup is created. I'm trying to deploy cluster-autoscaler on Fargate. I'm getting this issue when I try to deploy Helm chart or cluster autoscaler deployment files

**How to reproduce it (as minimally and precisely as possible)**:

IAM Policy
```
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Action" : [
          "autoscaling:DescribeAutoScalingGroups",
          "autoscaling:DescribeAutoScalingInstances",
          "autoscaling:DescribeInstances",
          "autoscaling:DescribeLaunchConfigurations",
          "autoscaling:DescribeTags",
          "autoscaling:SetDesiredCapacity",
          "autoscaling:TerminateInstanceInAutoScalingGroup",
          "ec2:DescribeLaunchTemplateVersions",
          "ec2:DescribeInstanceTypes",
          "eks:DescribeNodegroup"
        ],
        "Resource" : "*",
        "Effect" : "Allow"
      }  
    ]
```
Helm Values
```
rbac:
  serviceAccount:
    name: <name to sa>
    annotations:
      eks.amazonaws.com/role-arn: <IAM_ROLE_ARN>
autoDiscovery:
  clusterName: <cluster_name>
awsRegion: us-east-2
image:
  tag: v1.21.0
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
```

**Anything else we need to know?**:

```
 Error fetching https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-2/index.json skipping...
F0126 15:15:35.326957       1 aws_cloud_provider.go:358] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type
```
