### ISSUE TITLE
updateMode: Initial not applied on re-deployment

### ISSUE THREAD

**Issue by jseletz-rave** [kubernetes/autoscaler#5452]
I'm trying to use the VPA with the `Initial` update mode.  I'm seeing the following behavior and trying to understand if I am using this feature incorrectly, if it's not applicable to my use case, or it there is an issue:

1. Deploy a Helm chart with Pod for a Tomcat web application, no VPA.  
2. Undeploy the Helm release (`helm delete`) 
3. Deploy the Helm chart with a VPA added, configured with `updateMode: Initial`
4. Note timing issue - VPA resource is created, but has no recommendation. Pod is created at the same time with the resource requests configured in the Helm chart.  The VPA then updates with the recommendations, but pod is not using them.
5. Manually restart the pod (delete the pod so it is automatically recreated), then the VPA recommendations are automatically applied to the pod.
6. I have tested with the VPA resource configured with a Helm pre-install hook.  This does not resolve the timing issue.  I did notice that when undeploying the Helm release, the VPA is not deleted (as expected), but with the pod removed, the VPA's pod selector doesn't find it anymore, and the recommendations are removed from the VPA.  So next deployment does not apply them on pod creation, as the VPA doesn't get updated with recommendations until after the pod is created.
7. Deploying with `updateMode: Auto` shows a similar behavior - pod and vpa are created, pod has configured resource requests (not from VPA), VPA is updated with recommendations, and then a few seconds later the pod is evicted and re-deployed by the updater with the recommended resources.

Seems like a chicken-egg timing problem - even if the VPA exists before the pod is created, the VPA isn't updated with recommendations until the pod is created, and then it's too late for the initial settings to be applied.  How is this expected to work?

AWS EKS 1.22

My VPA configuration:
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: myApp
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
          - memory
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: myApp
  updatePolicy:
    updateMode: Initial
```
