### ISSUE TITLE
clusterapi: Cluster Autoscaler destroys healthy nodes when processing old unregistered nodes when multiple machinesets exist

### ISSUE THREAD

**Issue by cnmcavoy** [kubernetes/autoscaler#5465]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
v1.2.4

Component version:

**What k8s version are you using (`kubectl version`)?**:

```
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.3.428+425ff1c8e2d298-dirty", GitCommit:"425ff1c8e2d29874926abb7da37641cf785c4ff3", GitTreeState:"dirty", BuildDate:"2022-03-10T21:18:29Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What environment is this in?**:
AWS

**What did you expect to happen?**:
The cluster autoscaler should manage machine deployments and understand how to manage scale up and scale down behavior when a machine deployment is in the midst of a rollout. When a machine deployment is in a rollout, multiple machinesets exist with non-zero replica counts.

When the cluster autoscaler is managing machine deployments that are in undergoing a rollout (they own multiple machinesets that have non-zero replicas) and the provisioning nodes are not able to join the cluster in a timely manner, the cluster autoscaler detects these as "long unregistered" nodes. I expected the cluster autoscaler to correctly remove these long unregistered nodes and stop considering them for pod placement, and scale up another node group.

**What happened instead?**:
What we observed was that when the cluster autoscaler is managing machine deployments that are in undergoing a rollout (they own multiple machinesets that have non-zero replicas) and the provisioning nodes are not able to join the cluster in a timely manner, the cluster autoscaler detects these as "long unregistered" nodes. When it determines that these nodes have not joined the cluster after the max provision time has been exceeded, the cluster autoscaler marks these machines for deletion by setting an annotation and decreases the replica count of the machine deployment for the nodegroup.

Scaling the machine deployment at this point is tricky - scale up on the replica count causes the newest machineset desired replicas to increase. Scale down on the machine deployment replica count causes the oldest machineset to shrink the desired replicas. I think this is the core confusion for the cluster autoscaler.

So when the replica count for the machine deployment is decreased, the CAPI controller takes over. When the machine deployment replica count is decreased and multiple machinesets exist with non-zero replicas, the oldest machineset has a replica removed. This is not the machine that was stuck provisioning, because it was part of the new machineset that did not successfully finish coming up. So this causes a healthy node in the old machineset to be scaled down, in addition to the old provisioning machine that was annotated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a machine deployment with 2 replicas, backed by an AWSMachineTemplate and KubeadmConfigTemplate for the infrastructure and a no-op workload to occupy the each of the 2 nodes resources in a cluster with the cluster autoscaler configured
2. Wait for the node group to come up with 2 healthy nodes and the no-op workload to become ready
3. Configure a new KubeadmConfigTemplate that won't join the cluster (e.g `preKubeadmCommands: ['sleep infinity']`) and update the machine deployment to begin a rollout
4. Observe that the cluster autoscaler marks the stuck "provisioned" machines for deletion with the annotation and scales the node group down _even though there is no place for the pods to go_.

A brief gist which shows the sort of configuration we used to reproduce this: https://gist.github.com/cnmcavoy/364cb3020017c22fc63c75540cf58923 

**Anything else we need to know?**:
We first encountered this running a fork of the v1.26 cluster autoscaler, which we were running to use the scale from zero feature set. We re-tested on the official tagged v1.24 release and reproduced it there as well.

**Comment by elmiko** [comment]
great report, thank you for the depth of explanation.

> The cluster autoscaler should manage machine deployments and understand how to manage scale up and scale down behavior when a machine deployment is in the midst of a rollout.

the capi autoscaler provider is very dumb about machinesets and machinedeployments, essentially treating them the same. we could probably add more logic to help in distinguish the behaviors between the two types.

**Comment by elmiko** [comment]
afaik this is still a work in progress

/remove-lifecycle stale

**Comment by elmiko** [comment]
@wmgroot thanks for raising the concerns again. i tend to agree that this is a potential problem waiting to hit users, especially users with large clusters.

i will raise the issue about pr #5538 at an upcoming SIG meeting, it seems like we are just waiting on a comment from @MaciekPytel . i'm generally ok with the solution there.

**Comment by elmiko** [comment]
the related PR got closed as we took too long to approve it, i think this bug is worth keeping open though, perhaps someone can pickup @wmgroot 's work and carry it through.

/remove-lifecycle stale

**Comment by elmiko** [comment]
not sure where this is at, but i do think it's important

/remove-lifecycle stale

**Comment by songminglong** [comment]
In fact, this is a problem that has always existed in cluster autoscaler, not only in cluster-api provider, but also in AWS/Alicloud provider, etc. Cluster autoscaler does not directly manage instances, but uses nodegroup as an intermediary to indirectly operate instances by adjusting nodegroup replicas, which will cause the instance to be scaled down to a normal instance.

eg: https://github.com/kubernetes/autoscaler/issues/6795

**Comment by elmiko** [comment]
thank for the comment and link @songminglong !

**Comment by elmiko** [comment]
i believe this is still happening, but i have not had time to investigate further.

/remove-lifecycle stale

**Comment by mattpopa** [comment]
This is very serious, and makes no sense in using the cluster autoscaler on AWS EKS anymore. It seems to be scaling down by X an ASG and AWS ASG picks a random healthy node to kill.

For example, cluster-autoscaler sets the taints for deletion to a node, and then the ASG kills a completely different node that it picks:

```
At 2025-01-24T15:32:30Z an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 11 to 10. At 2025-01-24T15:32:30Z instance i-02837280022e99xyz was selected for termination.
```

in cluster-autoscaler logs:

```
I0124 15:51:13.298754 1 static_autoscaler.go:432] 1 unregistered nodes present
W0124 15:51:13.298783 1 static_autoscaler.go:760] No node group for node aws:///eu-west-2a/i-01518ccfad9adXXXX skipping
I0124 15:51:13.298974 1 static_autoscaler.go:565] No unschedulable pods
W0124 15:51:18.570893 1 clusterstate.go:648] Nodegroup is nil for aws:///eu-west-2a/i-01518ccfad9adXXXX
```

Nodes do have the nodegroup value, for example
```
eks.amazonaws.com/nodegroup-image=ami-0886142fd383fd785,
eks.amazonaws.com/nodegroup=spot_ci-20250124124850648900000001,
eks.amazonaws.com/sourceLaunchTemplateId=lt-04ec2eb11597d719c,
eks.amazonaws.com/sourceLaunchTemplateVersion=1,
```

We noticed this after upgrading EKS from 1.29 to 1.30. Running cluster autoscaler 9.37.0 chart version, registry.k8s.io/autoscaling/cluster-autoscaler:v1.30.0

Scale out works fine, scale in doesn't stop the elected instance for termination.

**Comment by elmiko** [comment]
@mattpopa thanks for the extra details, i'm curious which provider you are using? (is this problem more than just the clusterapi provider)

**Comment by mattpopa** [comment]
> [@mattpopa](https://github.com/mattpopa) thanks for the extra details, i'm curious which provider you are using? (is this problem more than just the clusterapi provider)

I'm using AWS, deployed the chart versioned mentioned above and this is my config (terraform template) 

```
cloudProvider: aws
awsRegion: ${region}

autoDiscovery:
  clusterName: ${cluster_name}

rbac:
  serviceAccount:
    annotations: {
        eks.amazonaws.com/role-arn: "${autoscaler_service_role_arn}"
    }
    create: false
    name: ${autoscaler_sa_name}
    automountServiceAccountToken: true

extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  expander: least-waste
  scan-interval: 5s
  scale-down-enabled: true
  scale-down-unneeded-time: 3m
  scale-down-delay-after-add: 1m
  scale-down-delay-after-delete: 1m
  scale-down-utilization-threshold: 0.1
  skip-nodes-with-local-storage: false
  skip-nodes-with-system-pods: false
  node-group-auto-discovery: "asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/${cluster_name}"

serviceMonitor:
  enabled: true
  interval: 10s
  namespace: monitoring
  selector:
    release: prometheus-operator
  path: /metrics

nodeSelector:
  pool: cluster_plumbing

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
```

it used to work ok before using mixed policy instances on the AWS ASG (used to only use spot for CI purposes, but due to increasing AWS spot capacity shortage, we need to mix it up).
