### ISSUE TITLE
(helm charts) Invalid PodSecurityPolicy for K8s > 1.21

### ISSUE THREAD

**Issue by karlmuscat** [kubernetes/autoscaler#5499]
**Which component are you using?**:

helm charts

**What version of the component are you using?**:

9.23.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS

**What did you expect to happen?**:

When enabling `PodSecurityPolicy` by setting `rbac.pspEnabled` to true, it was expected that the resource was generated properly.
 
**What happened instead?**:

The `apiVersion` in the `PodSecurityPolicy` manifest, generated by the `podsecuritypolicy.apiVersion` template, returned an empty value, resulting in the manifest being invalid. Example below (truncated):

```
apiVersion:
kind: PodSecurityPolicy
metadata:
  name: c-auto-aws-cluster-autoscaler
  labels:
    app.kubernetes.io/instance: "c-auto"
    app.kubernetes.io/name: "aws-cluster-autoscaler"
    app.kubernetes.io/managed-by: "Helm"
    helm.sh/chart: "cluster-autoscaler-9.23.0"
spec:
  # Prevents running in privileged mode
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
...
```

**How to reproduce it (as minimally and precisely as possible)**:
Locally, run `helm template --set rbac.pspEnabled=true c-auto`, and look for the generated `PodSecurityPolicy`. 

**Anything else we need to know?**:
