### ISSUE TITLE
VPA recommends 100T for memory and 100G for CPU

### ISSUE THREAD

**Issue by yogeek** [kubernetes/autoscaler#5569]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

k8s.gcr.io/autoscaling/vpa-recommender:0.11.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:18:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:12:26Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

VPA deployed as a subchart of goldilocks in a K8S clusters in AWS (not an EKS, deployed with kubeadm on EC2 instances)

The issue seems to appear if prometheus is used for recommender history via the extraArgs field (cf. values.yaml below)

**What did you expect to happen?**:

I would expect coherent values in recommendations

**What happened instead?**:

Incoherent values are shown in recommendations like `100T` for memory limite or `100G` for CPU limit
```
status:
  conditions:
  - lastTransitionTime: "2023-03-06T13:24:55Z"
    status: "True"
    type: RecommendationProvided
  recommendation:
    containerRecommendations:
    - containerName: goldilocks
      lowerBound:
        cpu: 15m
        memory: "104857600"
      target:
        cpu: 23m
        memory: "163378051"
      uncappedTarget:
        cpu: 23m
        memory: "163378051"
      upperBound:
        cpu: 100G
        memory: 100T
```

![image](https://user-images.githubusercontent.com/9500406/223130777-ff9b3faf-a2e2-479d-9a68-0b85632c21dc.png)

**How to reproduce it (as minimally and precisely as possible)**:

Deploy goldilocks with VPA with the commands below :
```
cat <<EOF >> kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goldilocks

helmCharts:
- name: goldilocks
  namespace: goldilocks
  includeCRDs: true
  releaseName: goldilocks
  repo: https://charts.fairwinds.com/stable
  valuesInline:
    # see all values in https://github.com/FairwindsOps/charts/blob/master/stable/goldilocks/values.yaml
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.7.0
    vpa:
      # vpa.enabled -- If true, the vpa will be installed as a sub-chart
      enabled: true
      # see all values in https://github.com/FairwindsOps/charts/blob/master/stable/vpa/values.yaml
      recommender:
        image:
          repository: k8s.gcr.io/autoscaling/vpa-recommender
        # In order to utilize prometheus for recommender history, we need to pass some extra flags to the recommender
        extraArgs:
          prometheus-address: |
            http://prometheus-k8s.monitoring.svc.cluster.local:9090
          storage: prometheus
      updater:
        enabled: false
EOF

kubectl create ns goldilocks
kustomize build --enable-helm . | kubectl apply -n goldilocks -f -

# enable goldilocks on its own namespace to see some recommendations coming from the VPS generated by goldilocks
kubectl label ns goldilocks goldilocks.fairwinds.com/enabled=true
```

# Additionnal information

I found a similar issue here but no more informatin : https://bugzilla.redhat.com/show_bug.cgi?id=1935794
