### ISSUE TITLE
[Priority Expander] CA Priority Expander scales up both high & low value ASGs triggered by ONE pod. 

### ISSUE THREAD

**Issue by xinxingliu90** [kubernetes/autoscaler#5655]
Hi, my team created `cluster-autoscaler-priority-expander` config map with two ASGs: 
- ASG-1   (high priority)  
- ASG-2   (low priority)

My config map looks like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: autoscaler-cloud-resource-management
data:
  priorities: |-
    10: 
      - <ASG-2>
    50: 
      - <ASG-1>
```
and I have put `- --expander=priority` in the CA. 

**Expect behavior:** 
I expect `ASG-1` to scale up first and `ASG-2` scale up when `ASG-1` is 100% scaled up. 

**Problematic behavior**
But when I submit ONE pod, both ASGs scale up! 

_( Note: I am using CA image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.1 )_

Could anyone help us find the cause why Priority Expander scales up All ASGs instead scale up the high-priority ASG?
