### ISSUE TITLE
Can't upgrade cluster-autoscaler past 9.19.4

### ISSUE THREAD

**Issue by jonny-rimek** [kubernetes/autoscaler#5678]
**Which component are you using?**:
cluster-autoscaler, helm chart 9.19.4 (the latest working version)

**What version of the component are you using?**:
helm chart 9.19.4 (the latest working version)

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version --output=yaml
clientVersion:
  buildDate: "2022-09-21T14:33:49Z"
  compiler: gc
  gitCommit: 5835544ca568b757a8ecae5c153f317e5736700e
  gitTreeState: clean
  gitVersion: v1.25.2
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-01-24T19:17:48Z"
  compiler: gc
  gitCommit: 9176fb99b52f8d5ff73d67fea27f3a638f679f8a
  gitTreeState: clean
  gitVersion: v1.24.10-eks-48e63af
  goVersion: go1.19.5
  major: "1"
  minor: 24+
  platform: linux/amd64
</pre></details>

**What environment is this in?**:
We deploy to EKS in AWS using eks managed node groups with SPOT ec2 instances. We also use the service account authentication.

**What did you expect to happen?**:
be able to upgrade past 9.19.4. I'm able to use 9.19.4 with cluster autoscaler app version 1.23 and 1.24

**What happened instead?**:
The new cluster-autoscaler pod will fail and be stuck in a state of `CrashLoopBackOff`

<details>
<pre>
I0412 09:47:18.194724       1 flags.go:57] FLAG: --add-dir-header="false"
I0412 09:47:18.195122       1 flags.go:57] FLAG: --address=":8085"
I0412 09:47:18.195127       1 flags.go:57] FLAG: --alsologtostderr="false"
I0412 09:47:18.195132       1 flags.go:57] FLAG: --aws-use-static-instance-list="false"
I0412 09:47:18.195135       1 flags.go:57] FLAG: --balance-similar-node-groups="false"
I0412 09:47:18.195139       1 flags.go:57] FLAG: --balancing-ignore-label="[]"
I0412 09:47:18.195143       1 flags.go:57] FLAG: --cloud-config="/etc/gce.conf"
I0412 09:47:18.195147       1 flags.go:57] FLAG: --cloud-provider="aws"
I0412 09:47:18.195150       1 flags.go:57] FLAG: --cloud-provider-gce-l7lb-src-cidrs="130.211.0.0/22,35.191.0.0/16"
I0412 09:47:18.195156       1 flags.go:57] FLAG: --cloud-provider-gce-lb-src-cidrs="130.211.0.0/22,209.85.152.0/22,209.85.204.0/22,35.191.0.0/16"
I0412 09:47:18.195162       1 flags.go:57] FLAG: --cluster-name=""
I0412 09:47:18.195165       1 flags.go:57] FLAG: --clusterapi-cloud-config-authoritative="false"
I0412 09:47:18.195169       1 flags.go:57] FLAG: --cordon-node-before-terminating="false"
I0412 09:47:18.195172       1 flags.go:57] FLAG: --cores-total="0:320000"
I0412 09:47:18.195176       1 flags.go:57] FLAG: --daemonset-eviction-for-empty-nodes="false"
I0412 09:47:18.195179       1 flags.go:57] FLAG: --daemonset-eviction-for-occupied-nodes="true"
I0412 09:47:18.195183       1 flags.go:57] FLAG: --debugging-snapshot-enabled="false"
I0412 09:47:18.195188       1 flags.go:57] FLAG: --emit-per-nodegroup-metrics="false"
I0412 09:47:18.195191       1 flags.go:57] FLAG: --estimator="binpacking"
I0412 09:47:18.195195       1 flags.go:57] FLAG: --expander="least-waste"
I0412 09:47:18.195199       1 flags.go:57] FLAG: --expendable-pods-priority-cutoff="-10"
I0412 09:47:18.195220       1 flags.go:57] FLAG: --feature-gates=""
I0412 09:47:18.195227       1 flags.go:57] FLAG: --gce-concurrent-refreshes="1"
I0412 09:47:18.195230       1 flags.go:57] FLAG: --gpu-total="[]"
I0412 09:47:18.195234       1 flags.go:57] FLAG: --grpc-expander-cert=""
I0412 09:47:18.195238       1 flags.go:57] FLAG: --grpc-expander-url=""
I0412 09:47:18.195242       1 flags.go:57] FLAG: --ignore-daemonsets-utilization="false"
I0412 09:47:18.195246       1 flags.go:57] FLAG: --ignore-mirror-pods-utilization="false"
I0412 09:47:18.195251       1 flags.go:57] FLAG: --ignore-taint="[]"
I0412 09:47:18.195255       1 flags.go:57] FLAG: --kubeconfig=""
I0412 09:47:18.195260       1 flags.go:57] FLAG: --kubernetes=""
I0412 09:47:18.195265       1 flags.go:57] FLAG: --leader-elect="true"
I0412 09:47:18.197376       1 flags.go:57] FLAG: --leader-elect-lease-duration="15s"
I0412 09:47:18.197392       1 flags.go:57] FLAG: --leader-elect-renew-deadline="10s"
I0412 09:47:18.197398       1 flags.go:57] FLAG: --leader-elect-resource-lock="leases"
I0412 09:47:18.197406       1 flags.go:57] FLAG: --leader-elect-resource-name="cluster-autoscaler"
I0412 09:47:18.197411       1 flags.go:57] FLAG: --leader-elect-resource-namespace=""
I0412 09:47:18.197417       1 flags.go:57] FLAG: --leader-elect-retry-period="2s"
I0412 09:47:18.197426       1 flags.go:57] FLAG: --log-backtrace-at=":0"
I0412 09:47:18.197441       1 flags.go:57] FLAG: --log-dir=""
I0412 09:47:18.197447       1 flags.go:57] FLAG: --log-file=""
I0412 09:47:18.197453       1 flags.go:57] FLAG: --log-file-max-size="1800"
I0412 09:47:18.197460       1 flags.go:57] FLAG: --logtostderr="true"
I0412 09:47:18.197466       1 flags.go:57] FLAG: --max-autoprovisioned-node-group-count="15"
Stream closed EOF for kube-system/cluster-autoscaler-aws-cluster-autoscaler-7f56fff9c4-vrfgf (aws-cluster-autoscaler)

    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x22
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x85

goroutine 277 [chan receive]:
k8s.io/client-go/tools/cache.(*controller).Run.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/controller.go:131 +0x28
created by k8s.io/client-go/tools/cache.(*controller).Run
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/controller.go:130 +0xbe

goroutine 278 [semacquire]:
sync.runtime_SemacquireMutex(0x39cccc0?, 0x1?, 0xc000c6cd58?)
    /usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x741d2d8)
    /usr/local/go/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
    /usr/local/go/src/sync/mutex.go:81
k8s.io/klog/v2.(*loggingT).output(0x741d2c0, 0x0, 0x0, 0xc000174380, 0x1, {0x5e1c1cd?, 0xc?}, 0xc00004ec00?, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:750 +0xb9
k8s.io/klog/v2.(*loggingT).printfDepth(0x741d2c0, 0x0?, 0x0, {0x0, 0x0}, 0x8d89e0?, {0x472e3c2, 0x22}, {0xc000690990, 0x3, ...})
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:630 +0x1f2
k8s.io/klog/v2.(*loggingT).printf(...)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:612
k8s.io/klog/v2.Verbose.Infof(...)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1298
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc000207420, 0xc000738f00)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/reflector.go:219 +0x168
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x22
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x85

goroutine 280 [chan receive]:
k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc000ba4770, 0xc000738f00?)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/shared_informer.go:669 +0x45
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x22
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x85

goroutine 281 [chan receive]:
k8s.io/client-go/tools/cache.(*controller).Run.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/controller.go:131 +0x28
created by k8s.io/client-go/tools/cache.(*controller).Run
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/controller.go:130 +0xbe

goroutine 290 [semacquire]:
sync.runtime_SemacquireMutex(0x39cccc0?, 0x1?, 0xc000a20d58?)
    /usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x741d2d8)
    /usr/local/go/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
    /usr/local/go/src/sync/mutex.go:81
k8s.io/klog/v2.(*loggingT).output(0x741d2c0, 0x0, 0x0, 0xc000926fc0, 0x1, {0x5e1c1cd?, 0xc?}, 0xc000100000?, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:750 +0xb9
k8s.io/klog/v2.(*loggingT).printfDepth(0x741d2c0, 0x0?, 0x0, {0x0, 0x0}, 0x0?, {0x472e3c2, 0x22}, {0xc00079a060, 0x3, ...})
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:630 +0x1f2
k8s.io/klog/v2.(*loggingT).printf(...)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:612
k8s.io/klog/v2.Verbose.Infof(...)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1298
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc000a2e0e0, 0xc000738f00)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/reflector.go:219 +0x168
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x22
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x85

goroutine 282 [semacquire]:
sync.runtime_SemacquireMutex(0x39cccc0?, 0x1?, 0xc000c6dd58?)
    /usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x741d2d8)
    /usr/local/go/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
    /usr/local/go/src/sync/mutex.go:81
k8s.io/klog/v2.(*loggingT).output(0x741d2c0, 0x0, 0x0, 0xc0001743f0, 0x1, {0x5e1c1cd?, 0xc?}, 0xc00004ec00?, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:750 +0xb9
k8s.io/klog/v2.(*loggingT).printfDepth(0x741d2c0, 0x0?, 0x0, {0x0, 0x0}, 0x0?, {0x472e3c2, 0x22}, {0xc000690a20, 0x3, ...})
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:630 +0x1f2
k8s.io/klog/v2.(*loggingT).printf(...)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:612
k8s.io/klog/v2.Verbose.Infof(...)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1298
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc000207500, 0xc000738f00)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/reflector.go:219 +0x168
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x22
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x85
Stream closed EOF for kube-system/cluster-autoscaler-aws-cluster-autoscaler-7f56fff9c4-vrfgf (aws-cluster-autoscaler)

</pre>
</details>

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade helm chart from 9.19.4

Unfortunately I can't provide a better reprocuable steps, seems to me that there is some misconfiguration, the problem is I don't know what, so I can't provide steps on how to reproduce.

**Anything else we need to know?**:
We deploy our cluster via terraform.

I updated our IAM permissions in accordance to the documentation and it currenty looks like this

```json
{
    "Statement": [
        {
            "Action": [
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:SetDesiredCapacity"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/k8s.io/cluster-autoscaler/cicd-prod": "owned"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": [
                "eks:DescribeNodegroup",
                "ec2:GetInstanceTypesFromInstanceRequirements",
                "ec2:DescribeLaunchTemplateVersions",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeImages",
                "autoscaling:DescribeTags",
                "autoscaling:DescribeScalingActivities",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeAutoScalingGroups"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        }
    ],
    "Version": "2012-10-17"
}
```

The tags on our Auto Scaling Group looks like this:

k8s.io/cluster-autoscaler/cicd-prod | owned 
-- | --
k8s.io/cluster-autoscaler/enabled | true 

As far as I could tell the errors changed after changing the iam permissions, but there is still a problem. I even tried `"eks:*", "ec2:*", "autoscaling:*"`, but I'm getting the same error, which leads me to believe that the IAM permissions are not the problem any more.

Our helm chart looks like this:

```yaml

## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# affinity -- Affinity for pod assignment
affinity: {}

autoDiscovery:
  # cloudProviders `aws`, `gce`, `magnum` and `clusterapi` are supported by auto-discovery at this time
  # AWS: Set tags as described in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup

  # autoDiscovery.clusterName -- Enable autodiscovery for `cloudProvider=aws`, for groups matching `autoDiscovery.tags`.
  # Enable autodiscovery for `cloudProvider=clusterapi`, for groups matching `autoDiscovery.labels`.
  # Enable autodiscovery for `cloudProvider=gce`, but no MIG tagging required.
  # Enable autodiscovery for `cloudProvider=magnum`, for groups matching `autoDiscovery.roles`.
  clusterName: ${cluster_name} # cluster.local

  # autoDiscovery.tags -- ASG tags to match, run through `tpl`.
  #    - kubernetes.io/cluster/${cluster_name}
  tags:
    - k8s.io/cluster-autoscaler/enabled
    - k8s.io/cluster-autoscaler/${cluster_name}


  # autoDiscovery.roles -- Magnum node group roles to match.
  roles:
    - worker

  # autoDiscovery.labels -- Cluster-API labels to match  https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/README.md#configuring-node-group-auto-discovery
  labels: []
    # - color: green
  # - shape: circle
# autoscalingGroups -- For AWS, Azure AKS or Magnum. At least one element is required if not using `autoDiscovery`. For example:
# <pre>
# - name: asg1<br />
#   maxSize: 2<br />
#   minSize: 1
# </pre>
autoscalingGroups: []
# - name: asg1
#   maxSize: 2
#   minSize: 1
# - name: asg2
#   maxSize: 2
#   minSize: 1

# autoscalingGroupsnamePrefix -- For GCE. At least one element is required if not using `autoDiscovery`. For example:
# <pre>
# - name: ig01<br />
#   maxSize: 10<br />
#   minSize: 0
# </pre>
autoscalingGroupsnamePrefix: []
# - name: ig01
#   maxSize: 10
#   minSize: 0
# - name: ig02
#   maxSize: 10
#   minSize: 0

# awsAccessKeyID -- AWS access key ID ([if AWS user keys used](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#using-aws-credentials))
awsAccessKeyID: ""

# awsRegion -- AWS region (required if `cloudProvider=aws`)
awsRegion: ${region}

# awsSecretAccessKey -- AWS access secret key ([if AWS user keys used](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#using-aws-credentials))
awsSecretAccessKey: ""

# azureClientID -- Service Principal ClientID with contributor permission to Cluster and Node ResourceGroup.
# Required if `cloudProvider=azure`
azureClientID: ""

# azureClientSecret -- Service Principal ClientSecret with contributor permission to Cluster and Node ResourceGroup.
# Required if `cloudProvider=azure`
azureClientSecret: ""

# azureResourceGroup -- Azure resource group that the cluster is located.
# Required if `cloudProvider=azure`
azureResourceGroup: ""

# azureSubscriptionID -- Azure subscription where the resources are located.
# Required if `cloudProvider=azure`
azureSubscriptionID: ""

# azureTenantID -- Azure tenant where the resources are located.
# Required if `cloudProvider=azure`
azureTenantID: ""

# azureVMType -- Azure VM type.
azureVMType: "AKS"

# azureClusterName -- Azure AKS cluster name.
# Required if `cloudProvider=azure`
azureClusterName: ""

# azureNodeResourceGroup -- Azure resource group where the cluster's nodes are located, typically set as `MC_<cluster-resource-group-name>_<cluster-name>_<location>`.
# Required if `cloudProvider=azure`
azureNodeResourceGroup: ""

# azureUseManagedIdentityExtension -- Whether to use Azure's managed identity extension for credentials. If using MSI, ensure subscription ID, resource group, and azure AKS cluster name are set.
azureUseManagedIdentityExtension: false

# magnumClusterName -- Cluster name or ID in Magnum.
# Required if `cloudProvider=magnum` and not setting `autoDiscovery.clusterName`.
magnumClusterName: ""

# magnumCABundlePath -- Path to the host's CA bundle, from `ca-file` in the cloud-config file.
magnumCABundlePath: "/etc/kubernetes/ca-bundle.crt"

# clusterAPIMode --  Cluster API mode, see https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/README.md#connecting-cluster-autoscaler-to-cluster-api-management-and-workload-clusters
# Syntax: workloadClusterMode-ManagementClusterMode
# for `kubeconfig-kubeconfig`, `incluster-kubeconfig` and `single-kubeconfig` you always must mount the external kubeconfig using either `extraVolumeSecrets` or `extraMounts` and `extraVolumes`
# if you dont set `clusterAPIKubeconfigSecret`and thus use an in-cluster config or want to use a non capi generated kubeconfig you must do so for the workload kubeconfig as well
clusterAPIMode: incluster-incluster  # incluster-incluster, incluster-kubeconfig, kubeconfig-incluster, kubeconfig-kubeconfig, single-kubeconfig

# clusterAPIKubeconfigSecret -- Secret containing kubeconfig for connecting to Cluster API managed workloadcluster
# Required if `cloudProvider=clusterapi` and `clusterAPIMode=kubeconfig-kubeconfig,kubeconfig-incluster or incluster-kubeconfig`
clusterAPIKubeconfigSecret: ""

# clusterAPIWorkloadKubeconfigPath -- Path to kubeconfig for connecting to Cluster API managed workloadcluster, only used if `clusterAPIMode=kubeconfig-kubeconfig or kubeconfig-incluster`
clusterAPIWorkloadKubeconfigPath: /etc/kubernetes/value

# clusterAPICloudConfigPath -- Path to kubeconfig for connecting to Cluster API Management Cluster, only used if `clusterAPIMode=kubeconfig-kubeconfig or incluster-kubeconfig`
clusterAPICloudConfigPath: /etc/kubernetes/mgmt-kubeconfig

# clusterAPIConfigMapsNamespace -- Namespace on the workload cluster to store Leader election and status configmaps
clusterAPIConfigMapsNamespace: ""

# cloudConfigPath -- Configuration file for cloud provider.
cloudConfigPath: /etc/gce.conf

# cloudProvider -- The cloud provider where the autoscaler runs.
# Currently only `gce`, `aws`, `azure`, `magnum` and `clusterapi` are supported.
# `aws` supported for AWS. `gce` for GCE. `azure` for Azure AKS.
# `magnum` for OpenStack Magnum, `clusterapi` for Cluster API.
cloudProvider: aws

# containerSecurityContext -- [Security context for container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
containerSecurityContext: {}
  # capabilities:
  #   drop:
#   - ALL

# dnsPolicy -- Defaults to `ClusterFirst`. Valid values are:
# `ClusterFirstWithHostNet`, `ClusterFirst`, `Default` or `None`.
# If autoscaler does not depend on cluster DNS, recommended to set this to `Default`.
dnsPolicy: ClusterFirst

## Priorities Expander
# expanderPriorities -- The expanderPriorities is used if `extraArgs.expander` contains `priority` and expanderPriorities is also set with the priorities.
# If `extraArgs.expander` contains `priority`, then expanderPriorities is used to define cluster-autoscaler-priority-expander priorities.
# See: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md
expanderPriorities: {}

# priorityConfigMapAnnotations -- Annotations to add to `cluster-autoscaler-priority-expander` ConfigMap.
priorityConfigMapAnnotations: {}
  # key1: "value1"
# key2: "value2"

# extraArgs -- Additional container arguments.
# Refer to https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca for the full list of cluster autoscaler
# parameters and their default values.
# Everything after the first _ will be ignored allowing the use of multi-string arguments.
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  scale-down-unneeded-time: 1m
  scale-down-delay-after-add: 1m
  expander: least-waste
  # write-status-configmap: true
  # status-config-map-name: cluster-autoscaler-status
  # leader-elect: true
  # leader-elect-resource-lock: endpoints
  # skip-nodes-with-local-storage: true
  # scale-down-enabled: true
  # balance-similar-node-groups: true
  # min-replica-count: 0
  # scale-down-utilization-threshold: 0.5
  # scale-down-non-empty-candidates-count: 30
  # max-node-provision-time: 15m0s
  # scan-interval: 10s
  # scale-down-delay-after-delete: 0s
  # scale-down-delay-after-failure: 3m
  # skip-nodes-with-system-pods: true
  # balancing-ignore-label_1: first-label-to-ignore
  # balancing-ignore-label_2: second-label-to-ignore

# extraEnv -- Additional container environment variables.
extraEnv: {}

# extraEnvConfigMaps -- Additional container environment variables from ConfigMaps.
extraEnvConfigMaps: {}

# extraEnvSecrets -- Additional container environment variables from Secrets.
extraEnvSecrets: {}

# envFromConfigMap -- ConfigMap name to use as envFrom.
envFromConfigMap: ""

# envFromSecret -- Secret name to use as envFrom.
envFromSecret: ""

# extraVolumeSecrets -- Additional volumes to mount from Secrets.
extraVolumeSecrets: {}
  # autoscaler-vol:
  #   mountPath: /data/autoscaler/
  # custom-vol:
  #   name: custom-secret
  #   mountPath: /data/custom/
  #   items:
  #     - key: subkey
#       path: mypath

# extraVolumes -- Additional volumes.
extraVolumes: []
  # - name: ssl-certs
  #   hostPath:
#     path: /etc/ssl/certs/ca-bundle.crt

# extraVolumeMounts -- Additional volumes to mount.
extraVolumeMounts: []
  # - name: ssl-certs
  #   mountPath: /etc/ssl/certs/ca-certificates.crt
#   readOnly: true

# fullnameOverride -- String to fully override `cluster-autoscaler.fullname` template.
fullnameOverride: ""

image:
  # image.repository -- Image repository
  repository: registry.k8s.io/autoscaling/cluster-autoscaler
  # image.tag -- Image tag
  tag: ${cluster_autoscaler_version}
  # image.pullPolicy -- Image pull policy
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # image.pullSecrets -- Image pull secrets
  pullSecrets: []
  # - myRegistrKeySecretName

# kubeTargetVersionOverride -- Allow overriding the `.Capabilities.KubeVersion.GitVersion` check. Useful for `helm template` commands.
kubeTargetVersionOverride: ""

# nameOverride -- String to partially override `cluster-autoscaler.fullname` template (will maintain the release name)
nameOverride: ""

# nodeSelector -- Node labels for pod assignment. Ref: https://kubernetes.io/docs/user-guide/node-selection/.
nodeSelector: {}

# podAnnotations -- Annotations to add to each pod.
podAnnotations: {}

# podDisruptionBudget -- Pod disruption budget.
podDisruptionBudget:
  maxUnavailable: 1
  # minAvailable: 2

# podLabels -- Labels to add to each pod.
podLabels: {}

# additionalLabels -- Labels to add to each object of the chart.
additionalLabels: {}

# priorityClassName -- priorityClassName
priorityClassName: "system-cluster-critical"

rbac:
  # rbac.create -- If `true`, create and use RBAC resources.
  create: true
  # rbac.pspEnabled -- If `true`, creates and uses RBAC resources required in the cluster with [Pod Security Policies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) enabled.
  # Must be used with `rbac.create` set to `true`.
  pspEnabled: false
  # rbac.clusterScoped -- if set to false will only provision RBAC to alter resources in the current namespace. Most useful for Cluster-API
  clusterScoped: true
  serviceAccount:
    # rbac.serviceAccount.annotations -- Additional Service Account annotations.
    annotations: {
      eks.amazonaws.com/role-arn: ${autoscaler_role}
    }
    # rbac.serviceAccount.create -- If `true` and `rbac.create` is also true, a Service Account will be created.
    create: true
    # rbac.serviceAccount.name -- The name of the ServiceAccount to use. If not set and create is `true`, a name is generated using the fullname template.
    name: ${service_account_name}
    # rbac.serviceAccount.automountServiceAccountToken -- Automount API credentials for a Service Account.
    automountServiceAccountToken: true

# replicaCount -- Desired number of pods
replicaCount: 1

# resources -- Pod resource requests and limits.
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 300Mi
  # requests:
  #   cpu: 100m
#   memory: 300Mi

# securityContext -- [Security context for pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
securityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1001
# runAsGroup: 1001

service:
  # service.annotations -- Annotations to add to service
  annotations: {}
  # service.labels -- Labels to add to service
  labels: {}
  # service.externalIPs -- List of IP addresses at which the service is available. Ref: https://kubernetes.io/docs/user-guide/services/#external-ips.
  externalIPs: []

  # service.loadBalancerIP -- IP address to assign to load balancer (if supported).
  loadBalancerIP: ""
  # service.loadBalancerSourceRanges -- List of IP CIDRs allowed access to load balancer (if supported).
  loadBalancerSourceRanges: []
  # service.servicePort -- Service port to expose.
  servicePort: 8085
  # service.portName -- Name for service port.
  portName: http
  # service.type -- Type of service to create.
  type: ClusterIP

## Are you using Prometheus Operator?
serviceMonitor:
  # serviceMonitor.enabled -- If true, creates a Prometheus Operator ServiceMonitor.
  enabled: false
  # serviceMonitor.interval -- Interval that Prometheus scrapes Cluster Autoscaler metrics.
  interval: 10s
  # serviceMonitor.namespace -- Namespace which Prometheus is running in.
  namespace: monitoring
  ## [Prometheus Selector Label](https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheus-operator-1)
  ## [Kube Prometheus Selector Label](https://github.com/helm/charts/tree/master/stable/prometheus-operator#exporters)
  # serviceMonitor.selector -- Default to kube-prometheus install (CoreOS recommended), but should be set according to Prometheus install.
  selector:
    release: prometheus-operator
  # serviceMonitor.path -- The path to scrape for metrics; autoscaler exposes `/metrics` (this is standard)
  path: /metrics

## Custom PrometheusRule to be defined
## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
## ref: https://github.com/coreos/prometheus-operator#customresourcedefinitions
prometheusRule:
  # prometheusRule.enabled -- If true, creates a Prometheus Operator PrometheusRule.
  enabled: false
  # prometheusRule.additionalLabels -- Additional labels to be set in metadata.
  additionalLabels: {}
  # prometheusRule.namespace -- Namespace which Prometheus is running in.
  namespace: monitoring
  # prometheusRule.interval -- How often rules in the group are evaluated (falls back to `global.evaluation_interval` if not set).
  interval: null
  # prometheusRule.rules -- Rules spec template (see https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#rule).
  rules: []

# tolerations -- List of node taints to tolerate (requires Kubernetes >= 1.6).
tolerations: []

# topologySpreadConstraints -- You can use topology spread constraints to control how Pods are spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains. (requires Kubernetes >= 1.19).
topologySpreadConstraints: []
  # - maxSkew: 1
  #   topologyKey: topology.kubernetes.io/zone
  #   whenUnsatisfiable: DoNotSchedule
  #   labelSelector:
  #     matchLabels:
#       app.kubernetes.io/instance: cluster-autoscaler

# updateStrategy -- [Deployment update strategy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy)
updateStrategy: {}
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0
# type: RollingUpdate
```
note that this helm chart is deployed via the helm terraform provider.
