### ISSUE TITLE
VPA high usage memory with Prometheus history provider on large cluster

### ISSUE THREAD

**Issue by wu0407** [kubernetes/autoscaler#5687]
**Which component are you using?**:
 vertical-pod-autoscaler

**What version of the component are you using?**:

Component version:
vpa: 0.13.0
kubernetes: 1.23.6
victoria metrics: 1.79.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:

vpa recommender no leak memory

**What happened instead?**:

The vpa recommender use large memory

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The cluster has 4903 pods and 3574 deployments and 1517 vpas.  I compare the memory of VPA recommender under two configurations, A is only config promethus address, B config Prometheus address and metric-for-pod-labels.
The result is B has 5GB more memory than A.
 I analyzed the code and found that the leak  point was in the `clusterstate.labelsetMap` and `clusterstate.aggregateStateMap`.  clusterstate.labelsetMap is only set on `AddOrUpdatePod`, but no garbage collection performed.  clusterstate.aggregateStateMap only  garbage collection on expired that default duration is 8 days.

I search relate issue:
https://github.com/kubernetes/autoscaler/issues/2543
https://github.com/kubernetes/autoscaler/issues/3348
https://github.com/kubernetes/autoscaler/issues/3438
https://github.com/kubernetes/autoscaler/pull/2551

### summary
1. Load all cpu memory label metrics on cluster scope from Prometheus, that lead to high memory on vpa recommender start.
2. no gc on clusterstate.labelsetMap
3. Leak vpa.aggregateContainerStates of clusterstate.Vpas on pod label change

### config
**A only config promethus address**
vpa recommender start arg:
```
      args:
          - --v=4
          - --storage=prometheus
          - --prometheus-address=http://vmselect-victoria-metrics-k8s-stack.victoria.svc:8481/select/0/prometheus
          - --prometheus-cadvisor-job-name=kubelet
```
memory usage monitor data:
![vpa-memory](https://user-images.githubusercontent.com/7602218/232263059-b93c030e-e3bf-456c-8a8d-15a70a88e52c.png)

**B config Prometheus address and metric-for-pod-labels**

vpa recommender start arg:
```
spec:
  containers:
  - args:
    - --recommender-name=default
    - --target-cpu-percentile=0.99
    - --container-name-label=container
    - --container-namespace-label=namespace
    - --container-pod-name-label=pod
    - --storage=prometheus
    - --memory-saver=true
    - --pod-label-prefix=label_
    - --metric-for-pod-labels=kube_pod_labels{job="kube-state-metrics"}[8d]
    - --pod-name-label=pod
    - --pod-namespace-label=namespace
    - --prometheus-address=http://vmselect-victoria-metrics-k8s-stack.victoria.svc:8481/select/0/prometheus
    - --prometheus-cadvisor-job-name=kubelet
    - -v=4
```
memory usage monitor data:
![vpa-memory-1](https://user-images.githubusercontent.com/7602218/232262687-8c548a66-4a18-440a-91f2-dfbeabdad84b.png)
