### ISSUE TITLE
Autoscaler not honouring PDB

### ISSUE THREAD

**Issue by DaveTaddei-CR** [kubernetes/autoscaler#583]
The CA has been observed to not honour PodDisruptionBudgets.  In this case when the cluster is scaled from 1 to 4 nodes and then scaled back down to 1 the pods which should be protected by the PodDisruptionBudget are often removed.

dns-pdb.yml
```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: dns-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
```

CA configuration
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
        - image: gcr.io/google_containers/cluster-autoscaler:v1.1.0
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --nodes=1:5:nodes.mycluster
          env:
            - name: AWS_REGION
              value: eu-west-2
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-certificates.crt"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/role: master
      dnsPolicy: Default
      hostNetwork: true
```

I will endeavour to capture logs when an event occurs however it is intermittent.

===
edit: Changed the formating to make yaml easier to read -- MaciekPytel
