### ISSUE TITLE
AWS provider warning Failed to check cloud provider has instance for fargate is flooding the log

### ISSUE THREAD

**Issue by tanvp112** [kubernetes/autoscaler#5842]
cluster-autoscaler

**What version of the component are you using?**:

v1.27.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

```
clientVersion:
  buildDate: "2023-05-17T14:14:46Z"
  compiler: gc
  gitCommit: 890a139214b4de1f01543d15003b5bda71aae9c7
  gitTreeState: clean
  gitVersion: v1.26.5
  goVersion: go1.19.9
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-04-14T20:40:28Z"
  compiler: gc
  gitCommit: abfec7d7e55d56346a5259c9379dea9f56ba2926
  gitTreeState: clean
  gitVersion: v1.27.1-eks-2f008fe
  goVersion: go1.20.3
  major: "1"
  minor: 27+
  platform: linux/amd64
```

</pre></details>

**What environment is this in?**:

AWS

cluster-autoscaler would skip checking Fargate node.

**What happened instead?**:

```
W0607 11:20:17.160735       1 clusterstate.go:1016] Failed to check cloud provider has instance for fargate-ip-<redacted>.<redacted>.compute.internal: node is not present in aws: could not find instance {aws:///ap-southeast-2b/efbff6af53-48dd3613780e4d1e825353558e31b868/fargate-ip-<redacted>.<redacted>.compute.internal efbff6af53-48dd3613780e4d1e825353558e31b868}
W0607 11:20:17.160766       1 clusterstate.go:1016] Failed to check cloud provider has instance for fargate-ip-<redacted>.<redacted>.compute.internal: node is not present in aws: could not find instance {aws:///ap-southeast-2b/efbff6af53-22db57863d5a40bb8a918a165403ddef/fargate-ip-<redacted>.<redacted>.compute.internal efbff6af53-22db57863d5a40bb8a918a165403ddef}
```

**How to reproduce it (as minimally and precisely as possible)**:

Apply the [cluster-autoscaler-one-asg](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml) example with coredns running on Fargate will do. Doesn't matter if there's any node group or workload.

**Anything else we need to know?**:

The warning message is flooding the log and causing noise. For AWS provider it probably should not warn as it is not applicable? 

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go#L86
