### ISSUE TITLE
Please add targetRef StrimziPodSet

### ISSUE THREAD

**Issue by thdonatello** [kubernetes/autoscaler#5925]
**Which component are you using?**:  recommender

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
I use recommender for seeing recommended resources for my services. It's very helpful but i can't get recommends for kafka pods because they deployed as a `kind: StrimziPodSet` (with Strimzi Kafka Operator).

It will be very cool i think to add `kind: StrimziPodSet` like:
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    service: kafka
  name: kafka
  namespace: kafka
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StrimziPodSet
    name: kafka
  updatePolicy:
    updateMode: "Off"

```
