### ISSUE TITLE
Node Readiness not found + Unregistered Node in Group

### ISSUE THREAD

**Issue by pjama** [kubernetes/autoscaler#593]
Hello,

I am trying to add a second nodePool to my k8s cluster in AWS. For reference, the there are two nodePools: `default` and `bigger`.

It seems that the `bigger` node instance _is_ being created successfully in AWS, but it is not available in the nodePool.

**Component Versions**

**K8s:** 1.7.4
**Kube-AWS:** 0.9.8
**CA:** 0.6

I have also tried upgrading CA to v0.6.1, and added `autoscaling:DescribeLaunchConfigurations` to the IAM role.

From the `cluster-autoscaler` logs:

```
auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  auto_scaling_groups.go:94] Regenerating ASG information for data-k8s-facepalm-test-Default-HBLCWNKLQOGX-Workers-1OQTHBHWTZ2XD
  leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
  polling_autoscaler.go:105] Poll finished
  clusterstate.go:397] Readiness for node group data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO not found
  static_autoscaler.go:145] 1 unregistered nodes present
  utils.go:285] Removing unregistered node aws:///us-east-1c/i-097ef5790575cd23d
  utils.go:297] Failed to remove node aws:///us-east-1c/i-097ef5790575cd23d: min size reached, nodes will not be deleted
  static_autoscaler.go:152] Failed to remove unregistered nodes: min size reached, nodes will not be deleted
  clusterstate.go:237] Failed to find readiness information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  clusterstate.go:271] Failed to find readiness information for data-k8s-facepalm-test-Bigger-B2KPINOPUD2Q-Workers-1JJ3JT4O395CO
  leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
```

The section of `cluster.yaml`:

```
worker:
  apiEndpointName: internal
  nodePools:
    - name: default
      iam:
        instanceProfile:
          arn: "{{ default_node_pool_iam_profile_arn }}"
      subnets:
        - name: PrivateInstance1
        - name: PrivateInstance2
        - name: PrivateInstance3
      securityGroupIds:
        - "{{ default_node_pool_sg_id }}"
        - "{{ bastion_ssh_access_sg_id }}"
        - "{{ default_node_pool_access_sg_id }}"
      autoScalingGroup:
        minSize: {{ default_worker_asg_min_size }}
        maxSize: {{ default_worker_asg_max_size }}
        rollingUpdateMinInstancesInService: {{ default_worker_asg_min_in_service }}
      autoscaling:
        clusterAutoscaler:
          enabled: true
      instanceType: "{{ default_worker_asg_instance_type }}"
      rootVolume:
        # Disk size (GiB) for controller node
        size: {{ default_worker_volume_size }}
      kube2IamSupport:
        enabled: true
      nodeLabels:
        data.ub.net/role: worker
      loadBalancer:
        enabled: true
        subnets:
          - name: PublicLoadBalancer1
          - name: PublicLoadBalancer2
          - name: PublicLoadBalancer3
    - name: bigger
      iam:
        instanceProfile:
          arn: "{{ default_node_pool_iam_profile_arn }}"
      subnets:
        - name: PrivateInstance1
        - name: PrivateInstance2
        - name: PrivateInstance3
      securityGroupIds:
        - "{{ default_node_pool_sg_id }}"
        - "{{ bastion_ssh_access_sg_id }}"
        - "{{ default_node_pool_access_sg_id }}"
      autoScalingGroup:
        minSize: {{ bigger_worker_asg_min_size }}
        maxSize: {{ bigger_worker_asg_max_size }}
        rollingUpdateMinInstancesInService: {{ bigger_worker_asg_min_in_service }}
      autoscaling:
        clusterAutoscaler:
          enabled: true
      instanceType: "{{ bigger_worker_asg_instance_type }}"
      rootVolume:
        # Disk size (GiB) for controller node
        size: {{ bigger_worker_volume_size }}
      kube2IamSupport:
        enabled: true
      nodeLabels:
        data.ub.net/role: worker
        data.ub.net/owner: xyz
      loadBalancer:
        enabled: true
        subnets:
          - name: PublicLoadBalancer1
          - name: PublicLoadBalancer2
          - name: PublicLoadBalancer3
```
