### ISSUE TITLE
CA won't scale the cluster up if there is a nodegroup where all nodes are NotReady

### ISSUE THREAD

**Issue by H3Cki** [kubernetes/autoscaler#5959]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

v1.27.1

Component version:

**What k8s version are you using (`kubectl version`)?**:

 v1.23.12

**What environment is this in?**:

OpenStack

**What did you expect to happen?**:

When starting Cluster Autoscaler, if there is a nodegroup where all nodes are in the NotReady state, that nodegroup does not block the scaling of nodes in other nodegroups.

**What happened instead?**:

- Cluster Autoscaler Pod logs the following error: 
`Error: static_autoscaler.go:445] Failed to scale up: Could not compute total resources: No node info for: default-worker-08d2a1ab`
- Nodegroup with faulty node (default-worker) will not scale up
- Nodegroup with valid nodes will not scale up either

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster with a default-worker node and another worker node
2. Make node default-worker faulty (e.g. stop kubelet)
3. Wait for cluster to became UNHEALTHY (health_status field)
4. Log into master node and restart the autoscaler 
5. Create and apply a deployment that works on several nodes, e.g.

6. Described error is logged in Cluster Autoscaler Pod

**Anything else we need to know?**:

Test deployment used:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  labels:
    app: stress-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: stress-test
      tier: stress-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stress-test
        tier: stress-test
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - stress-test
            topologyKey: kubernetes.io/hostname
      containers:
      - image: progrium/stress
        name: stress-test
        args:
        - "--cpu"
        - "1"
```
