### ISSUE TITLE
Cluster AutoScaler/Kube-Scheduler does not respect topologySpreadConstraints

### ISSUE THREAD

**Issue by icarthick** [kubernetes/autoscaler#5975]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
v1.27.1

Component version:

**What k8s version are you using (`kubectl version`)?**:
> kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.3-eks-a5565ad", GitCommit:"78c8293d1c65e8a153bf3c03802ab9358c0e1a14", GitTreeState:"clean", BuildDate:"2023-06-16T17:32:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

**What environment is this in?**:
EKS

**What did you expect to happen?**:
I have set topology spread constraints (based on AZ) on my Deployment, but when the pods were created, it does not honor the spread that I requested. 

In my EKS cluster, i have three ASG's each managing a single zone. Each ASG has a minimum node count of 1, with a maximum of 5. When I deploy the below mentioned manifest, i expect 6 pods to be scheduled. One should remain pending, as a result Cluster AutoScaler should kick in and deploy a new node. 

**What happened instead?**:
All the 7 pods were deployed on the three nodes, thereby violating the topology spread that was requested. I do not see pods go to a Pending state at all and a consequence no new nodes were spun up

**How to reproduce it (as minimally and precisely as possible)**:
Deploying this manifest, should showcase the problem

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: my-app
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
      topologySpreadConstraints:
        - topologyKey: "topology.kubernetes.io/zone"
          maxSkew: 1
          minDomains: 3
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: my-app
          matchLabelKeys:
            - pod-template-hash
```
