### ISSUE TITLE
Add explanations to the limitation that VPA & HPA can not be used together?

### ISSUE THREAD

**Issue by lilac** [kubernetes/autoscaler#6060]
In the ReadMe of vertical pod autoscaler, it clearly lists [this limitation](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md#known-limitations) of using VPA and HPA together. But there is no any detail explanations why they should not be used together on CPU or memory.

>Vertical Pod Autoscaler should not be used with the [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-resource-metrics) (HPA) on CPU or memory at this moment. However, you can use VPA with [HPA on custom and external metrics](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#scaling-on-custom-metrics).

We had a deep dive into the limitation, and tried to analyze the root cause of it. **Fortunately we found a solution that makes VPA and HPA working together without conflicts.** We've also done some experiments by running this solution on sandbox and staging environment with simulated production traffic. Those experiments all succeed without any issues identified.

In our experiment workload, a VPA is set up to manage only the request of CPU and memory. In addition, a HPA is set up to target CPU _average usage_ instead of _average utilization_. This difference is very important.

### Analysis
If the HPA is set up to target at CPU average utilization. As we know, the CPU utilization is calculated as the [ratio between the current usage of the resource to the requested resource](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-resource-metrics) of the pod.
```
utilization = usage / resource request
```
So after the VPA updates the resource request, the utilization also changes, causing HPA’s reaction to that to make the utilization closer to the target. In other words, HPA works on the numerator, but VPA works on the denominator; they are competing with each other. This is the essential reason why HPA and VPA are in conflict when they both target the CPU usage.

**The trick of this solution is that now HPA targets at the CPU average usage**, so even when VPA took actions to adjust the CPU request, HPA’s own target metric won’t be affected probably. This time, both VPA and HPA work in the same direction, so finally the CPU usage converges to the target we set.

Another requirement of this setup is CPU limit. It's set to a value that the actual CPU usage can hardly exceed, and larger than the target of HPA. In addition, the VPA does not manage the limit. This setup ensures the workload works well in extreme cases.

### Workload deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-web
spec:
  selector:
    matchLabels:
      app: stress-web
  template:
    metadata:
      labels:
        app: stress-web
    spec:
      imagePullSecrets:
      - name: github-registry
      containers:
      - name: stress-web
        image: ghcr.io/adrise/stress-web:main
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
```

### HPA manifest
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stress-web
spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 500m
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-web
```

### VPA manifest
```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: stress-web
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: stress-web
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 100Mi
        maxAllowed:
          cpu: 1200m
          memory: 24Gi
        controlledResources:
        - cpu
        - memory
        controlledValues: RequestsOnly
        # Note that since limit is not controlled, VPA cannot react to detected OOM pods.
```

Could you review our experiment setup and conclusion? If our analysis or conclusion is wrong, could you provide more detail explanation on this limitation?
