### ISSUE TITLE
The autoscaler does not scale node groups on non-amd64 clusters when pods explicitly require non-amd64 nodes in node affinity

### ISSUE THREAD

**Issue by aleskandro** [kubernetes/autoscaler#6064]
The autoscaler does not scale node groups on non-amd64 clusters when pods explicitly require non-amd64 nodes in node affinity

**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: master branch

Component version: any

**What k8s version are you using (`kubectl version`)?**: any

**What environment is this in?**: cluster API and most cloud providers

**What did you expect to happen?**: when the autoscaler provider build the generic labels to perform autoscale from zero decisions, most cloud providers consider `amd64` as the default architecture to use, leading a pod reporting a node selector term to be scheduled on non-amd64 nodes, unable to trigger the autoscaler although non-amd64 nodes are available in the cluster.

What behaviour did you expect to see?

Users should be allowed to override the default architecture in the buildGenericLabels method. This will not take into account cases like clusters heterogeneous in architecture (CP on arm64, DP on amd64, or CP on amd64 and DP arm64 + amd64 nodes). However, this case should be considered user-specific or cloud-provider-specific.

**What happened instead?**:

When a pod reports a node selector term like `kubernetes.io/arch in {arm64}` in an arm64 cluster, the pod does not trigger the scale out of node groups.

**How to reproduce it (as minimally and precisely as possible)**:

In any kubernetes arm64 deployment with the autoscaler enabled, try to define a deployment with node selector term `kubernetes.io/arch in {arm64}` , resource requests, and set the replicas such that a pod keeps pending scheduling due to missing resources.

Example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'my-deployment'
spec:
  selector:
    matchLabels:
      app: name
  replicas: 3
  template:
    metadata:
      labels:
        app: name
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - "arm64"
      containers:
        - name: container
          image: >-
            quay.io/openshifttest/hello-openshift:1.2.0
          resources:
              requests:
                cpu: "2"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
```
