### ISSUE TITLE
Helm chart error using vpa component 

### ISSUE THREAD

**Issue by Idan-Lazar** [kubernetes/autoscaler#6076]
**Which component are you using?**: autoscaler

vertical-pod-autoscaler
**What version of the component are you using?**:
0.14.0

image:
  repository: registry.k8s.io/autoscaling/cluster-autoscaler
  tag: v1.27.2

Helm chart version: "9.29.1"

**What k8s version are you using (`kubectl version`)?**: v1.26.1

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: Aws

Like your documentation I use:
```
vpa:
  enabled: true
  updateMode: "Auto"
  containerPolicy:
    minAllowed:
      cpu: 20m
      memory: 50Mi
```
I expected that the vpa component downloaded in my eks cluster.

I get this error:

> no matches for kind "VerticalPodAutoscaler" in version "autoscaling.k8s.io/v1"
> ensure CRDs are installed first

I tried to change the tag version of Autoscaler repo and Chart version and it's still the same.
Only when I clone the repo like your Readme it works, But I need a helm Solution.
