### ISSUE TITLE
autoscalingGroupsnamePrefix doesn't work on AWS

### ISSUE THREAD

**Issue by decoursin** [kubernetes/autoscaler#6100]
The flag [autoscalingGroupsnamePrefix](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml#L53) doesn't seem to be working.

When I have the autoscalingGroups flag set like this:
```
cluster-autoscaler:
  autoscalingGroups:
    - name: eks-base-20c54189-c0fd-cd7a-8399-568cddd4b63e
      maxSize: 4
      minSize: 2
```
It works fine, but when I use autoscalingGroupsnamePrefix, it doesn't:
```
cluster-autoscaler:
  autoscalingGroupsnamePrefix:
    - name: eks-base
      maxSize: 4
      minSize: 2
```
As a result, with the autoscalingGroupsnamePrefix set and without the autoscalingGroups set, the cluster-autoscaler Deployment gets removed.

I'm using AWS with the latest cluster-autoscaler helm chart (version: 9.29.3).
