### ISSUE TITLE
vertical-pod-autoscaler recommender doesn't work for some targets

### ISSUE THREAD

**Issue by asenyaev** [kubernetes/autoscaler#6120]
vpa-recommender doesn't work for some targetRefs on vertical-pod-autoscaler-0.13.0 and vertical-pod-autoscaler-0.14.0.

Specifically, none of the rabbitmq or redis statefulsets get any recommendation.

rabbitmq targetRef:

```
  targetRef:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rabbitmq-cluster-test
```

redis targetRef:

```
  targetRef:
    apiVersion: databases.spotahome.com/v1
    kind: RedisFailover
    name: test-redis-cluster
```

gets following vpa-recommender v0.14.0 messages on the .status.conditions:

`rabbitmq`:

```
  - lastTransitionTime: "2023-09-19T08:18:22Z"
    message: 'Cannot read targetRef. Reason: Unhandled targetRef rabbitmq.com/v1beta1
      / RabbitmqCluster / rabbitmq-cluster-test, last error rabbitmqclusters.rabbitmq.com
      "rabbitmq-cluster-test" not found'
    status: "True"
    type: ConfigUnsupported
  - lastTransitionTime: "2023-09-19T08:18:39Z"
    message: No pods match this VPA object
    reason: NoPodsMatched
    status: "True"
    type: NoPodsMatched
  - lastTransitionTime: "2023-09-19T08:18:39Z"
    message: No pods match this VPA object
    reason: NoPodsMatched
    status: "False"
    type: RecommendationProvided
```

`redis`:

```
  - lastTransitionTime: "2023-09-18T17:37:23Z"
    message: 'Cannot read targetRef. Reason: Unhandled targetRef databases.spotahome.com/v1
      / RedisFailover / test-redis-cluster, last error redisfailovers.databases.spotahome.com
      "test-redis-cluster" not found'
    status: "True"
    type: ConfigUnsupported
  - lastTransitionTime: "2023-09-18T17:37:39Z"
    message: No pods match this VPA object
    reason: NoPodsMatched
    status: "True"
    type: NoPodsMatched
  - lastTransitionTime: "2023-09-18T17:37:39Z"
    message: No pods match this VPA object
    reason: NoPodsMatched
    status: "False"
    type: RecommendationProvided
```

logs from `vpa-recommender`:

```
E0919 09:06:55.966709       1 cluster_feeder.go:532] Cannot get target selector from VPA's targetRef. Reason: Unhandled targetRef rabbitmq.com/v1beta1 / RabbitmqCluster / rabbitmq-cluster-test, last error rabbitmqclusters.rabbitmq.com "rabbitmq-cluster-test" not found
E0919 09:06:55.973140       1 cluster_feeder.go:532] Cannot get target selector from VPA's targetRef. Reason: Unhandled targetRef databases.spotahome.com/v1 / RedisFailover / test-redis-cluster, last error redisfailovers.databases.spotahome.com "test-redis-cluster" not found
```

I've seen an issue https://github.com/kubernetes/autoscaler/issues/2159 with the similar problem, but with prometheus. I also have this component, but there are no issues.

**Comment by vinu2003** [comment]
Hi,

I do notice the same issue - vpa-recommender cannot read targetRef with vpa version 0.14
I do notice for some pods.

```Status:
  Conditions:
    Last Transition Time:  2024-01-23T06:36:33Z
    Message:               Cannot read targetRef. Reason: Unhandled targetRef v1 / Pod / webapp, last error the server could not find the requested resource
    Status:                True
    Type:                  ConfigUnsupported
    Last Transition Time:  2024-01-23T06:36:33Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                True
    Type:                  NoPodsMatched
    Last Transition Time:  2024-01-23T06:36:33Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                False
    Type:                  RecommendationProvided
  Recommendation:
```

vpa-recommender pod logs

```E0123 11:43:24.885605       1 cluster_feeder.go:532] Cannot get target selector from VPA's targetRef. Reason: Unhandled targetRef v1 / Pod / webapp, last error the server could not find the requested resource```

Iam not sure if it is just for some statefulsets or for wide range of objects ? Or should I be fixing any permissions with RBAC to get this work ?

**Comment by abbyglaubit** [comment]
Hi, 

I am seeing this issue on v0.14.0, where all VPAs that target statefulsets get into a state where they do not provide recommendations.

In the VPA recommender logs:
` Using selector  for VPA <vpa name>` (note there is no selector)

The status on the VPA object is
```
status:
  conditions:
  - lastTransitionTime: "2024-04-08T15:43:29Z"
    message: The targetRef controller has a parent but it should point to a topmost
      well-known or scalable controller
    status: "True"
    type: ConfigUnsupported
  - lastTransitionTime: "2024-04-08T15:43:29Z"
    message: No pods match this VPA object
    reason: NoPodsMatched
    status: "True"
    type: NoPodsMatched
  - lastTransitionTime: "2024-04-08T15:43:29Z"
    message: No pods match this VPA object
    reason: NoPodsMatched
    status: "False"
    type: RecommendationProvided
```

Is there any update on this issue?
