### ISSUE TITLE
VPA release using Helm Chart 9.29.4

### ISSUE THREAD

**Issue by ViniciusBastosTR** [kubernetes/autoscaler#6224]
Please provide any information that is related to the release:

- When we plan to do the release?

When trying to install VPA using Helm Chart

```shell
vinicius@TR-H8F87Y3:~/repos/hub/kubernetes/autoscaler/charts/cluster-autoscaler$ helm template k8s . --set vpa.enabled=true
Error: YAML parse error on cluster-autoscaler/templates/vpa.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key

Use --debug flag to render out invalid YAML
```
- Are there any issues / PRs blocking the release?
Yes

**Comment by ViniciusBastosTR** [comment]
values.yaml:

```text
cloudProvider: clusterapi
autoDiscovery:
  clusterName: test1
  tags:
    - k8s.io/cluster-autoscaler/enabled
    - k8s.io/cluster-autoscaler/test1
    - kubernetes.io/cluster/test1
  roles:
    - worker

  labels:
    - color: green
vpa:
  enabled: true
  updateMode: "Off"
  containerPolicy: {}
```

Error trace:

```shell
Error: YAML parse error on cluster-autoscaler/templates/vpa.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 20: did not find expected key
YAML parse error on cluster-autoscaler/templates/vpa.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:259
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:264
main.newTemplateCmd.func2
        helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
```

**Comment by Shubham82** [comment]
Please take a look at the following content for VPA in README.md:
https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler#verticalpodautoscaler

**Comment by julian-perge** [comment]
I found the issue. Even when the VPA is installed in the cluster, you still have to specify the `containerName` in the helm chart.

I could not get the chart to install using terraform without this setup:

```yaml
vpa:
  enabled: true
  updateMode: "Auto"
  containerPolicy:
    containerName: aws-cluster-autoscaler
    minAllowed:
      cpu: 20m
      memory: 50Mi
```

Which is funny, because the final helm chart has this output. The helm chart needs updated. I don't know how you guys tested this and didn't catch this. It makes me think this wasn't tested at all.

```
    containerPolicies:
    - containerName: aws-cluster-autoscaler
      containerName: aws-cluster-autoscaler
      minAllowed:
        cpu: 20m
        memory: 50Mi
```
