### ISSUE TITLE
VPA doesn't provide any recommendations when CronJob is in OOMKill crash loop

### ISSUE THREAD

**Issue by FilimonovEugene** [kubernetes/autoscaler#6236]
**Which component are you using?**:

 vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 1.0.0

**What k8s version are you using (`kubectl version`)?**:

v1.25.14-eks-f8587cb

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

VPA should track CronJob OOMKilled events and adjust resources requests and limits.

**What happened instead?**:

VPA doesn't react to job OOMKilled events 

**How to reproduce it (as minimally and precisely as possible)**:

```YAML
apiVersion: batch/v1
kind: CronJob
metadata:
  name: oomkilled
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: oomkilled
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: gcr.io/google-containers/stress:v1
            name: stress
            command: [ "/stress"]
            args: 
              - "--mem-total"
              - "10485800000"
              - "--logtostderr"
              - "--mem-alloc-size"
              - "100000"
            resources:
              requests:
                memory: 100Mi
                cpu: 5m
              limits:
                memory: 1Gi

---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: oomkilled
spec:
  targetRef:
    apiVersion: "batch/v1"
    kind: CronJob
    name: oomkilled
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 50m
          memory: 10Mi
        maxAllowed:
          cpu: 1
          memory: 2Gi
        controlledResources: ["cpu", "memory"]
```

**Comment by wu0407** [comment]
Perhaps due to the short pod time, the metrics server did not obtain monitoring data.  any related log or is more detail required?

**Comment by andrii-litvinov** [comment]
That can definitely be a reason, also I would expect VPA to react on OOMKilled events and increase the memory target recommendation for the next pod start.

**Comment by adrianmoisey** [comment]
My guess is that the logic is looking for Pods that are restarted: https://github.com/kubernetes/autoscaler/blob/afb3a087f9d491435785bfaa42e7ed7b3dc750b3/vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go#L150-L152

And since this CronJob has `restartPolicy: Never`, the OOM is never detected.

I'll take a look at this and see if I can fix it.

/remove-lifecycle stale
/assign

**Comment by tkukushkin** [comment]
Is there any reason to check RestartCount? Personally, I can't imagine a situation where this would be important.

**Comment by adrianmoisey** [comment]
I think there are two problem in this issue:
1. The Cronjob is setup so that VPA can't control it 
2. The OOM detection

Since the second one is being handled by the PR, I want to focus on the first problem.

I believe the issue is this: https://github.com/kubernetes/autoscaler/issues/7499

Since the pod doesn't have a label, the VPA can't find it and can't even provide a recommendation.
Using the cronjob in the description of this issue shows mt that no recommendations are set. 
I tweaked this to:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: oomkilled
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: oomkilled
    spec:
      template:
        metadata:
          labels:
            app: oomkilled
        spec:
          restartPolicy: Never
          containers:
          - image: registry.k8s.io/e2e-test-images/agnhost:2.47
            name: stress
            args: 
              - stress
              - "--mem-total"
              - "10485800000"
              - "--mem-alloc-size"
              - "100000"
            resources:
              requests:
                memory: 100Mi
                cpu: 5m
              limits:
                memory: 1Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: oomkilled
spec:
  targetRef:
    apiVersion: "batch/v1"
    kind: CronJob
    name: oomkilled
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 50m
          memory: 10Mi
        maxAllowed:
          cpu: 1
          memory: 2Gi
        controlledResources: ["cpu", "memory"]
```

and now I do get recommendations.

Regarding the OOM detection. I tried the linked PR and it seems to work. I just need to review it more.
