### ISSUE TITLE
Add backoff data to cluster-autoscaler-status and make the status easier for parsing

### ISSUE THREAD

**Issue by walidghallab** [kubernetes/autoscaler#6318]
**Which component are you using?**:
cluster-autoscaler

**The problem this feature should solve**:
cluster-autoscaler-status config map shows which nodegroups are in backoff but it doesn't show the reasons behind backoff of nodegroups which makes debugging harder especially for large clusters.
Also the status of cluster-autoscaler doesn't confine to a pattern that is easily parsable.

**Describe the solution you'd like**:
To add backoff reason (errorCode & errorMessage) for each nodegroup being in backoff in the status field of cluster-autoscaler-status config map.

Also change the current format of status field from the current format to yaml which is both human-readable and easier in parsing.

**Example for the status field:**

Current state (Human readable string without backoff data):

```
status: |
Cluster-autoscaler status at 2023-11-24 04:28:19.546750398 +0000 UTC:
Cluster-wide:
  Health:      Healthy (ready=7 unready=0 (resourceUnready=0) notStarted=0 longNotStarted=0 registered=7 longUnregistered=0)
               LastProbeTime:      2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876
               LastTransitionTime: 2023-11-23 14:52:02.009391854 +0000 UTC m=+10.793340938
  ScaleUp:     NoActivity (ready=7 registered=7)
               LastProbeTime:      2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876
               LastTransitionTime: 2023-11-24 04:15:34.972108466 +0000 UTC m=+48223.756057543
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC

NodeGroups:
  Name:        https://www.googleapis.com/compute/v1/projects/sample-project/zones/us-central1-c/instanceGroups/gke-sample-cluster-default-pool-40ce0341-grp
  Health:      Healthy (ready=7 unready=0 (resourceUnready=0) notStarted=0 longNotStarted=0 registered=7 longUnregistered=0 cloudProviderTarget=7 (minSize=4, maxSize=10))
               LastProbeTime:      2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876
               LastTransitionTime: 2023-11-23 14:52:02.009391854 +0000 UTC m=+10.793340938
  ScaleUp:     Backoff (ready=7 cloudProviderTarget=7)
               LastProbeTime:      2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876
               LastTransitionTime: 2023-11-24 04:15:34.972108466 +0000 UTC m=+48223.756057543
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
```

Target state (yaml with backoff data): 

```yaml
status:
  time: "2023-11-24 04:28:19.546750398 +0000 UTC"
  autoscalerStatus: "Running"
  clusterWide:
    health: 
      status: "Healthy"
      nodeCounts:
        ready: 7
        unready: 0
        resourceUnready: 0
        notStarted: 0
        registered: 7
        longUnregistered: 0
      lastProbeTime: "2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876"
      lastTransitionTime: "2023-11-23 14:52:02.009391854 +0000 UTC m=+10.793340938"
    scaleUp: 
      status: "NoActivity"
      nodeCounts:
        ready: "7"
        registered: "7"
      lastProbeTime: "2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876"
      lastTransitionTime: "2023-11-24 04:15:34.972108466 +0000 UTC m=+48223.756057543"
    scaleDown:   
      status: "NoCandidates"
      candidates: 0
      lastProbeTime: "2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876"
      lastTransitionTime: "0001-01-01 00:00:00 +0000 UTC"

  nodeGroups:
    -
      name: "https://www.googleapis.com/compute/v1/projects/sample-project/zones/us-central1-c/instanceGroups/gke-sample-cluster-default-pool-40ce0341-grp"
      health:      
        status: "Healthy"
        nodeCounts:
          ready: 7
          unready: 0
          resourceUnready: 0
          notStarted: 0
          registered: 7
          cloudProviderTarget:
            targetSize: 7
            minSize: 4
            maxSize: 10
        lastProbeTime: "2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876"
        lastTransitionTime: "2023-11-23 14:52:02.009391854 +0000 UTC m=+10.793340938"
      scaleUp:   
        status: "Backoff"
        nodeCounts:
          ready: "7"
          cloudProviderTarget: "7"
        errorCode: "QUOTA_EXCEEDED"
        errorMessage: "Instance 'gke-sample-cluster-default-pool-40ce0341-t28s' creation failed: Quota 'CPUS' exceeded.  Limit: 57.0 in region us-central1., Instance 'gke-sample-cluster-default-pool-40ce0341-8pz9' creation failed: Quota 'CPUS' exceeded.  Limit: 57.0 in region us-central1., Instance 'gke-sample-cluster-default-pool-40ce0341-q8ck' creation failed: Quota 'CPUS' exceeded.  Limit: 57.0 in region us-central1."
        lastProbeTime: "2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876"
        lastTransitionTime: "2023-11-24 04:15:34.972108466 +0000 UTC m=+48223.756057543"
      scaleDown:   
        status: "NoCandidates"
        candidates: 0
        lastProbeTime: "2023-11-24 04:28:19.408724799 +0000 UTC m=+48988.192673876"
        lastTransitionTime: "0001-01-01 00:00:00 +0000 UTC"


```

**Comment by MaciekPytel** [comment]
I have a few comments to the proposed format:

- Do we need to repeat node counts in 'health' and 'scaleUp'? It seems redundant (I realize the current configmap repeats this info, but maybe that's an opportunity to clean-up?).
- I don't think minSize/maxSize should be under cloudProviderTarget. Again, current formating puts it that way, but I don't really think those are connected. Min/Max size are cluster autoscaler constraints, not cloudprovider ones (and many cloudproviders have min/max size of ASG, so putting it here makes it easy to confuse those). In your example I'd change it to:
   ```
   health:
       nodeCounts:
            (...)
            longUnregistered: 0
       cloudProviderTarget: 7
       minSize: 4
       maxSize: 10
  ```
- I'd consider putting backoff related information under something like 'backoffInfo' or similar. Using your example:
```
  scaleUp:   
        status: "Backoff"
        backoffInfo:
            errorCode: "QUOTA_EXCEEDED"
            errorMessage: "Instance 'gke-sample-cluster-default-pool-40ce0341-t28s' creation failed: Quota 'CPUS' exceeded.  Limit: 57.0 in region us-central1., Instance 'gke-sample-cluster-default-pool-40ce0341-8pz9' creation failed: Quota 'CPUS' exceeded.  Limit: 57.0 in region us-central1., Instance 'gke-sample-cluster-default-pool-40ce0341-q8ck' creation failed: Quota 'CPUS' exceeded.  Limit: 57.0 in region us-central1."
```

**Comment by walidghallab** [comment]
Good points, thanks Maciek!

> Do we need to repeat node counts in 'health' and 'scaleUp'? It seems redundant (I realize the current configmap repeats this info, but maybe that's an opportunity to clean-up?).

I agree, I'll remove remove nodeCounts from scalueUp.

> I don't think minSize/maxSize should be under cloudProviderTarget. Again, current formating puts it that way, but I don't really think those are connected. Min/Max size are cluster autoscaler constraints, not cloudprovider ones (and many cloudproviders have min/max size of ASG, so putting it here makes it easy to confuse those).

I am not sure about this one. I don't know why it is named cloudProviderTarget, rather than clusterAutoscalerTarget. In that case, minSize and maxSize are the min size and max size of autoscaler and not the node group. For example, if min size for autoscaler is 3, but the user manually removes nodes until the count is 2 and the utilization is still low, autoscaler won't scale up to 3 and the size will be smaller than the min size of the autoscaler settings.  
So, WDYT of still keeping minSize and maxSize nested as they are now, and rename cloudProviderTarget to clusterAutoscalerTarget?

> I'd consider putting backoff related information under something like 'backoffInfo' or similar. :

I agree, I'll do that.

**Comment by MaciekPytel** [comment]
Actually this discussion makes me think about whether we should nest resourceUnready under unready, or even nest a bunch of stuff under registered. Technically the correct representation would be:

```
registered:
  total: 8
  ready: 4
  unready:
    total: 3
    resourceUnready: 2
  notStarted: 1
```

This actually illustrates how the different states aggregate. Registered should equal ready+unready+notStarted. ResourceUnready nodes are already counted as 'unready' and including them in calculation would lead to double counting.
My guess is that vast majority of CA users wouldn't know the relationships between those states. I wonder if more structured representation like this would help make this more clear? Or if it would just make things harder to read and parse?

@x13n @towca @BigDarkClown opinions?
