### ISSUE TITLE
VPA recommender doesn't recommend CPU requests below 10m

### ISSUE THREAD

**Issue by dmitrii-sisutech** [kubernetes/autoscaler#6415]
**Which component are you using?**: 
vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 1.0.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.7-gke.1056000
</pre></details>

**What environment is this in?**:
GKE

**What did you expect to happen?**:
I expect Recommender to provide CPU recommendations to VPAs less than `10m` when consumption is less than `10m`.

**What happened instead?**:
Instead the smallest recommended CPU is `10m` while usage is `2-3m`. On the screenshot there're 2 pods:
<img width="196" alt="image" src="https://github.com/kubernetes/autoscaler/assets/148070131/07e17fa3-fc18-42ad-b300-6c6f66aca079">

**How to reproduce it (as minimally and precisely as possible)**:
If it's on GKE then if VPA is turned on turn it off in console.
Then 
```
./hack/vpa-down.sh
./hack/vpa-up.sh
```

**Anything else we need to know?**:

Recommender configuration:
```
        - name: recommender
          image: registry.k8s.io/autoscaling/vpa-recommender:1.0.0
          imagePullPolicy: Always
          args:
            - --v=4
            - --cpu-histogram-decay-half-life=0h2m0s
            - --history-length="3h"
            - --history-resolution="5m"
            - --pod-recommendation-min-cpu-millicores=1
```
I tried also `--pod-recommendation-min-cpu-millicores=5` and `--pod-recommendation-min-cpu-millicores=1.0` - didn't change anything. To make sure that parameter works at all tried `--pod-recommendation-min-cpu-millicores=50` and it worked.

While we stayed with GKE VPA it was setting up CPU recommendations down to `1m`.
