### ISSUE TITLE
[VPA] Does not respond to OOM for workloads with non-uniform resource utilization

### ISSUE THREAD

**Issue by emla9** [kubernetes/autoscaler#6420]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: v1.0.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.25.11
Kustomize Version: v4.5.7
Server Version: v1.25.16-eks-8cb36c9
</pre></details>

**What environment is this in?**:

EKS 1.25

**What did you expect to happen?**:

Expected that VPA would respond to OOM by adjusting the memory recommendation according to the [documented formula](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-1.0.0/vertical-pod-autoscaler/README.md#custom-memory-bump-up-after-oomkill):
```
recommendation = memory-usage-in-oomkill-event + max(oom-min-bump-up-bytes, memory-usage-in-oomkill-event * oom-bump-up-ratio)
```

**What happened instead?**:

Containers OOM continuously; VPA's recommendation is never adjusted.

**How to reproduce it (as minimally and precisely as possible)**:

The problem was originally observed with the `datadog-agent` Daemonset. Its resource needs can vary by node depending on how many pods are running there and the amount of metrics emitted. Sometimes the gap is quite signifant, like by a factor of 6. The issue is reproducible with a stress test.

Create a Deployment whose pods allocate a random amount of memory such that ~10% of them should OOM:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-stress
spec:
  replicas: 10
  selector:
    matchLabels:
      app: vpa-stress
  template:
    metadata:
      labels:
        app: vpa-stress
    spec:
      containers:
        - name: vpa-stress
          image: docker.io/elizabethla/vpa-stress:latest
          resources:
            limits:
              cpu: '1'
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 200Mi
```
Most `vpa-stress` pods will allocate between 100-160Mi of memory. The remaining 10% will allocate 650Mi of memory, causing OOM. If no OOM occurs after a couple of minutes, replace some pods to roll the dice again.

Turn up verbosity on the VPA updater:
```
containers:
  - name: updater
    args:
      - --v=4
```

Create a VPA for the Deployment:
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-stress
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
          - memory
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpa-stress
  updatePolicy:
    minReplicas: 1
    updateMode: Auto
```

Expect logs like this from the VPA updater:
```
I1228 16:14:47.820536       1 update_priority_calculator.go:114] quick OOM detected in pod vpa-stress-dev/vpa-stress-56b94449d8-w7r2h, container vpa-stress
I1228 16:14:47.820550       1 update_priority_calculator.go:140] not updating pod vpa-stress-dev/vpa-stress-56b94449d8-w7r2h because resource would not change
```

**Anything else we need to know?**:

VPA responds to OOM as expected when resource utilization across pods is uniform. As far as I can tell, the issue arises from the fact that only a small percentage of pods actually experience OOM. The target memory percentile of 90% is not affected by relatively infrequent OOM samples. This means that VPA never recommends a memory increase.

In applying VPA to a Daemonset such as the `datadog-agent` that may have non-uniform memory usage, I do not expect to reduce resource waste (all pods are subject to the same recommendation), but rather to reduce toil around manually adjusting the Daemonset's memory requests and limits as its requirements change with the workloads running on the cluster.
