### ISSUE TITLE
After upgrade 1.28.2 > 1.29.0 autoscaler fails due missing policy ec2:DescribeLaunchTemplateVersions

### ISSUE THREAD

**Issue by robinpecha** [kubernetes/autoscaler#6496]
**Which component and versions are you using?**:
LATEST - Autoscaler 1.29.0
LATEST - AWS EKS v1.29.0-eks-c417bb3
LATEST - kubectl v1.29.1
Terraform v1.7.0
Ubuntu 22.04

**What did you expect to happen?**:
After deploying it should start as previous versions.

**What happened instead?**:
Autoscaler didnt start and write this error log:
`User: arn:aws:sts::123456789101:assumed-role/company-eks-cluster-staging-worker-role/i-03c5634b964abac94 is not authorized to perform: ec2:DescribeLaunchTemplateVersions`

```
I0201 12:41:05.768933       1 auto_scaling_groups.go:396] Regenerating instance to ASG map for ASG names: []
I0201 12:41:05.768962       1 auto_scaling_groups.go:403] Regenerating instance to ASG map for ASG tags: map[k8s.io/cluster-autoscaler/company-eks-cluster-staging: k8s.io/cluster-autoscaler/enabled:]
E0201 12:41:05.977226       1 aws_manager.go:128] Failed to regenerate ASG cache: unable to retrieve instance requirements from mixed instance policy, err: UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::123456789101:assumed-role/company-eks-cluster-staging-worker-role/i-03c5634b964abac94 is not authorized to perform: ec2:DescribeLaunchTemplateVersions because no identity-based policy allows the ec2:DescribeLaunchTemplateVersions action
    status code: 403, request id: 41061c8b-a912-430e-b8bf-9ec559596de1
F0201 12:41:05.977261       1 aws_cloud_provider.go:455] Failed to create AWS Manager: unable to retrieve instance requirements from mixed instance policy, err: UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::123456789101:assumed-role/company-eks-cluster-staging-worker-role/i-03c5634b964abac94 is not authorized to perform: ec2:DescribeLaunchTemplateVersions because no identity-based policy allows the ec2:DescribeLaunchTemplateVersions action
    status code: 403, request id: 41061c8b-a912-430e-b8bf-9ec559596de1
Stream closed EOF for kube-system/cluster-autoscaler-6b4b45f496-vw7hx (cluster-autoscaler)
```
**We are deploying autoscaler with this terraform:**
```
data "template_file" "cluster_autoscaler" {
  count    = length(var.manifests)
  template = file("${path.module}/templates/autoscaler-${var.manifests[count.index]}.yaml")

  vars = {
    name             = var.autoscaler_name
    namespace        = var.autoscaler_namespace
    eks_cluster_name = var.eks_cluster_name
    image            = var.autoscaler_image
  }
}

resource "kubectl_manifest" "cluster_autoscaler" {
  count = length(data.template_file.cluster_autoscaler)

  validate_schema = false
  force_new       = true

  yaml_body = var.cluster_autoscaler_yaml == null ? data.template_file.cluster_autoscaler[count.index].rendered : var.cluster_autoscaler_yaml
}

```
**Attaching content of other configuration files in /templates/**
```
autoscaler-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: ${name}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-autoscaler-status", "cluster-autoscaler-priority-expander"]
    verbs: ["delete", "get", "update", "watch"]

```
```
autoscaler-cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${name}
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: ${name}
rules:
  - apiGroups: [""]
    resources: ["events", "endpoints"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["endpoints"]
    resourceNames: ["cluster-autoscaler"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch", "list", "get", "update"]
  - apiGroups: [""]
    resources:
      - "namespaces"
      - "pods"
      - "services"
      - "replicationcontrollers"
      - "persistentvolumeclaims"
      - "persistentvolumes"
    verbs: ["watch", "list", "get"]
  - apiGroups: ["extensions"]
    resources: ["replicasets", "daemonsets"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["watch", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "replicasets", "daemonsets"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes", "csidrivers", "csistoragecapacities"]
    verbs: ["watch", "list", "get"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
  - apiGroups: ["coordination.k8s.io"]
    resourceNames: ["cluster-autoscaler"]
    resources: ["leases"]
    verbs: ["get", "update"]
```
```
autoscaler-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: ${name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${name}
subjects:
  - kind: ServiceAccount
    name: ${name}
    namespace: ${namespace}
```
```
autoscaler-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: ${name}
  name: ${name}
  namespace: ${namespace}
```
```
autoscaler-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${name}
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: ${name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${name}
subjects:
  - kind: ServiceAccount
    name: ${name}
    namespace: ${namespace}
```
```
autoscaler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    app: ${name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
    spec:
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      serviceAccountName: ${name}
      containers:
        - image: ${image}
          name: ${name}
          resources:
            limits:
              cpu: 100m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 600Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/${eks_cluster_name}
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt 
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"

````
**Rights in aws**
I have also tried to add rights to AWSServiceRoleForAutoScaling, but it is managed by aws and cannot be changed.
![image](https://github.com/kubernetes/autoscaler/assets/9316280/7f6f2fe0-6ce1-480d-b248-665a78bf6abc)

Please do you have any hints? Thanks
