### ISSUE TITLE
Cluster Autoscaler AWS Example Issue

### ISSUE THREAD

**Issue by ForbiddenEra** [kubernetes/autoscaler#6561]
There's an example for deploying on the control plane for EKS.

There were [commits](https://github.com/kubernetes/autoscaler/commit/d872ec3db85de83acce44a8cde503dcb59014e54#commitcomment-139033055) changing `master` to `control-plane` in a lot of places, I suppose in response to [this](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint#renaming-the-node-rolekubernetesiomaster-node-taint)

Shouldn't it be like:
```yaml
      tolerations:
        - effect: NoSchedule
          operator: "Equal"
          value: "true"
          key: node-role.kubernetes.io/control-plane
      nodeSelector:
        kubernetes.io/role: control-plane
```

as is, the example as is doesn't work..?
