### ISSUE TITLE
Daemonset graceful termination is not graceful

### ISSUE THREAD

**Issue by gerasym** [kubernetes/autoscaler#6580]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
image v1.25.0

Component version:

**What k8s version are you using (`kubectl version`)?**:
1.25.14
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:
AWS

**What did you expect to happen?**:
With 
daemonset-eviction-for-empty-nodes=true
daemonset-eviction-for-occupied-nodes=true
and ds pod annotation cluster-autoscaler.kubernetes.io/enable-ds-eviction: "true"

i expected the node would be terminated after the ds pod is terminated

**What happened instead?**:
The EC2 instance was terminated by cluster-autoscaler while the ds pod was still terminating

**How to reproduce it (as minimally and precisely as possible)**:

Configure cluster-autoscaler with flags mentioned:
Run DS 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sleep-daemonset
  namespace: core-stack
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/enable-ds-eviction": "true"
      labels:
        app: sleep
    spec:
      containers:
      - name: sleeper
        image: alpine
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 120
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
      terminationGracePeriodSeconds: 150
      tolerations:
      - effect: NoSchedule
        key: component
        operator: Equal
        value: core
```

**Anything else we need to know?**:
