### ISSUE TITLE
unable to scale down when pods with pv as ephemeral storage are present

### ISSUE THREAD

**Issue by iamKunal** [kubernetes/autoscaler#6710]
**Which component are you using?**:  cluster-autoscaler installed with helm chart

**What version of the component are you using?**: Chart version: 9.34.0, Image: v1.28.2

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
❯  kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6-eks-508b6b3
</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: Scale down should work fine as the volumes are used as ephemeral store https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes

**What happened instead?**: 
`"PersistentVolume and node mismatch for pod"` and `no matching NodeSelectorTerms` and the pod being unable to be rescheduled even when the cluster has capacity.

**How to reproduce it (as minimally and precisely as possible)**: 
- Create deployments with high CPU/memory requests with ephemeral storage backed by persistent volume, so that the cluster scales up to multiple nodes.
- Decrease the memory/CPU requests

**Anything else we need to know?**:
The node group is a multi-AZ one, but I have set `skip-nodes-with-local-storage=false` and also added `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"` annotation to the pod, but I just get the mismatch error, before I did not received even that properly.

I do not care about the AZ which the pod gets assigned to as the volumes are just used as ephemeral/temporary storage, what I care about is costs, if there are 1 node in each AZ and can be combined to a single node in one of the AZs, it is fine.

Example volume ref:
```yaml
      volumes:
        - name: pod-ephemeral-storage
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: ebs-gp3-backed-sc
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 128Gi
```

Since I am using a helm chart to create such a deployment, will creating the persistent volume explicitly with specific labels, and then referring in the volumeClaimTemplate help?
