### ISSUE TITLE
Hetzner: no node labels

### ISSUE THREAD

**Issue by yellowhat** [kubernetes/autoscaler#6715]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

1.29.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
</pre></details>

**What environment is this in?**:

Hetzner

**What did you expect to happen?**:

I have `HCLOUD_CLUSTER_CONFIG`:

```json
{
    "imagesForArch": {
        "amd64": "<id>"
    },
    "nodeConfigs": {
        "pool1": {
            "cloudInit": "<blah>",
            "labels": {
                "node.kubernetes.io/role": "autoscaler-node",
                "custom/role": "test"
            }
        }
    }
}
```

and the following `args`:

```yaml
...
      containers:
        - name: cluster-autoscaler
          image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.29.0
          imagePullPolicy: "Always"
          command:
            - ./cluster-autoscaler
            - --cloud-provider=hetzner
            - --v=4
            - --scale-down-enabled
            - --ignore-daemonsets-utilization
            - --ignore-mirror-pods-utilization
            - --scale-down-unneeded-time=30s
            - --scale-down-delay-after-add=30s
            - --nodes=0:10:CPX31:NBG1:pool1
...
```

I would have expected to see the additional labels:

* `"node.kubernetes.io/role": "autoscaler-node"`
* `"custom/role": "test"`

added to the node.

**What happened instead?**:

```console
$ kubectl describe nodes pool1-53477363a36052f3
Name:               pool1-53477363a36052f3
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=cpx31
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=nbg1
                    failure-domain.beta.kubernetes.io/zone=nbg1-dc3
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=pool1-53477363a36052f3
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=cpx31
                    topology.kubernetes.io/region=nbg1
                    topology.kubernetes.io/zone=nbg1-dc3
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
...
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

* hetznercloud/hcloud-cloud-controller-manager:v1.19.0

**Comment by apricote** [comment]
/kind documentation
/area provider/hetzner

That is not well described in the README :( . The cluster-autoscaler is not responsible for setting any labels on your nodes. The `kubelet` will create the `Node` object with the Kubernetes API. The field you mentioned only tells cluster-autoscaler what labels the node will probably have, so cluster-autoscaler can figure out if the pending pods could be scheduled to a node from the node group.

You need to set these labels yourself. The easiest way to do that is in the `cloud-init` script you pass. The kubelet has a flag [`--node-labels`](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) that sets the labels on the newly created Node object. How you configure the kubelet arguments depends on your Kubernetes distribution.

**Comment by yellowhat** [comment]
Thanks for the reply, but if I set `--node-labels` to `kubelet`, HCCM will not apply its labels.

Am I missing something?

Is it the same behaviour with `taints`?

**Comment by yellowhat** [comment]
Also by default `cluster-autoscaler` is aware of these labels:

```
beta.kubernetes.io/instance-type:...
kubernetes.io/arch:...
topology.kubernetes.io/region:..
csi.hetzner.cloud/location:...
hcloud/node-group:...
```

It does account for other "default" labels, like:

```
kubernetes.io/hostname=...
```

Therefore a `deployment` with:

```yaml
...
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: app
...
```
 
will never trigger an autoscale as the `kubernetes.io/hostname` is unknown to the controller. 

I have to pass 

```
{
    "imagesForArch": {
        "amd64": "<id>"
    },
    "nodeConfigs": {
        "pool1": {
            "cloudInit": "<blah>",
            "labels": {
                "kubernetes.io/hostname": "",
            }
        }
    }
}
```
