### ISSUE TITLE
Due to capping with LimitRange CPU recommendations are not applied.

### ISSUE THREAD

**Issue by prashantkalkar** [kubernetes/autoscaler#7063]
**Which component are you using?**: vertical-pod-autoscaler

**What version of the component are you using?**: 1.1.2

Component version: 1.1.2 (image tag)

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.5
</pre></details>

**What environment is this in?**: AWS

**What did you expect to happen?**:

I have a limit range set as follows:
```
  limits:
  - default:
      cpu: "3"
    defaultRequest:
      cpu: 50m
    max:
      cpu: "3"
```
This set the CPU limit value on all pods at 3 cores. The deployment resources look like this:
```
resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 600Mi
```
As the limit range default limit is set to 3. The limit CPU can be assumed to be 3 cores. (Higher limit values are used to prevent CPU throttling in the cluster)
My VPA configuration is as follows:
```
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledValues: RequestsOnly
  targetRef:
    kind: Deployment
    name: my-deployment
  updatePolicy:
    updateMode: Auto
```
The recommendation generated by the VPA are as follows:
```
lowerBound:
  cpu: 25m
  memory: "920663787"
target:
  cpu: 1168m
  memory: "1470157273"
uncappedTarget:
  cpu: 1168m
  memory: "1470157273"
upperBound:
  cpu: 1212m
  memory: "1525707692"
```
As can be seen the recommended CPU target is 1168m. 
I expect the CPU request to be updated to 1168m but it remains at 50m. 

After reading through the document, it seems like VPA tried to scale down the request values in relationship to the max value to retain the ratio of limit and request. 

This behaviour seems to prevent setting the resource requests as per the usage, which defeat the purpose of using VPA for me. I am trying to use the VPA to reduce the overcommitment on the cluster node and improve the cluster stability. 

I feel that at least this behaviour should be configurable by the user (to prevent down scaling the request value to retain the ratio). But Current VPA behaviour for given configuration, will never update the CPU value. 

I feel that above is possible a common scenario for VPA use but if there is a preferred alternative for the VPA configuration. Please share.
