### ISSUE TITLE
Error adding metric sample for container

### ISSUE THREAD

**Issue by BestChinchilla** [kubernetes/autoscaler#7198]
**Which component are you using?**:

VPA

**What version of the component are you using?**:

Component version: 1.2.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
OKD: 4.12.0-0.okd-2023-02-04-212953
Kubernetes Version: v1.25.0-2653+a34b9e9499e6c3-dirty
</pre></details>

**What environment is this in?**:

On Premise in OpenStack

**What did you expect to happen?**:

No errors in logs every minute

**What happened instead?**:

We are getting a error something like this: `W0822 08:38:08.999233 1 cluster_feeder.go:443] Error adding metric sample for container {{openshift-multus multus-additional-cni-plugins-ql9hs} POD}: KeyError: {{openshift-multus multus-additional-cni-plugins-ql9hs} POD}
` in `recommender` pod every minute on all system NS (openshift*, kube*, calico*, tigera-operator and etc) in `OKD` cluster, in these NS there's no VPA objects created and I cannot understand why VPA trying to get metrics from pods.
I'm added new arg `--ignored-vpa-object-namespaces=tigera-operator,openshift,openshift-apiserver,...,argocd-operator` but this not resolving the issue

**How to reproduce it (as minimally and precisely as possible)**:

Just install VPA

**Anything else we need to know?**:

**Comment by adrianmoisey** [comment]
> We are getting a error something like this: `W0822 08:38:08.999233 1 cluster_feeder.go:443] Error adding metric sample for container {{openshift-multus multus-additional-cni-plugins-ql9hs} POD}: KeyError: {{openshift-multus multus-additional-cni-plugins-ql9hs} POD} `

Are some of these containers sidecars?

I'm wondering if this issue is a dupe of https://github.com/kubernetes/autoscaler/issues/6691

**Comment by BestChinchilla** [comment]
@adrianmoisey I'm checked two random pods and in first of these has 2 sidecars and 0 initcontainers, but second has not both sidecars and initcontainder, but i see this pod in log error too

**Comment by adrianmoisey** [comment]
> @adrianmoisey I'm checked two random pods and in first of these has 2 sidecars and 0 initcontainers, but second has not both sidecars and initcontainder, but i see this pod in log error too

Sounds like the issue you're facing is this bug? https://github.com/kubernetes/autoscaler/issues/7229

**Comment by BestChinchilla** [comment]
@adrianmoisey We are not using native sidecars and we have an error in pod, that don't have any initContainer or sidecar in manifest

**Comment by adrianmoisey** [comment]
Can you provide more details on reproducing this?

**Comment by BestChinchilla** [comment]
@adrianmoisey 

1. Create simple Deployment, in our case this is an application, that writes one line to PVC, but it can be anything app

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: disk-writer
  namespace: test
  labels:
    app: disk-writer
    app.kubernetes.io/component: disk-writer
    app.kubernetes.io/instance: disk-writer
    app.kubernetes.io/name: disk-writer
    app.kubernetes.io/part-of: disk-writer-app
    app.openshift.io/runtime-namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disk-writer
  template:
    metadata:
      labels:
        app: disk-writer
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
        - resources: {}
          name: disk-writer
          env:
            - name: PERIOD
              value: '1'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /data
          image: >-
            image-registry.openshift-image-registry.svc:5000/test/disk-writer@sha256:917f051beb8b255573a09bbcb61522fcbc3766a0de43ad5d9ceba8279fbc02ee
      restartPolicy: Always
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 3
```

2. Deploy VPA
- Version: 1.2.0
- Args:
            - '--address=:8942'
            - >-
              --ignored-vpa-object-namespaces=ALL_OKD_K8S_AND_SERVICES_LIKE_CALICO_NS
            - '--v=2'

3. Create VPA object

```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: test-deployment
  namespace: test
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test
  updatePolicy:
    updateMode: 'Off'
```

4. Check recommender logs, after some time you see something like this:

`
W1007 13:45:09.051207 1 cluster_feeder.go:443] Error adding metric sample for container {{test disk-writer-576495447b-gj8r4} POD}: KeyError: {{test disk-writer-576495447b-gj8r4} POD}
`
