### ISSUE TITLE
Question: node affinity + zone outage + autoscaling

### ISSUE THREAD

**Issue by paymog** [kubernetes/autoscaler#7314]
Suppose I have a deployment with the following config

```
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-west-2a
```

Suppose also that:

1. I'm using the aws autoscaler
4. I just deployed the above
5. No existing nodes in my kubernetes cluster can accept the pod because of resource constraints
6. I have 1 node group per AZ (us-west-2a, 2b, 2c and 2d)

My understanding is that by default the autoscaler will try to scale up the `us-west-2a` node group to accommodate this new deployment. Is that correct?

Now suppose also that `us-west-2a` (where this deployments wants to be scheduled) suffers an outage and new nodes cannot come online.

Given this hypothetical outage, will the autoscaler eventually realize it needs to scale up a node in a different AZ?
