### ISSUE TITLE
VPA assigns `minAllowed.memory` instead of actual recommendation when restarting Prometheus pod if `Limitrange` is set 

### ISSUE THREAD

**Issue by MatteoMori8** [kubernetes/autoscaler#7429]
**Which component are you using?**:

 - `vertical-pod-autoscaler`

**What version of the component are you using?**:
- `1.2.1`

Component version:

**What k8s version are you using (`kubectl version`)?**:

```
Server Version: v1.29.8-eks
```

**What environment is this in?**:

- AWS - `eks`

**What did you expect to happen?**:
I expected `VPA`'s AdmissionController to patch my Prometheus pod with a `request.memory` value equal to the memory target recommendation

**What happened instead?**:
Instead, the new pod got deployed with the following:
* `limit.memory` got halved 
* `request.memory` has been assigned the value that I specified as `minAllowed.memory` from the VPA object itself

On the other hand, CPU got updated correctly

**How to reproduce it (as minimally and precisely as possible)**:

<details>
<summary>VPA object</summary>
<br>

```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-test
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: prometheus
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits
      maxAllowed:
        memory: 30Gi
      minAllowed:
        cpu: 100m
        memory: 500Mi
    - containerName: thanos-sidecar
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits
      maxAllowed:
        memory: 20Gi
      minAllowed:
        memory: 100Mi
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus-test
  updatePolicy:
    updateMode: "Initial"
```
</details>

<details>
<summary>LimitRange</summary>
<br>

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - max:
      memory: 60Gi
    min:
      cpu: 1m
      memory: 50Mi
    type: Pod
  - default:
      memory: 512Mi
    defaultRequest:
      cpu: 20m
      memory: 256Mi
    min:
      memory: 50Mi
    type: Container
```
</details>

**Anything else we need to know?**:

We talked this out on the #sig-autoscaling Slack channel and it turns out that by deleting the `LimitRange`, `VPA` goes back on track and manages memory in the appropriate way.

Personally I do not know if this is a bug or an opportunity to enhance the docs but we thought it could be good to raise an Issue about it
