### ISSUE TITLE
Question: Referencing multiple recommenders in a VPA 

### ISSUE THREAD

**Issue by dwilliams782** [kubernetes/autoscaler#7444]
The VerticalPodAutoscaler object takes an array of `VerticalPodAutoscalerRecommenderSelector` under `.spec.recommenders` which allows you to specify multiple recommenders:

```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: example
  namespace: example
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: example
  updatePolicy:
    updateMode: "Off"  # recommender mode
  recommenders:
    - name: default
    - name: strict
    - name: safe
```

Under each of these recommender deployments, I can see in the logs it has registered the VPA to start tracking it. My question is... How does this actually work? surely all recommenders will now be competing against each other, so this doesn't make much sense to support multiple recommenders?

Sorry if I've missed this in the docs; I searched around the web, issues etc etc and haven't found a reference to this.
