### ISSUE TITLE
Failed to watch *v1.VolumeAttachment

### ISSUE THREAD

**Issue by madchap** [kubernetes/autoscaler#7663]
**Which component are you using?**: cluster-autoscaler on AWS

/area cluster-autoscaler

**What version of the component are you using?**: 9.45

Component version: Helm chart 9.45

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.3-eks-56e63d8

</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: I am trying to figure out why the autoscaler does not honor my ` --ok-total-unready-count=0`. It seems the node that enters the `NotReady` state is stuck with many terminating pods, and I observed at the same time the error in the autoscaler log.

The error is the following:
```
failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
```

When looking at the clusterrole created by the helm chart, I am not seeing this particular resource:
```
$ k describe clusterrole cluster-autoscaler-aws-cluster-autoscaler
Name:         cluster-autoscaler-aws-cluster-autoscaler
Labels:       app.kubernetes.io/instance=cluster-autoscaler
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=aws-cluster-autoscaler
              helm.sh/chart=cluster-autoscaler-9.45.0
Annotations:  meta.helm.sh/release-name: cluster-autoscaler
              meta.helm.sh/release-namespace: kube-system
PolicyRule:
  Resources                            Non-Resource URLs  Resource Names        Verbs
  ---------                            -----------------  --------------        -----
  endpoints                            []                 []                    [create patch]
  events                               []                 []                    [create patch]
  pods/eviction                        []                 []                    [create]
  leases.coordination.k8s.io           []                 []                    [create]
  jobs.extensions                      []                 []                    [get list patch watch]
  endpoints                            []                 [cluster-autoscaler]  [get update]
  leases.coordination.k8s.io           []                 [cluster-autoscaler]  [get update]
  configmaps                           []                 []                    [list watch get]
  pods/status                          []                 []                    [update]
  nodes                                []                 []                    [watch list create delete get update]
  jobs.batch                           []                 []                    [watch list get patch]
  namespaces                           []                 []                    [watch list get]
  persistentvolumeclaims               []                 []                    [watch list get]
  persistentvolumes                    []                 []                    [watch list get]
  pods                                 []                 []                    [watch list get]
  replicationcontrollers               []                 []                    [watch list get]
  services                             []                 []                    [watch list get]
  daemonsets.apps                      []                 []                    [watch list get]
  replicasets.apps                     []                 []                    [watch list get]
  statefulsets.apps                    []                 []                    [watch list get]
  cronjobs.batch                       []                 []                    [watch list get]
  daemonsets.extensions                []                 []                    [watch list get]
  replicasets.extensions               []                 []                    [watch list get]
  csidrivers.storage.k8s.io            []                 []                    [watch list get]
  csinodes.storage.k8s.io              []                 []                    [watch list get]
  csistoragecapacities.storage.k8s.io  []                 []                    [watch list get]
  storageclasses.storage.k8s.io        []                 []                    [watch list get]
  poddisruptionbudgets.policy          []                 []                    [watch list]
```

I am not sure, but given the ` --ok-total-unready-count=0`, I would expect the node which enters the `NotReady` state to be fairly quickly replaced by a node that can handle things.

**What happened instead?**:
The `NotReady` node sticks around for quite some time, with bunch of pods in `Terminating` state. Eventually, it'll go away after some time (maybe 30-45mn).

**How to reproduce it (as minimally and precisely as possible)**:
Something is causing my node to get to `NotReady` state, I think way too much over-committment on them, especially on memory (then the kubelet then bails out).

I am afraid I can't :-/

**Anything else we need to know?**:

An log iteration where I see the volumeattachment error:

```
I0106 17:52:52.606768       1 static_autoscaler.go:274] Starting main loop
I0106 17:52:52.609136       1 aws_manager.go:188] Found multiple availability zones for ASG "eks-default_node_group-20241211130258966500000008-7cc9dae8-63f0-63d5-bce1-642871ebd84f"; using eu-central-2b for failure-domain.beta.kubernetes.io/zone label
I0106 17:52:52.758096       1 filter_out_schedulable.go:65] Filtering out schedulables
I0106 17:52:52.758116       1 filter_out_schedulable.go:122] 0 pods marked as unschedulable can be scheduled.
I0106 17:52:52.758125       1 filter_out_schedulable.go:85] No schedulable pods
I0106 17:52:52.758130       1 filter_out_daemon_sets.go:47] Filtered out 0 daemon set pods, 0 unschedulable pods left
I0106 17:52:52.758150       1 static_autoscaler.go:532] No unschedulable pods
I0106 17:52:52.758168       1 static_autoscaler.go:555] Calculating unneeded nodes
I0106 17:52:52.758182       1 pre_filtering_processor.go:67] Skipping ip-10-0-12-37.eu-central-2.compute.internal - node group min size reached (current: 3, min: 3)
I0106 17:52:52.758204       1 pre_filtering_processor.go:67] Skipping ip-10-0-28-107.eu-central-2.compute.internal - node group min size reached (current: 3, min: 3)
I0106 17:52:52.758209       1 pre_filtering_processor.go:67] Skipping ip-10-0-36-38.eu-central-2.compute.internal - node group min size reached (current: 3, min: 3)
I0106 17:52:52.758213       1 pre_filtering_processor.go:67] Skipping ip-10-0-36-82.eu-central-2.compute.internal - node group min size reached (current: 3, min: 3)
I0106 17:52:52.758473       1 static_autoscaler.go:598] Scale down status: lastScaleUpTime=2025-01-06 16:16:32.949347114 +0000 UTC m=-3582.400670434 lastScaleDownDeleteTime=2025-01-06 16:16:32.949347114 +0000 UTC m=-3582.400670434 lastScaleDownFailTime=2025-01-06 16:16:32.949347114 +0000 UTC m=-3582.400670434 scaleDownForbidden=false scaleDownInCooldown=true
I0106 17:52:52.759061       1 orchestrator.go:322] ScaleUpToNodeGroupMinSize: NodeGroup eks-default_node_group-20241211130258966500000008-7cc9dae8-63f0-63d5-bce1-642871ebd84f, TargetSize 3, MinSize 3, MaxSize 5
I0106 17:52:52.759135       1 orchestrator.go:366] ScaleUpToNodeGroupMinSize: scale up not needed
I0106 17:52:56.201819       1 reflector.go:349] Listing and watching *v1.VolumeAttachment from pkg/mod/k8s.io/client-go@v0.32.0/tools/cache/reflector.go:251
W0106 17:52:56.206308       1 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.0/tools/cache/reflector.go:251: failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
E0106 17:52:56.206341       1 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.0/tools/cache/reflector.go:251: Failed to watch *v1.VolumeAttachment: failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cluster-autoscaler\" cannot list resource \"volumeattachments\" in API group \"storage.k8s.io\" at the cluster scope" logger="UnhandledError"
I0106 17:52:57.975501       1 reflector.go:879] pkg/mod/k8s.io/client-go@v0.32.0/tools/cache/reflector.go:251: Watch close - *v1.Node total 29 items received
```

**Comment by eon01** [comment]
Same problem with DigitalOcean / chart 9.45.0 / image 1.32.0.

```bash
kubectl get clusterrole rancher-autoscaler-rancher-cluster-autoscaler -o yaml 
```

A temporary fix would be adding the necessary permissions for `volumeattachments` to the `ClusterRole` bound to the autoscaler service account.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
[...]
rules:
- apiGroups:
  - ""
  resources:
  - events
  - endpoints
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - update
- apiGroups:
  - ""
  resourceNames:
  - cluster-autoscaler
  resources:
  - endpoints
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - watch
  - list
  - create
  - delete
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - replicationcontrollers
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - csinodes
  - csidrivers
  - csistoragecapacities
  - volumeattachments # <== This
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - cluster-autoscaler
  resources:
  - leases
  verbs:
  - get
  - update
  ```

**Comment by devops-cafex** [comment]
Seeing the same in our eks cluster missing `volumeattachements` reasources from the clusterrole

**Comment by omers** [comment]
Same for me, with a fresh installed EKS 1.31

**Comment by JnMik** [comment]
Same issue here

**Comment by devops-cafex** [comment]
Latest chart 9.45.1 on EKS 1.31 has the same issue

**Comment by TomKeyte** [comment]
Same issue :/

**Comment by ScottKinder** [comment]
I am also seeing this issue in the most current Helm chart as of today, `9.45.1`.

**Comment by TomKeyte** [comment]
I fixed this by downgrading to 9.44.0 based on this table: 

https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases

**Comment by sambonbonne** [comment]
I'm adding myself on the "same issue" list. Installed on Kubernetes 1.32.0 (managed by AWS EKS) with Helm chart 9.46.0 (latest when installing).

**Comment by VeseliD** [comment]
Hey, any updated on this issue?
I also have it in helm chart version 9.45.1

`W0210 10:09:49.458887       1 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.0/tools/cache/reflector.go:251: failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope`

**Comment by sinkr** [comment]
Same issue here on 9.46.0, even with these `values` set correctly, they're not being passed through to the ClusterRole (expressed below as `helm_release` in Terraform):

```
  values = [
    yamlencode({
      rbac = {
        create = true
        extraRules = [
          {
            apiGroups = ["storage.k8s.io"]
            resources = ["volumeattachments"]
            verbs     = ["list", "watch"]
          }
        ]
      }
    })
  ]
```

Doing this shows the changes exist in the applied values, but the SA name is not being set (last line):
```
helm get values cluster-autoscaler -n kube-system --all | yq '.rbac'   
clusterScoped: true
create: true
extraRules:
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - list
      - watch
pspEnabled: false
serviceAccount:
  annotations: {}
  automountServiceAccountToken: true
  create: true
  name: ""
```

**Comment by vitobotta** [comment]
Hi everyone,

I’ve noticed the same problem with a custom k3s cluster on Hetzner Cloud and saw the same error in the autoscaler logs. However, I tested deploying workloads with volumes on autoscaled nodes, and everything worked as expected. I didn’t encounter any issues when attaching or detaching volumes from these nodes.

What are the potential implications of the missing permission?

**Comment by rafamartos** [comment]
I faced the same issue in EKS with K8s 1.30 and the cluster-autoscaler chart version 9.46.0

**Workaround:**
Since I'm using FluxCD to deploy the chart, I've added this manifest with the missing permission to the cluster-autoscaler deployment:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler-volumeattachments
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler-volumeattachments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler-volumeattachments
subjects:
  - kind: ServiceAccount
    name: <your-service-account-name>
    namespace: <your-namespace>
```
