### ISSUE TITLE
ServiceMonitor configuration is confusing in Helm chart

### ISSUE THREAD

**Issue by darnone** [kubernetes/autoscaler#7913]
**Which component are you using?**:

Cluster-autoscaler Helm chart

**What version of the component are you using?**
App 1.32.0, chart 9.46.3:

Component version: chart 9.46.3

**What k8s version are you using (`kubectl version`)?**: 1.30.9

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:
AWS EKS

**What did you expect to happen?**:

Proper coordinfination of labels in service monitor

**What happened instead?**:

The service monitor template uses the following for metadata.labels:

```
{{- range $key, $value := .Values.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
  ```

which are set in the helm chart values. However, the match labels uses:
```
selector:
    matchLabels:
{{ include "cluster-autoscaler.instance-name" . | indent 6 }}
```

Which comes from the _helper.tpl and is defined as:
```
{{- define "cluster-autoscaler.instance-name" -}}
app.kubernetes.io/instance: {{ .Release.Name | quote }}
app.kubernetes.io/name: {{ include "cluster-autoscaler.name" . | quote }}
{{- end -}}
```
 and in addition name is prepended:
```
{{- define "cluster-autoscaler.name" -}}
{{- default (printf "%s-%s" .Values.cloudProvider .Chart.Name) .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

This requires the user:
 - to know the instance name
 - to understand the match labels have 2 parameters
 - to understand the cloud provider is prepended with the cloud provide name
 - 
**How to reproduce it (as minimally and precisely as possible)**:

add following to chart values:
```
serviceMonitor:
  enabled: "true"
  interval: 10s
  namespace: monitoring
  selector:
    release: kube-prometheus-stack
    app.kubernetes.io/instance: "cluster-autoscaler"
    app.kubernetes.io/name: "aws-cluster-autoscaler"
  path: /metrics
```

**Anything else we need to know?**:

this is confusing
