### ISSUE TITLE
Scaling down based on target

### ISSUE THREAD

**Issue by 23navi** [kubernetes/autoscaler#7982]
Hello, I have doubt regarding HPA

```
spec:
  scaleTargetRef:
    ...
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale UP if CPU > 70%
```

With this the HPA will scale up if CPU load > 70% 
What if I want to scale down if the CPU load is < 20%??

In docs I don't see any reference of scaling down and chatgpt is telling to add 

```
spec:
  scaleTargetRef:
    ...
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale UP if CPU > 70%
  scaleDownThreshold: 20
```

Which seems stupid as there can be multiple metrics and how will it associate this field with right metric?
