### ISSUE TITLE
VPA: `spec.controlledResources` should still allow recommender to update statuses of other resources

### ISSUE THREAD

**Issue by jklaw90** [kubernetes/autoscaler#8030]
**Which component are you using?**: Vertical Pod Autoscaler

/area vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We want to use VPA to only update CPU requests while still providing recommendations about memory. 
With the following spec we lose memory statuses on the VPA cr, due to `controlledResources` being set. 
```yaml
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      controlledValues: RequestsOnly
```

**Describe the solution you'd like.**:

Ideally `controlledResources` doesn't impact recommenders logic, and the updater and webhook are smart enough to only concern themself with controlled resources (may already do this).

**Describe any alternative solutions you've considered.**:

Without this change we would require multiple VPA cr's to see memory statuses, but the information already appears to be on the checkpoints so it seems pointless not to add it to the VPA status.

**Additional context.**:
