### ISSUE TITLE
CA can trigger scale UP GKE nodepool with GPU and MPS enabled

### ISSUE THREAD

**Issue by aaktaev** [kubernetes/autoscaler#8129]
**Which component are you using?**:
```
registry.k8s.io/autoscaling/cluster-autoscaler:v1.32.1
```

**What version of the component are you using?**:
```
v1.32.1
```

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

```
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.4-gke.1106000
```
</pre></details>

**What environment is this in?**:
GKE cluster 1.32 with several nodepools.
One of the nodepool has gpu accelerator + :
```
       gpu_sharing_config {
          gpu_sharing_strategy = "mps"
          max_shared_clients_per_gpu = 8
      }


```
So I'm expecting `nvidia.com/gpu: 8` is available on the "gpu" node that should be scaled up.

**What did you expect to happen?**:
I am launching pod with resources:
```
        resources:
          limits:
            cpu: 1500m
            memory: 5625Mi
            nvidia.com/gpu: "2"
          requests:
            cpu: 1500m
            memory: 5625Mi
            nvidia.com/gpu: "2"
```

Logs from CA:

`I0515 08:39:01.064193       1 orchestrator.go:588] Pod project-test/d-simple-9df8d958b-7cdvf can't be scheduled on https://www.googleapis.com/compute/v1/projects/$PROJECT/zones/europe-west1-b/instanceGroups/gke-k8s-standardgpu-4def78d5-grp, predicate checking error: can't schedule pod project-test/d-simple-9df8d958b-7cdvf: predicate "NodeResourcesFit" didn't pass (predicateReasons=[Insufficient nvidia.com/gpu]; debugInfo=nodeName: "template-node-for-https://www.googleapis.com/compute/v1/projects/$PROJECT/zones/europe-west1-b/instanceGroups/gke-k8s-standardgpu-4def78d5-grp-8458829548540998666")`

CA start with next args:
```
        - ./cluster-autoscaler
        - --cloud-provider=gce
        - --namespace=default
        - --node-group-auto-discovery=mig:namePrefix=gke-k8s-system,min=0,max=8
        - --node-group-auto-discovery=mig:namePrefix=gke-k8s-standardgpu,min=0,max=3
        - --logtostderr=true
        - --stderrthreshold=info
        - --v=4
```

**What happened instead?**:
Nothing happens, pod can't trigger scale up.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Manual scale via gcp WEB works OK and pod can be launched on the "gpu" node.

**Comment by aaktaev** [comment]
<img width="688" alt="Image" src="https://github.com/user-attachments/assets/942f5fb3-c3bc-4097-8a83-2234e82bd85c" />

**Comment by aaktaev** [comment]
<img width="1006" alt="Image" src="https://github.com/user-attachments/assets/d8211639-7097-425d-9c48-2d77821ea46f" />

**Comment by aaktaev** [comment]
Pods toleration:
```
      tolerations:
      - effect: NoExecute
        key: nodepool-name.kubernetes.io
        operator: Equal
        value: standardgpu
```

Pods affinity:
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool-name.kubernetes.io
                operator: In
                values:
                - standardgpu
```
