### ISSUE TITLE
Question: How do I setup PodDisruptionBudget for CA?

### ISSUE THREAD

**Issue by yukha-dw** [kubernetes/autoscaler#8158]
Hello, how do I setup PodDisruptionBudget for CA?
I've setup CA 1.31.2 on `kube-system` namespace and minimal parameter for K8s on AWS deployment. 

I've also created PDB using apiVersion `policy/v1`:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: application-pdb-dev
  namespace: default
spec:
  minAvailable: 999
  selector:
    matchLabels:
      app: application-dev
```

And based on CA's log, it seems acknowledge my PDB:
```
I0523 04:06:26.449751       1 reflector.go:871] pkg/mod/k8s.io/client-go@v0.31.7/tools/cache/reflector.go:243: Watch close - *v1.PodDisruptionBudget total 9 items received
```

However, when the load is low, it'll scale down `application-dev` Pods, ignoring my PDB. Is there any additional configuration that I should've add? Thank you in advance

Versions:
Provider: AWS
CA: 1.31.2
K8s: 1.31.7
