### ISSUE TITLE
Cluster Autoscaler not scaling down Nodes where Pods with hard topology spread constraints are scheduled

### ISSUE THREAD

**Issue by towca** [kubernetes/autoscaler#8162]
**Which component are you using?**:

/area cluster-autoscaler

**What did you expect to happen?**:

When CA encounters underutilized Nodes where Pods using hard topology spread constraints are scheduled, I'd expect it to consolidate the Nodes to the minimal number that fits all Pods and still satisfies the topology spread constraints.

**What happened instead?**:

Instead, Cluster Autoscaler never consolidates such Nodes, because it thinks that the Pods can't be rescheduled. However, when the Nodes are deleted manually, their scheduled Pods are recreated and successfully scheduled on other Nodes by the scheduler.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Deployment of Pods using topology spread constraints targeting a specific NodeGroup with 0 Nodes (GKE-specific example):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repro
spec:
  replicas: 12
  selector:
    matchLabels:
      app: repro
  template:
    metadata:
      labels:
        app: repro
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          requests:
            cpu: 200m
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: repro
          minDomains: 3
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      nodeSelector:
         beta.kubernetes.io/instance-type: e2-standard-2
```

2. Wait for Cluster Autoscaler to scale the NodeGroup up, for the Pods to schedule, and for CA to delete leftover empty Nodes caused by #8161.
3. Inspect the Pod placement on the leftover Nodes. There should be at least 1 Node from which the Pods could be rescheduled to other Nodes (the Node with the lowest number of scheduled Pods).
4. Inspect CA scale-down logs for this Node, verify that CA thinks that the Pods can't be rescheduled from it.
5. Delete the Node manually.
6. Observe the recreated Pods getting scheduled on other Nodes.

**Anything else we need to know?**:

This is the root cause:
* When CA evaluates scaling a Node down, it first [removes all scheduled Pods from the Node](https://github.com/kubernetes/autoscaler/blob/0d8f5871189fe896443512bc16d9853d1afcc1ae/cluster-autoscaler/simulator/cluster.go#L223) in the cluster simulation state. Then it [calls `TrySchedulePods`](https://github.com/kubernetes/autoscaler/blob/0d8f5871189fe896443512bc16d9853d1afcc1ae/cluster-autoscaler/simulator/cluster.go#L237) which iterates over the removed Pods and other eligible Nodes in the simulation state and checks scheduler Filters on them to see if the Pods can be rescheduled to other Nodes.
* The `isNodeAcceptable` argument passed to `TrySchedulePods` ensures that the Node being evaluated is not checked. However, the Node isn't actually removed from the simulation state.
* Because the Node being evaluated is still in the cluster simulation state, it's being counted as a valid domain for the constraint topology. But all the constraint-matching Pods got removed from it, so there are 0 Pods matching the constraint in this domain. This means that the global minimum for the constraint topology will always be 0 for the rest of the simulation.
* Since all the other Nodes have at least 1 constraint-matching Pod (otherwise CA would remove them as empty), CA can't schedule the removed Pods on any of them - it would bring the constraint-matching Pods on a Node to 2, skewing more than 1 from the global minimum of 0.

The fix here is obvious - CA should be removing the Node from the simulation altogether after removing the Pods from it. Then the global minimum would be the lowest number of constraint-matching Pods among the remaining Nodes, and CA could reschedule each Pod to the Node with that lowest number during the simulation.
